; Wolf Language — LLVM IR Output
; Generated by wolf compiler

target triple = "x86_64-pc-linux-gnu"

; --- String Constants ---
@.str.15 = private unnamed_addr constant [9 x i8] c"required\00"
@.str.16 = private unnamed_addr constant [4 x i8] c"bio\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"25\00"
@.str.5 = private unnamed_addr constant [5 x i8] c"name\00"
@.str.13 = private unnamed_addr constant [17 x i8] c"required|integer\00"
@.str.2 = private unnamed_addr constant [17 x i8] c"wolf@example.com\00"
@.str.17 = private unnamed_addr constant [1 x i8] c"\00"
@.str.14 = private unnamed_addr constant [3 x i8] c"16\00"
@.str.1 = private unnamed_addr constant [6 x i8] c"email\00"
@.str.3 = private unnamed_addr constant [4 x i8] c"age\00"
@.str.6 = private unnamed_addr constant [5 x i8] c"Wolf\00"
@.str.10 = private unnamed_addr constant [6 x i8] c"valid\00"
@.str.11 = private unnamed_addr constant [8 x i8] c"invalid\00"
@.str.12 = private unnamed_addr constant [13 x i8] c"not-an-email\00"
@.str.18 = private unnamed_addr constant [9 x i8] c"nullable\00"
@.str.7 = private unnamed_addr constant [15 x i8] c"required|email\00"
@.str.8 = private unnamed_addr constant [24 x i8] c"required|integer|min:18\00"
@.str.9 = private unnamed_addr constant [23 x i8] c"required|min:2|max:100\00"

; --- External Runtime Functions ---
declare void @wolf_print_str(ptr)
declare void @wolf_throw(ptr)
declare i1 @wolf_has_error()
declare ptr @wolf_get_error()
declare void @wolf_clear_error()
declare void @wolf_print_int(i64)
declare void @wolf_print_float(double)
declare void @wolf_print_bool(i1)
declare void @wolf_print_nil()
declare void @wolf_println()
declare ptr @wolf_string_concat(ptr, ptr)
declare i64 @wolf_string_length(ptr)
declare ptr @wolf_string_upper(ptr)
declare ptr @wolf_string_lower(ptr)
declare ptr @wolf_string_trim(ptr)
declare ptr @wolf_int_to_string(i64)
declare ptr @wolf_float_to_string(double)
declare ptr @wolf_bool_to_string(i1)

; --- Math ---
declare double @wolf_math_abs(double)
declare double @wolf_math_ceil(double)
declare double @wolf_math_floor(double)
declare double @wolf_math_max(double, double)
declare double @wolf_math_min(double, double)
declare i64 @wolf_math_random(i64, i64)
declare double @wolf_math_sin(double)
declare double @wolf_math_cos(double)
declare double @wolf_math_tan(double)
declare double @wolf_math_asin(double)
declare double @wolf_math_acos(double)
declare double @wolf_math_atan(double)
declare double @wolf_math_atan2(double, double)
declare double @wolf_math_sqrt(double)
declare double @wolf_math_pow(double, double)
declare double @wolf_math_log(double)
declare double @wolf_math_log10(double)
declare double @wolf_math_exp(double)
declare double @wolf_math_round(double, i64)
declare double @wolf_math_fmod(double, double)
declare double @wolf_math_pi()
declare ptr @wolf_number_format(double, i64, ptr, ptr)
declare i64 @wolf_strings_length(ptr)

; --- Database (Mock) ---
declare ptr @wolf_db_connect(ptr, ptr, ptr, ptr)
declare ptr @wolf_db_prepare(ptr, ptr)
declare void @wolf_db_bind(ptr, ptr, ptr)
declare i64 @wolf_db_execute(ptr)
declare ptr @wolf_db_fetch_all(ptr)
declare ptr @wolf_db_fetch_one(ptr)
declare i64 @wolf_db_row_count(ptr)
declare i64 @wolf_db_last_insert_id(ptr)
declare void @wolf_db_close(ptr)
declare void @wolf_db_begin_transaction(ptr)
declare void @wolf_db_commit(ptr)
declare void @wolf_db_rollback(ptr)

; --- Stdlib Strings & JSON ---
declare i1 @wolf_strings_contains(ptr, ptr)
declare ptr @wolf_strings_upper(ptr)
declare ptr @wolf_strings_title(ptr)
declare ptr @wolf_strings_split(ptr, ptr)
declare ptr @wolf_strings_trimleft(ptr, ptr)
declare ptr @wolf_strings_trimright(ptr, ptr)
declare ptr @wolf_strings_join(ptr, ptr)
declare ptr @wolf_json_encode(ptr)

; --- Output & Display ---
declare void @wolf_say(ptr)
declare void @wolf_show(ptr)
declare void @wolf_inspect(ptr)

; --- Closures ---
declare ptr @wolf_closure_create(ptr, i64)
declare void @wolf_closure_set_env(ptr, i64, ptr)
declare ptr @wolf_closure_get_env(ptr, i64)
declare ptr @wolf_closure_get_fn(ptr)

; --- Phase 1 Stdlib: Strings ---
declare ptr @wolf_strtoupper(ptr)
declare ptr @wolf_strtolower(ptr)
declare ptr @wolf_ucfirst(ptr)
declare ptr @wolf_ucwords(ptr)
declare ptr @wolf_lcfirst(ptr)
declare ptr @wolf_trim(ptr)
declare ptr @wolf_ltrim(ptr)
declare ptr @wolf_rtrim(ptr)
declare i1 @wolf_str_contains(ptr, ptr)
declare i1 @wolf_str_starts_with(ptr, ptr)
declare i1 @wolf_str_ends_with(ptr, ptr)
declare ptr @wolf_str_replace(ptr, ptr, ptr)
declare ptr @wolf_str_repeat(ptr, i64)
declare ptr @wolf_str_pad(ptr, i64, ptr)
declare ptr @wolf_explode(ptr, ptr)
declare ptr @wolf_implode(ptr, ptr)
declare ptr @wolf_substr(ptr, i64, i64)
declare i64 @wolf_strpos(ptr, ptr)
declare i64 @wolf_strrpos(ptr, ptr)
declare i64 @wolf_str_word_count(ptr)
declare i64 @wolf_strcmp(ptr, ptr)
declare ptr @wolf_nl2br(ptr)
declare ptr @wolf_strip_tags(ptr)
declare ptr @wolf_htmlspecialchars(ptr)
declare ptr @wolf_addslashes(ptr)
declare ptr @wolf_stripslashes(ptr)
declare ptr @wolf_sprintf(ptr, ...)
declare ptr @wolf_http_req_file(i64, ptr)
declare i64 @wolf_http_req_file_count(i64)
declare void @wolf_http_header(ptr, ptr)
declare void @wolf_http_status(i64)
declare ptr @wolf_http_query(ptr)
declare i1 @wolf_strings_isempty(ptr)
declare ptr @wolf_strings_substring(ptr, i64, i64)
declare i64 @wolf_math_randomint(i64)
declare ptr @wolf_str_ireplace(ptr, ptr, ptr)
declare ptr @wolf_htmlspecialchars_decode(ptr)
declare double @wolf_similar_text(ptr, ptr)
declare ptr @wolf_wordwrap(ptr, i64, ptr, i1)
declare ptr @wolf_quoted_printable_encode(ptr)
declare ptr @wolf_ws_on_message(ptr)
declare ptr @wolf_ws_on_close(ptr)
declare ptr @wolf_ws_send(i64, ptr)
declare void @wolf_ws_broadcast(ptr)
declare void @wolf_ws_join(i64, ptr)
declare void @wolf_ws_broadcast_to(ptr, ptr)
declare void @wolf_presence_track(i64, ptr)
declare ptr @wolf_presence_list(ptr)
declare void @wolf_ws_close(i64)

; --- Phase 1 Stdlib: Regex ---
declare i1 @wolf_preg_match(ptr, ptr)
declare ptr @wolf_preg_match_captures(ptr, ptr)
declare i64 @wolf_preg_match_all(ptr, ptr)
declare ptr @wolf_preg_replace(ptr, ptr, ptr)
declare ptr @wolf_preg_split(ptr, ptr)

; --- Math Extras ---
declare double @wolf_deg2rad(double)
declare double @wolf_rad2deg(double)
declare double @wolf_clamp(double, double, double)

; --- Type Casting ---
declare i64 @wolf_intval(ptr)
declare double @wolf_floatval(ptr)
declare ptr @wolf_strval(i64)
declare i1 @wolf_boolval(ptr)
declare i64 @wolf_intdiv(i64, i64)
declare ptr @wolf_gettype(ptr)
declare i1 @wolf_is_numeric(ptr)
declare ptr @wolf_typeof(ptr)
declare i1 @wolf_is_string(ptr)
declare i1 @wolf_is_int(ptr)
declare i1 @wolf_is_float(ptr)
declare i1 @wolf_is_bool(ptr)
declare i1 @wolf_is_null(ptr)
declare i1 @wolf_is_array(ptr)
declare ptr @wolf_settype(ptr, ptr)
declare ptr @wolf_money_format(i64, ptr)
declare i64 @wolf_money_add(i64, i64)
declare i64 @wolf_money_subtract(i64, i64)
declare i64 @wolf_money_multiply(i64, double)
declare i64 @wolf_money_divide(i64, double)
declare i64 @wolf_money_percentage(i64, double)
declare ptr @wolf_pluralise(ptr, i64)
declare ptr @wolf_phone_format(ptr, ptr)
declare void @wolf_log_debug(ptr)
declare void @wolf_retry_sleep(i64, i64)

; --- Encoding ---
declare ptr @wolf_base64_encode(ptr)
declare ptr @wolf_base64_decode(ptr)
declare ptr @wolf_json_pretty(ptr)
declare ptr @wolf_json_decode(ptr)

; --- Security & Crypto ---
declare ptr @wolf_md5(ptr)
declare ptr @wolf_sha256(ptr)
declare ptr @wolf_sha512(ptr)
declare ptr @wolf_hash(ptr, ptr)
declare ptr @wolf_hash_hmac(ptr, ptr, ptr)
declare i1 @wolf_hash_equals(ptr, ptr)
declare ptr @wolf_password_hash(ptr)
declare i1 @wolf_password_verify(ptr, ptr)
declare i1 @wolf_password_needs_rehash(ptr)
declare ptr @wolf_encrypt(ptr, ptr)
declare ptr @wolf_decrypt(ptr, ptr)
declare ptr @wolf_rand_bytes(i64)
declare ptr @wolf_rand_hex(i64)
declare ptr @wolf_rand_token()
declare ptr @wolf_uuid_v4()
declare ptr @wolf_uuid_v7()
declare ptr @wolf_nanoid(i64)
declare ptr @wolf_custom_id(ptr, i64)
declare ptr @wolf_base64_url_encode(ptr)
declare ptr @wolf_base64_url_decode(ptr)
declare ptr @wolf_hex_encode(ptr)
declare ptr @wolf_hex_decode(ptr)
declare ptr @wolf_jwt_encode(ptr, ptr)
declare ptr @wolf_jwt_decode(ptr, ptr)
declare ptr @wolf_jwt_decode_unverified(ptr)
declare i1 @wolf_jwt_expired(ptr)
declare ptr @wolf_curve25519_keypair()
declare ptr @wolf_curve25519_shared(ptr, ptr)
declare ptr @wolf_sign(ptr, ptr)
declare i1 @wolf_verify(ptr, ptr, ptr)

; --- Debugging ---
declare void @wolf_dump(ptr)
declare void @wolf_dd(ptr)
declare void @wolf_log_info(ptr)
declare void @wolf_log_warning(ptr)
declare void @wolf_log_error(ptr)

; --- Time & System ---
declare i64 @wolf_time_now()
declare ptr @wolf_time_date(ptr, i64)
declare i64 @wolf_time_strtotime(ptr)
declare void @wolf_system_sleep(i64)
declare void @wolf_system_exit(i64)
declare void @wolf_system_die(ptr)
declare ptr @wolf_env_get(ptr, ptr)

; --- Phase 2: Arrays ---
declare i64 @wolf_count(ptr)
declare i1 @wolf_in_array(ptr, ptr)
declare i64 @wolf_array_search(ptr, ptr)
declare ptr @wolf_array_pop(ptr)
declare ptr @wolf_array_shift(ptr)
declare void @wolf_array_unshift(ptr, ptr)
declare ptr @wolf_array_reverse(ptr)
declare ptr @wolf_array_unique(ptr)
declare ptr @wolf_array_merge(ptr, ptr)
declare ptr @wolf_array_slice(ptr, i64, i64)
declare void @wolf_sort(ptr)
declare void @wolf_rsort(ptr)
declare double @wolf_array_sum(ptr)
declare ptr @wolf_array_keys(ptr)
declare ptr @wolf_array_values(ptr)
declare ptr @wolf_array_diff(ptr, ptr)
declare ptr @wolf_array_intersect(ptr, ptr)
declare ptr @wolf_array_flip(ptr)
declare ptr @wolf_range(i64, i64)

; --- Phase 2 Stdlib: Additional Array Functions ---
declare ptr @wolf_array_fill(i64, i64, ptr)
declare ptr @wolf_array_combine(ptr, ptr)
declare ptr @wolf_array_chunk(ptr, i64)
declare ptr @wolf_array_column(ptr, ptr)
declare double @wolf_array_product(ptr)
declare ptr @wolf_array_diff_key(ptr, ptr)
declare ptr @wolf_array_splice(ptr, i64, i64)
declare ptr @wolf_array_pad(ptr, i64, ptr)
declare ptr @wolf_array_count_values(ptr)
declare i64 @wolf_array_rand_one(ptr)
declare double @wolf_array_mean(ptr)
declare double @wolf_array_median(ptr)
declare ptr @wolf_array_mode(ptr)
declare double @wolf_array_variance(ptr)
declare double @wolf_array_std_dev(ptr)
declare double @wolf_array_percentile(ptr, double)

; --- Phase 3: Date/Time ---
declare i64 @wolf_time_ms()
declare i64 @wolf_time_ns()
declare i64 @wolf_mktime(i64, i64, i64, i64, i64, i64)
declare i64 @wolf_date_diff(i64, i64)
declare ptr @wolf_date_format(i64, ptr)
declare i64 @wolf_day_of_week(i64)
declare i64 @wolf_days_in_month(i64, i64)
declare i1 @wolf_is_leap_year(i64)
declare i64 @wolf_strtotime(ptr)
declare i64 @wolf_date_create(ptr)
declare i64 @wolf_date_add_days(i64, i64)
declare i64 @wolf_date_add_months(i64, i64)
declare i64 @wolf_date_diff_days(i64, i64)
declare i1 @wolf_date_is_past(i64)
declare i1 @wolf_date_is_future(i64)
declare ptr @wolf_date_to_iso(i64)

; --- Phase 3: Validation ---
declare i1 @wolf_is_email(ptr)
declare i1 @wolf_is_url(ptr)
declare i1 @wolf_is_phone(ptr)
declare i1 @wolf_is_uuid(ptr)
declare i1 @wolf_is_json(ptr)
declare i1 @wolf_is_ip(ptr)
declare i1 @wolf_is_alpha(ptr)
declare i1 @wolf_is_alpha_num(ptr)

; --- Phase 3: File System ---
declare i1 @wolf_file_exists(ptr)
declare ptr @wolf_file_read(ptr)
declare i1 @wolf_file_write(ptr, ptr)
declare i1 @wolf_file_append(ptr, ptr)
declare i1 @wolf_file_delete(ptr)
declare i64 @wolf_file_size(ptr)
declare ptr @wolf_file_extension(ptr)
declare ptr @wolf_file_basename(ptr)
declare ptr @wolf_file_dirname(ptr)
declare i1 @wolf_dir_exists(ptr)
declare i1 @wolf_file_copy(ptr, ptr)
declare i1 @wolf_file_move(ptr, ptr)
declare i1 @wolf_dir_create(ptr)
declare ptr @wolf_path_join(ptr, ptr)
declare ptr @wolf_scan_dir(ptr)

; --- Phase 3: Utilities ---
declare ptr @wolf_slug(ptr)
declare ptr @wolf_truncate(ptr, i64, ptr)

; --- STDLIB-08: Validation Rules Engine ---
declare ptr @wolf_validate(ptr, ptr)
declare i1 @wolf_validator_passes(ptr)
declare ptr @wolf_validator_errors(ptr)
declare ptr @wolf_validator_validated(ptr)

; --- DB-01: Query Builder ---
declare ptr @wolf_qb_create(ptr, ptr)
declare ptr @wolf_qb_with(ptr, ptr, ptr, ptr, ptr)
declare ptr @wolf_qb_where(ptr, ptr, ptr, ptr)
declare ptr @wolf_qb_order_by(ptr, ptr, ptr)
declare ptr @wolf_qb_limit(ptr, i64)
declare ptr @wolf_qb_offset(ptr, i64)
declare ptr @wolf_qb_get(ptr)
declare ptr @wolf_qb_first(ptr)
declare i64 @wolf_qb_insert(ptr, ptr)
declare i64 @wolf_qb_update(ptr, ptr)
declare i64 @wolf_qb_delete(ptr)
declare ptr @wolf_qb_paginate(ptr, i64, i64)

; --- Sessions ---
declare void @wolf_session_begin()
declare void @wolf_session_set(ptr, ptr)
declare ptr @wolf_session_get(ptr)
declare void @wolf_session_end()

; --- Define System (PHP-style constants) ---
declare void @wolf_define(ptr, ptr)
declare i1 @wolf_defined(ptr)
declare ptr @wolf_define_get(ptr)

; --- Redis ---
declare ptr @wolf_redis_connect(ptr, i64, ptr)
declare void @wolf_redis_set(ptr, ptr, i64)
declare ptr @wolf_redis_get(ptr)
declare i64 @wolf_redis_del(ptr)
declare i1 @wolf_redis_exists(ptr)
declare void @wolf_redis_hset(ptr, ptr, ptr)
declare ptr @wolf_redis_hget(ptr, ptr)
declare void @wolf_redis_close()

; --- Data Structures ---
declare ptr @wolf_array_create()
declare void @wolf_array_push(ptr, ptr)
declare ptr @wolf_array_get(ptr, i64)
declare i64 @wolf_array_length(ptr)
declare ptr @wolf_map_create()
declare void @wolf_map_set(ptr, ptr, ptr)
declare void @wolf_map_set_int(ptr, ptr, i64)
declare void @wolf_map_set_float(ptr, ptr, double)
declare void @wolf_map_set_bool(ptr, ptr, i1)
declare ptr @wolf_map_get(ptr, ptr)
declare ptr @wolf_class_create(ptr)
declare i1 @wolf_env_has(ptr)
declare ptr @wolf_val_int(i64)
declare ptr @wolf_val_float(double)
declare ptr @wolf_val_bool(i1)
declare ptr @wolf_val_array(ptr)

; --- Thread-Local Request Context ---
declare void @wolf_set_current_context(ptr, ptr)
declare ptr @wolf_get_request_body()
declare ptr @wolf_get_request_header(ptr)
declare ptr @wolf_get_request_method()
declare ptr @wolf_get_request_path()
declare ptr @wolf_input(ptr)
declare void @wolf_http_response_code(i64)
declare void @wolf_http_write_response(ptr)

; --- Phase 2: WolfScheduler ---
declare void @wolf_spawn_task(ptr)
declare void @wolf_task_wait_all()

; --- Phase 1: Concurrency (Legacy) ---
declare void @wolf_supervise_begin(i64, i64)
declare void @wolf_supervise_end()
declare void @wolf_trace_start(ptr)
declare void @wolf_trace_end(ptr)
declare void @wolf_metrics_increment(ptr)
declare void @wolf_metrics_gauge(ptr, double)
declare void @wolf_metrics_histogram(ptr, double)

; --- CLI Arguments ---
declare void @wolf_init_args(i32, ptr)
declare i64 @wolf_argc()
declare ptr @wolf_argv(i64)

; --- Sanitization ---
declare ptr @wolf_sanitize_string(ptr)
declare ptr @wolf_sanitize_email(ptr)
declare ptr @wolf_sanitize_url(ptr)
declare ptr @wolf_sanitize_int(ptr)
declare ptr @wolf_sanitize_float(ptr)

; --- HTTP Server (C FFI) ---
declare void @wolf_http_serve(i64, ptr)
declare ptr @wolf_http_req_method(i64)
declare ptr @wolf_http_req_path(i64)
declare ptr @wolf_http_req_query(i64, ptr)
declare ptr @wolf_http_req_header(i64, ptr)
declare ptr @wolf_http_req_body(i64)
declare void @wolf_http_res_header(i64, ptr, ptr)
declare void @wolf_http_res_status(i64, i64)
declare void @wolf_http_res_write(i64, ptr)

; --- HTTP Client (libcurl) ---
declare ptr @wolf_http_request(ptr, ptr, ptr, ptr)
declare ptr @wolf_http_get(ptr, ptr)
declare ptr @wolf_http_post(ptr, ptr, ptr)
declare ptr @wolf_http_put(ptr, ptr, ptr)
declare ptr @wolf_http_delete(ptr, ptr)
declare ptr @wolf_http_patch(ptr, ptr, ptr)
declare ptr @wolf_http_client_res_body(ptr)
declare ptr @wolf_http_client_res_json(ptr)
declare i64 @wolf_http_client_res_status(ptr)
declare i64 @wolf_http_client_res_ok(ptr)
declare i64 @wolf_http_client_res_failed(ptr)
declare ptr @wolf_http_client_res_header(ptr, ptr)
declare ptr @wolf_url_encode(ptr)
declare ptr @wolf_url_decode(ptr)
declare ptr @wolf_url_parse(ptr)
declare ptr @wolf_build_query(ptr)
declare ptr @wolf_dns_lookup(ptr)
declare ptr @wolf_get_client_ip()

define i1 @wolf___compiler_dispatch_controller(ptr %c.arg, ptr %m.arg, ptr %args.arg, ptr %req.arg, ptr %res.arg) {
entry:
  %c = alloca ptr
  %m = alloca ptr
  %args = alloca ptr
  %req = alloca ptr
  %res = alloca ptr
  store ptr %c.arg, ptr %c
  store ptr %m.arg, ptr %m
  store ptr %args.arg, ptr %args
  store ptr %req.arg, ptr %req
  store ptr %res.arg, ptr %res
  ret i1 0
}

define ptr @wolf___compiler_create_model(ptr %name.arg) {
entry:
  %name = alloca ptr
  store ptr %name.arg, ptr %name
  ret ptr null
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  call void @wolf_init_args(i32 %argc, ptr %argv)
  %rules1 = alloca ptr
  %data3 = alloca ptr
  %rules3 = alloca ptr
  %data5 = alloca ptr
  %data1 = alloca ptr
  %v1 = alloca ptr
  %rules2 = alloca ptr
  %v4 = alloca ptr
  %rules5 = alloca ptr
  %data2 = alloca ptr
  %v2 = alloca ptr
  %v3 = alloca ptr
  %data4 = alloca ptr
  %rules4 = alloca ptr
  %v5 = alloca ptr
  %t1 = call ptr @wolf_map_create()
  %t2 = getelementptr [6 x i8], ptr @.str.1, i64 0, i64 0
  %t3 = getelementptr [17 x i8], ptr @.str.2, i64 0, i64 0
  call void @wolf_map_set(ptr %t1, ptr %t2, ptr %t3)
  %t4 = getelementptr [4 x i8], ptr @.str.3, i64 0, i64 0
  %t5 = getelementptr [3 x i8], ptr @.str.4, i64 0, i64 0
  call void @wolf_map_set(ptr %t1, ptr %t4, ptr %t5)
  %t6 = getelementptr [5 x i8], ptr @.str.5, i64 0, i64 0
  %t7 = getelementptr [5 x i8], ptr @.str.6, i64 0, i64 0
  call void @wolf_map_set(ptr %t1, ptr %t6, ptr %t7)
  store ptr %t1, ptr %data1
  %t8 = call ptr @wolf_map_create()
  %t9 = getelementptr [6 x i8], ptr @.str.1, i64 0, i64 0
  %t10 = getelementptr [15 x i8], ptr @.str.7, i64 0, i64 0
  call void @wolf_map_set(ptr %t8, ptr %t9, ptr %t10)
  %t11 = getelementptr [4 x i8], ptr @.str.3, i64 0, i64 0
  %t12 = getelementptr [24 x i8], ptr @.str.8, i64 0, i64 0
  call void @wolf_map_set(ptr %t8, ptr %t11, ptr %t12)
  %t13 = getelementptr [5 x i8], ptr @.str.5, i64 0, i64 0
  %t14 = getelementptr [23 x i8], ptr @.str.9, i64 0, i64 0
  call void @wolf_map_set(ptr %t8, ptr %t13, ptr %t14)
  store ptr %t8, ptr %rules1
  %t15 = load ptr, ptr %data1
  %t16 = load ptr, ptr %rules1
  %t17 = call ptr @wolf_validate(ptr %t15, ptr %t16)
  %t18 = call i1 @wolf_has_error()
  br i1 %t18, label %err.true.1, label %err.false.2

err.true.1:
    ret i32 1

err.false.2:
  store ptr %t17, ptr %v1
  %t19 = load ptr, ptr %v1
  %t20 = call i1 @wolf_validator_passes(ptr %t19)
  %t21 = call i1 @wolf_has_error()
  br i1 %t21, label %err.true.3, label %err.false.4

err.true.3:
    ret i32 1

err.false.4:
  br i1 %t20, label %if.then.5, label %if.else.7
if.then.5:
  %t22 = getelementptr [6 x i8], ptr @.str.10, i64 0, i64 0
  call void @wolf_print_str(ptr %t22)
  call void @wolf_println()
  br label %if.end.6
if.else.7:
  %t23 = getelementptr [8 x i8], ptr @.str.11, i64 0, i64 0
  call void @wolf_print_str(ptr %t23)
  call void @wolf_println()
  br label %if.end.6
if.end.6:
  %t24 = call ptr @wolf_map_create()
  %t25 = getelementptr [6 x i8], ptr @.str.1, i64 0, i64 0
  %t26 = getelementptr [13 x i8], ptr @.str.12, i64 0, i64 0
  call void @wolf_map_set(ptr %t24, ptr %t25, ptr %t26)
  %t27 = getelementptr [4 x i8], ptr @.str.3, i64 0, i64 0
  %t28 = getelementptr [3 x i8], ptr @.str.4, i64 0, i64 0
  call void @wolf_map_set(ptr %t24, ptr %t27, ptr %t28)
  store ptr %t24, ptr %data2
  %t29 = call ptr @wolf_map_create()
  %t30 = getelementptr [6 x i8], ptr @.str.1, i64 0, i64 0
  %t31 = getelementptr [15 x i8], ptr @.str.7, i64 0, i64 0
  call void @wolf_map_set(ptr %t29, ptr %t30, ptr %t31)
  %t32 = getelementptr [4 x i8], ptr @.str.3, i64 0, i64 0
  %t33 = getelementptr [17 x i8], ptr @.str.13, i64 0, i64 0
  call void @wolf_map_set(ptr %t29, ptr %t32, ptr %t33)
  store ptr %t29, ptr %rules2
  %t34 = load ptr, ptr %data2
  %t35 = load ptr, ptr %rules2
  %t36 = call ptr @wolf_validate(ptr %t34, ptr %t35)
  %t37 = call i1 @wolf_has_error()
  br i1 %t37, label %err.true.8, label %err.false.9

err.true.8:
    ret i32 1

err.false.9:
  store ptr %t36, ptr %v2
  %t38 = load ptr, ptr %v2
  %t39 = call i1 @wolf_validator_passes(ptr %t38)
  %t40 = call i1 @wolf_has_error()
  br i1 %t40, label %err.true.10, label %err.false.11

err.true.10:
    ret i32 1

err.false.11:
  br i1 %t39, label %if.then.12, label %if.else.14
if.then.12:
  %t41 = getelementptr [6 x i8], ptr @.str.10, i64 0, i64 0
  call void @wolf_print_str(ptr %t41)
  call void @wolf_println()
  br label %if.end.13
if.else.14:
  %t42 = getelementptr [8 x i8], ptr @.str.11, i64 0, i64 0
  call void @wolf_print_str(ptr %t42)
  call void @wolf_println()
  br label %if.end.13
if.end.13:
  %t43 = call ptr @wolf_map_create()
  %t44 = getelementptr [4 x i8], ptr @.str.3, i64 0, i64 0
  %t45 = getelementptr [3 x i8], ptr @.str.14, i64 0, i64 0
  call void @wolf_map_set(ptr %t43, ptr %t44, ptr %t45)
  store ptr %t43, ptr %data3
  %t46 = call ptr @wolf_map_create()
  %t47 = getelementptr [4 x i8], ptr @.str.3, i64 0, i64 0
  %t48 = getelementptr [24 x i8], ptr @.str.8, i64 0, i64 0
  call void @wolf_map_set(ptr %t46, ptr %t47, ptr %t48)
  store ptr %t46, ptr %rules3
  %t49 = load ptr, ptr %data3
  %t50 = load ptr, ptr %rules3
  %t51 = call ptr @wolf_validate(ptr %t49, ptr %t50)
  %t52 = call i1 @wolf_has_error()
  br i1 %t52, label %err.true.15, label %err.false.16

err.true.15:
    ret i32 1

err.false.16:
  store ptr %t51, ptr %v3
  %t53 = load ptr, ptr %v3
  %t54 = call i1 @wolf_validator_passes(ptr %t53)
  %t55 = call i1 @wolf_has_error()
  br i1 %t55, label %err.true.17, label %err.false.18

err.true.17:
    ret i32 1

err.false.18:
  br i1 %t54, label %if.then.19, label %if.else.21
if.then.19:
  %t56 = getelementptr [6 x i8], ptr @.str.10, i64 0, i64 0
  call void @wolf_print_str(ptr %t56)
  call void @wolf_println()
  br label %if.end.20
if.else.21:
  %t57 = getelementptr [8 x i8], ptr @.str.11, i64 0, i64 0
  call void @wolf_print_str(ptr %t57)
  call void @wolf_println()
  br label %if.end.20
if.end.20:
  %t58 = call ptr @wolf_map_create()
  %t59 = getelementptr [5 x i8], ptr @.str.5, i64 0, i64 0
  %t60 = getelementptr [5 x i8], ptr @.str.6, i64 0, i64 0
  call void @wolf_map_set(ptr %t58, ptr %t59, ptr %t60)
  store ptr %t58, ptr %data4
  %t61 = call ptr @wolf_map_create()
  %t62 = getelementptr [6 x i8], ptr @.str.1, i64 0, i64 0
  %t63 = getelementptr [9 x i8], ptr @.str.15, i64 0, i64 0
  call void @wolf_map_set(ptr %t61, ptr %t62, ptr %t63)
  %t64 = getelementptr [5 x i8], ptr @.str.5, i64 0, i64 0
  %t65 = getelementptr [9 x i8], ptr @.str.15, i64 0, i64 0
  call void @wolf_map_set(ptr %t61, ptr %t64, ptr %t65)
  store ptr %t61, ptr %rules4
  %t66 = load ptr, ptr %data4
  %t67 = load ptr, ptr %rules4
  %t68 = call ptr @wolf_validate(ptr %t66, ptr %t67)
  %t69 = call i1 @wolf_has_error()
  br i1 %t69, label %err.true.22, label %err.false.23

err.true.22:
    ret i32 1

err.false.23:
  store ptr %t68, ptr %v4
  %t70 = load ptr, ptr %v4
  %t71 = call i1 @wolf_validator_passes(ptr %t70)
  %t72 = call i1 @wolf_has_error()
  br i1 %t72, label %err.true.24, label %err.false.25

err.true.24:
    ret i32 1

err.false.25:
  br i1 %t71, label %if.then.26, label %if.else.28
if.then.26:
  %t73 = getelementptr [6 x i8], ptr @.str.10, i64 0, i64 0
  call void @wolf_print_str(ptr %t73)
  call void @wolf_println()
  br label %if.end.27
if.else.28:
  %t74 = getelementptr [8 x i8], ptr @.str.11, i64 0, i64 0
  call void @wolf_print_str(ptr %t74)
  call void @wolf_println()
  br label %if.end.27
if.end.27:
  %t75 = call ptr @wolf_map_create()
  %t76 = getelementptr [5 x i8], ptr @.str.5, i64 0, i64 0
  %t77 = getelementptr [5 x i8], ptr @.str.6, i64 0, i64 0
  call void @wolf_map_set(ptr %t75, ptr %t76, ptr %t77)
  %t78 = getelementptr [4 x i8], ptr @.str.16, i64 0, i64 0
  %t79 = getelementptr [1 x i8], ptr @.str.17, i64 0, i64 0
  call void @wolf_map_set(ptr %t75, ptr %t78, ptr %t79)
  store ptr %t75, ptr %data5
  %t80 = call ptr @wolf_map_create()
  %t81 = getelementptr [5 x i8], ptr @.str.5, i64 0, i64 0
  %t82 = getelementptr [9 x i8], ptr @.str.15, i64 0, i64 0
  call void @wolf_map_set(ptr %t80, ptr %t81, ptr %t82)
  %t83 = getelementptr [4 x i8], ptr @.str.16, i64 0, i64 0
  %t84 = getelementptr [9 x i8], ptr @.str.18, i64 0, i64 0
  call void @wolf_map_set(ptr %t80, ptr %t83, ptr %t84)
  store ptr %t80, ptr %rules5
  %t85 = load ptr, ptr %data5
  %t86 = load ptr, ptr %rules5
  %t87 = call ptr @wolf_validate(ptr %t85, ptr %t86)
  %t88 = call i1 @wolf_has_error()
  br i1 %t88, label %err.true.29, label %err.false.30

err.true.29:
    ret i32 1

err.false.30:
  store ptr %t87, ptr %v5
  %t89 = load ptr, ptr %v5
  %t90 = call i1 @wolf_validator_passes(ptr %t89)
  %t91 = call i1 @wolf_has_error()
  br i1 %t91, label %err.true.31, label %err.false.32

err.true.31:
    ret i32 1

err.false.32:
  br i1 %t90, label %if.then.33, label %if.else.35
if.then.33:
  %t92 = getelementptr [6 x i8], ptr @.str.10, i64 0, i64 0
  call void @wolf_print_str(ptr %t92)
  call void @wolf_println()
  br label %if.end.34
if.else.35:
  %t93 = getelementptr [8 x i8], ptr @.str.11, i64 0, i64 0
  call void @wolf_print_str(ptr %t93)
  call void @wolf_println()
  br label %if.end.34
if.end.34:
  ret i32 0
}
