// Package emitter also contains the LLVM IR code generator.
// LLVMEmitter transforms WIR into LLVM IR text (.ll files).
// This emitter produces LLVM IR directly as text — no external
// Go dependencies required (no llir/llvm package needed).
package emitter

import (
	"fmt"
	"strings"

	"github.com/wolflang/wolf/internal/ir"
)

// LLVMEmitter generates LLVM IR text from WIR.
type LLVMEmitter struct {
	buf         strings.Builder
	stringConsts map[string]string // value → @.str.N label
	strCounter   int
	localCounter int
	labelCounter int
	indent       int
	// Track declared variables and their LLVM types
	varTypes map[string]string // varName → LLVM type ("i64", "double", "ptr", "i1")
	// Track declared external functions
	declaredExterns map[string]bool
}

// NewLLVMEmitter creates a new LLVM IR emitter.
func NewLLVMEmitter() *LLVMEmitter {
	return &LLVMEmitter{
		stringConsts:    make(map[string]string),
		varTypes:        make(map[string]string),
		declaredExterns: make(map[string]bool),
	}
}

// nextLocal returns a fresh LLVM local register name.
func (e *LLVMEmitter) nextLocal() string {
	e.localCounter++
	return fmt.Sprintf("%%t%d", e.localCounter)
}

// nextLabel returns a fresh LLVM label name.
func (e *LLVMEmitter) nextLabel(prefix string) string {
	e.labelCounter++
	return fmt.Sprintf("%s.%d", prefix, e.labelCounter)
}

// addStringConst registers a string constant and returns its global label.
func (e *LLVMEmitter) addStringConst(value string) string {
	if label, ok := e.stringConsts[value]; ok {
		return label
	}
	e.strCounter++
	label := fmt.Sprintf("@.str.%d", e.strCounter)
	e.stringConsts[value] = label
	return label
}

// llvmEscapeString escapes a string for LLVM IR string constants.
func llvmEscapeString(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		ch := s[i]
		switch ch {
		case '\\':
			b.WriteString("\\5C")
		case '"':
			b.WriteString("\\22")
		case '\n':
			b.WriteString("\\0A")
		case '\r':
			b.WriteString("\\0D")
		case '\t':
			b.WriteString("\\09")
		case '\x00':
			b.WriteString("\\00")
		default:
			if ch < 32 || ch > 126 {
				b.WriteString(fmt.Sprintf("\\%02X", ch))
			} else {
				b.WriteByte(ch)
			}
		}
	}
	return b.String()
}

// Emit generates LLVM IR text from a WIR program.
func (e *LLVMEmitter) Emit(program *ir.Program) string {
	e.buf.Reset()
	e.localCounter = 0
	e.labelCounter = 0

	// We'll collect all string constants during emission,
	// then prepend them at the top.
	var bodyBuf strings.Builder

	// Swap buffers: emit body first to collect string constants
	mainBuf := &e.buf
	e.buf = bodyBuf

	// Emit functions
	for _, fn := range program.Functions {
		e.emitFunction(fn)
		e.writeln("")
	}

	// Emit main function from InitStmts
	if len(program.InitStmts) > 0 {
		e.writeln("define i32 @main() {")
		e.writeln("entry:")
		e.indent++
		for _, stmt := range program.InitStmts {
			e.emitStmt(stmt)
		}
		e.writelnIndent("ret i32 0")
		e.indent--
		e.writeln("}")
	}

	// Now assemble: header + string constants + body
	bodyStr := e.buf.String()
	e.buf = *mainBuf
	e.buf.Reset()

	// Module header
	e.writeln("; Wolf Language — LLVM IR Output")
	e.writeln("; Generated by wolf compiler")
	e.writeln("")
	e.writeln("target triple = \"x86_64-pc-linux-gnu\"")
	e.writeln("")

	// String constants
	if len(e.stringConsts) > 0 {
		e.writeln("; --- String Constants ---")
		for value, label := range e.stringConsts {
			escaped := llvmEscapeString(value)
			byteLen := len(value) + 1 // +1 for null terminator
			e.writeln(fmt.Sprintf("%s = private unnamed_addr constant [%d x i8] c\"%s\\00\"", label, byteLen, escaped))
		}
		e.writeln("")
	}

	// External function declarations
	e.writeln("; --- External Runtime Functions ---")
	e.writeln("declare void @wolf_print_str(ptr)")
	e.writeln("declare void @wolf_print_int(i64)")
	e.writeln("declare void @wolf_print_float(double)")
	e.writeln("declare void @wolf_print_bool(i1)")
	e.writeln("declare void @wolf_print_nil()")
	e.writeln("declare void @wolf_println()")
	e.writeln("declare ptr @wolf_string_concat(ptr, ptr)")
	e.writeln("declare i64 @wolf_string_length(ptr)")
	e.writeln("declare ptr @wolf_string_upper(ptr)")
	e.writeln("declare ptr @wolf_string_lower(ptr)")
	e.writeln("declare ptr @wolf_string_trim(ptr)")
	e.writeln("declare ptr @wolf_int_to_string(i64)")
	e.writeln("declare ptr @wolf_float_to_string(double)")
	e.writeln("declare ptr @wolf_bool_to_string(i1)")
	e.writeln("")

	// Body
	e.buf.WriteString(bodyStr)

	return e.buf.String()
}

// ========== Function Emission ==========

func (e *LLVMEmitter) emitFunction(fn *ir.Function) {
	// Build param list
	params := make([]string, len(fn.Params))
	for i, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		params[i] = fmt.Sprintf("%s %%%s", llType, p.Name)
	}

	retType := "void"
	if len(fn.ReturnTypes) > 0 {
		retType = e.wolfTypeToLLVM(fn.ReturnTypes[0])
	}

	e.writeln(fmt.Sprintf("define %s @%s(%s) {", retType, fn.Name, strings.Join(params, ", ")))
	e.writeln("entry:")
	e.indent++

	// Allocate stack space for params
	for _, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		e.writelnIndent(fmt.Sprintf("%%%s.addr = alloca %s", p.Name, llType))
		e.writelnIndent(fmt.Sprintf("store %s %%%s, ptr %%%s.addr", llType, p.Name, p.Name))
	}

	for _, stmt := range fn.Body {
		e.emitStmt(stmt)
	}

	// Add implicit return if missing
	if retType == "void" && !e.lastStmtIsReturn(fn.Body) {
		e.writelnIndent("ret void")
	}

	e.indent--
	e.writeln("}")
}

func (e *LLVMEmitter) lastStmtIsReturn(stmts []ir.Stmt) bool {
	if len(stmts) == 0 {
		return false
	}
	_, ok := stmts[len(stmts)-1].(*ir.ReturnStmt)
	return ok
}

// ========== Statement Emission ==========

func (e *LLVMEmitter) emitStmt(stmt ir.Stmt) {
	switch s := stmt.(type) {
	case *ir.VarDeclStmt:
		e.emitVarDecl(s)
	case *ir.AssignStmt:
		e.emitAssign(s)
	case *ir.ExprStmt:
		e.emitExprStmt(s)
	case *ir.ReturnStmt:
		e.emitReturn(s)
	case *ir.IfStmt:
		e.emitIf(s)
	case *ir.ForStmt:
		e.emitFor(s)
	case *ir.RangeStmt:
		e.emitRange(s)
	case *ir.SwitchStmt:
		e.emitSwitch(s)
	case *ir.BlockStmt:
		for _, inner := range s.Stmts {
			e.emitStmt(inner)
		}
	case *ir.RawStmt:
		e.writelnIndent(fmt.Sprintf("; raw: %s", s.Code))
	default:
		e.writelnIndent(fmt.Sprintf("; TODO: unhandled statement type %T", stmt))
	}
}

func (e *LLVMEmitter) emitVarDecl(s *ir.VarDeclStmt) {
	llType := e.wolfTypeToLLVM(s.Type)
	if llType == "" || llType == "ptr" {
		// Try to infer type from value
		if s.Value != nil {
			llType = e.inferExprType(s.Value)
		}
		if llType == "" {
			llType = "ptr"
		}
	}
	// Allocate on stack
	e.writelnIndent(fmt.Sprintf("%%%s = alloca %s", s.Name, llType))
	e.varTypes[s.Name] = llType

	if s.Value != nil {
		val := e.emitExpr(s.Value, llType)
		e.writelnIndent(fmt.Sprintf("store %s %s, ptr %%%s", llType, val, s.Name))
	}
}

func (e *LLVMEmitter) emitAssign(s *ir.AssignStmt) {
	switch target := s.Target.(type) {
	case *ir.Ident:
		// Infer type from value expression
		llType := e.inferExprType(s.Value)
		if llType == "" {
			llType = "ptr"
		}

		// := means first declaration — need alloca
		if s.Op == ":=" {
			e.writelnIndent(fmt.Sprintf("%%%s = alloca %s", target.Name, llType))
			e.varTypes[target.Name] = llType
		}

		// Get stored type (may differ for reassignment)
		storedType, ok := e.varTypes[target.Name]
		if !ok {
			storedType = llType
		}

		val := e.emitExpr(s.Value, storedType)
		e.writelnIndent(fmt.Sprintf("store %s %s, ptr %%%s", storedType, val, target.Name))
	default:
		e.writelnIndent(fmt.Sprintf("; TODO: complex assignment target %T", s.Target))
	}
}

// inferExprType returns the LLVM type of the given expression.
func (e *LLVMEmitter) inferExprType(expr ir.Expr) string {
	switch ex := expr.(type) {
	case *ir.IntLit:
		return "i64"
	case *ir.FloatLit:
		return "double"
	case *ir.BoolLit:
		return "i1"
	case *ir.StringLit:
		return "ptr"
	case *ir.NilLit:
		return "ptr"
	case *ir.BinaryExpr:
		// Arithmetic ops on ints → i64, comparisons → i1
		switch ex.Op {
		case "==", "!=", "<", ">", "<=", ">=", "&&", "||":
			return "i1"
		default:
			// Check if either side is float
			if e.inferExprType(ex.Left) == "double" || e.inferExprType(ex.Right) == "double" {
				return "double"
			}
			return "i64"
		}
	case *ir.UnaryExpr:
		if ex.Op == "!" {
			return "i1"
		}
		return e.inferExprType(ex.Operand)
	case *ir.FmtSprintf:
		return "ptr"
	case *ir.StringConcat:
		return "ptr"
	case *ir.CallExpr:
		return "ptr" // default for function calls
	case *ir.Ident:
		if t, ok := e.varTypes[ex.Name]; ok {
			return t
		}
		return "ptr"
	default:
		return "ptr"
	}
}

func (e *LLVMEmitter) emitExprStmt(s *ir.ExprStmt) {
	switch expr := s.Expr.(type) {
	case *ir.CallExpr:
		e.emitCallExpr(expr)
	case *ir.MethodCallExpr:
		e.emitMethodCall(expr)
	default:
		e.emitExpr(s.Expr, "")
	}
}

func (e *LLVMEmitter) emitReturn(s *ir.ReturnStmt) {
	if len(s.Values) == 0 {
		e.writelnIndent("ret void")
	} else {
		val := e.emitExpr(s.Values[0], "")
		e.writelnIndent(fmt.Sprintf("ret i64 %s", val))
	}
}

func (e *LLVMEmitter) emitIf(s *ir.IfStmt) {
	condVal := e.emitExpr(s.Condition, "i1")
	thenLabel := e.nextLabel("if.then")
	elseLabel := e.nextLabel("if.else")
	endLabel := e.nextLabel("if.end")

	if s.ElseBody != nil || len(s.ElseIfs) > 0 {
		e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", condVal, thenLabel, elseLabel))
	} else {
		e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", condVal, thenLabel, endLabel))
	}

	// Then block
	e.writeln(fmt.Sprintf("%s:", thenLabel))
	for _, stmt := range s.Body {
		e.emitStmt(stmt)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))

	// Else block
	if s.ElseBody != nil || len(s.ElseIfs) > 0 {
		e.writeln(fmt.Sprintf("%s:", elseLabel))
		if s.ElseBody != nil {
			for _, stmt := range s.ElseBody {
				e.emitStmt(stmt)
			}
		}
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
	}

	// End
	e.writeln(fmt.Sprintf("%s:", endLabel))
}

func (e *LLVMEmitter) emitFor(s *ir.ForStmt) {
	condLabel := e.nextLabel("for.cond")
	bodyLabel := e.nextLabel("for.body")
	updateLabel := e.nextLabel("for.update")
	endLabel := e.nextLabel("for.end")

	// Init
	if s.Init != nil {
		e.emitStmt(s.Init)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))

	// Condition
	e.writeln(fmt.Sprintf("%s:", condLabel))
	if s.Cond != nil {
		condVal := e.emitExpr(s.Cond, "i1")
		e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", condVal, bodyLabel, endLabel))
	} else {
		e.writelnIndent(fmt.Sprintf("br label %%%s", bodyLabel))
	}

	// Body
	e.writeln(fmt.Sprintf("%s:", bodyLabel))
	for _, stmt := range s.Body {
		e.emitStmt(stmt)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", updateLabel))

	// Update
	e.writeln(fmt.Sprintf("%s:", updateLabel))
	if s.Update != nil {
		e.emitStmt(s.Update)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))

	// End
	e.writeln(fmt.Sprintf("%s:", endLabel))
}

func (e *LLVMEmitter) emitRange(s *ir.RangeStmt) {
	e.writelnIndent(fmt.Sprintf("; TODO: range loop over %s, %s", s.Key, s.Value))
}

func (e *LLVMEmitter) emitSwitch(s *ir.SwitchStmt) {
	e.writelnIndent("; TODO: switch statement")
}

// ========== Expression Emission ==========

// emitExpr emits LLVM IR for an expression and returns the register/value name.
func (e *LLVMEmitter) emitExpr(expr ir.Expr, expectedType string) string {
	switch ex := expr.(type) {
	case *ir.IntLit:
		return ex.Value
	case *ir.FloatLit:
		return ex.Value
	case *ir.BoolLit:
		if ex.Value {
			return "1"
		}
		return "0"
	case *ir.NilLit:
		return "null"
	case *ir.StringLit:
		label := e.addStringConst(ex.Value)
		reg := e.nextLocal()
		byteLen := len(ex.Value) + 1
		e.writelnIndent(fmt.Sprintf("%s = getelementptr [%d x i8], ptr %s, i64 0, i64 0", reg, byteLen, label))
		return reg
	case *ir.Ident:
		loadType := "ptr"
		if t, ok := e.varTypes[ex.Name]; ok {
			loadType = t
		}
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = load %s, ptr %%%s", reg, loadType, ex.Name))
		return reg
	case *ir.BinaryExpr:
		return e.emitBinaryExpr(ex, expectedType)
	case *ir.UnaryExpr:
		return e.emitUnaryExpr(ex)
	case *ir.CallExpr:
		return e.emitCallExpr(ex)
	case *ir.FmtSprintf:
		return e.emitFmtSprintf(ex)
	case *ir.StringConcat:
		return e.emitStringConcat(ex)
	case *ir.PostfixExpr:
		return e.emitPostfix(ex)
	default:
		e.writelnIndent(fmt.Sprintf("; TODO: unhandled expr type %T", expr))
		return "0"
	}
}

func (e *LLVMEmitter) emitBinaryExpr(ex *ir.BinaryExpr, expectedType string) string {
	left := e.emitExpr(ex.Left, "i64")
	right := e.emitExpr(ex.Right, "i64")
	reg := e.nextLocal()

	switch ex.Op {
	case "+":
		e.writelnIndent(fmt.Sprintf("%s = add i64 %s, %s", reg, left, right))
	case "-":
		e.writelnIndent(fmt.Sprintf("%s = sub i64 %s, %s", reg, left, right))
	case "*":
		e.writelnIndent(fmt.Sprintf("%s = mul i64 %s, %s", reg, left, right))
	case "/":
		e.writelnIndent(fmt.Sprintf("%s = sdiv i64 %s, %s", reg, left, right))
	case "%":
		e.writelnIndent(fmt.Sprintf("%s = srem i64 %s, %s", reg, left, right))
	case "==":
		e.writelnIndent(fmt.Sprintf("%s = icmp eq i64 %s, %s", reg, left, right))
	case "!=":
		e.writelnIndent(fmt.Sprintf("%s = icmp ne i64 %s, %s", reg, left, right))
	case "<":
		e.writelnIndent(fmt.Sprintf("%s = icmp slt i64 %s, %s", reg, left, right))
	case ">":
		e.writelnIndent(fmt.Sprintf("%s = icmp sgt i64 %s, %s", reg, left, right))
	case "<=":
		e.writelnIndent(fmt.Sprintf("%s = icmp sle i64 %s, %s", reg, left, right))
	case ">=":
		e.writelnIndent(fmt.Sprintf("%s = icmp sge i64 %s, %s", reg, left, right))
	case "&&":
		e.writelnIndent(fmt.Sprintf("%s = and i1 %s, %s", reg, left, right))
	case "||":
		e.writelnIndent(fmt.Sprintf("%s = or i1 %s, %s", reg, left, right))
	default:
		e.writelnIndent(fmt.Sprintf("; unknown binary op: %s", ex.Op))
		return "0"
	}
	return reg
}

func (e *LLVMEmitter) emitUnaryExpr(ex *ir.UnaryExpr) string {
	operand := e.emitExpr(ex.Operand, "")
	reg := e.nextLocal()

	switch ex.Op {
	case "!":
		e.writelnIndent(fmt.Sprintf("%s = xor i1 %s, 1", reg, operand))
	case "-":
		e.writelnIndent(fmt.Sprintf("%s = sub i64 0, %s", reg, operand))
	default:
		e.writelnIndent(fmt.Sprintf("; unknown unary op: %s", ex.Op))
		return "0"
	}
	return reg
}

func (e *LLVMEmitter) emitCallExpr(call *ir.CallExpr) string {
	// Check for built-in print
	if ident, ok := call.Callee.(*ir.Ident); ok {
		switch ident.Name {
		case "fmt_Println", "fmt.Println", "wolf_print", "print":
			return e.emitPrintCall(call)
		}
	}

	// Generic function call
	calleeName := ""
	if ident, ok := call.Callee.(*ir.Ident); ok {
		calleeName = ident.Name
	}

	args := make([]string, len(call.Args))
	for i, arg := range call.Args {
		val := e.emitExpr(arg, "")
		args[i] = fmt.Sprintf("ptr %s", val)
	}

	reg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @%s(%s)", reg, calleeName, strings.Join(args, ", ")))
	return reg
}

func (e *LLVMEmitter) emitPrintCall(call *ir.CallExpr) string {
	for i, arg := range call.Args {
		// Add space between arguments (like Go's fmt.Println)
		if i > 0 {
			spaceLabel := e.addStringConst(" ")
			spaceReg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = getelementptr [2 x i8], ptr %s, i64 0, i64 0", spaceReg, spaceLabel))
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", spaceReg))
		}

		switch ex := arg.(type) {
		case *ir.StringLit:
			val := e.emitExpr(arg, "ptr")
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		case *ir.IntLit:
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_int(i64 %s)", ex.Value))
		case *ir.FloatLit:
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_float(double %s)", ex.Value))
		case *ir.BoolLit:
			val := "0"
			if ex.Value {
				val = "1"
			}
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_bool(i1 %s)", val))
		case *ir.NilLit:
			e.writelnIndent("call void @wolf_print_nil()")
		case *ir.FmtSprintf:
			val := e.emitFmtSprintf(ex)
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		case *ir.BinaryExpr:
			val := e.emitBinaryExpr(ex, "i64")
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_int(i64 %s)", val))
		case *ir.StringConcat:
			val := e.emitStringConcat(ex)
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		default:
			val := e.emitExpr(arg, "")
			// Default: try to print as string
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		}
	}

	// Newline at end
	e.writelnIndent("call void @wolf_println()")
	return "0"
}

func (e *LLVMEmitter) emitFmtSprintf(ex *ir.FmtSprintf) string {
	// For string interpolation: build the result by concatenating parts
	// The FmtSprintf has a Go-style format string and args.
	// We'll decompose it into concat calls.

	// Simple approach: emit each arg as a string, then concat them all
	parts := make([]string, 0)

	// Split the format string by %v and emit literal parts + args
	fmtStr := ex.Format
	argIdx := 0
	lastIdx := 0

	for i := 0; i < len(fmtStr)-1; i++ {
		if fmtStr[i] == '%' && fmtStr[i+1] == 'v' {
			// Emit literal part before %v
			if i > lastIdx {
				literal := fmtStr[lastIdx:i]
				val := e.emitExpr(&ir.StringLit{Value: literal}, "ptr")
				parts = append(parts, val)
			}
			// Emit the arg converted to string
			if argIdx < len(ex.Args) {
				argVal := e.emitArgAsString(ex.Args[argIdx])
				parts = append(parts, argVal)
				argIdx++
			}
			lastIdx = i + 2
			i++ // skip 'v'
		}
	}
	// Emit trailing literal
	if lastIdx < len(fmtStr) {
		literal := fmtStr[lastIdx:]
		val := e.emitExpr(&ir.StringLit{Value: literal}, "ptr")
		parts = append(parts, val)
	}

	// Concatenate all parts
	if len(parts) == 0 {
		return e.emitExpr(&ir.StringLit{Value: ""}, "ptr")
	}
	result := parts[0]
	for i := 1; i < len(parts); i++ {
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_string_concat(ptr %s, ptr %s)", reg, result, parts[i]))
		result = reg
	}
	return result
}

func (e *LLVMEmitter) emitArgAsString(arg ir.Expr) string {
	switch ex := arg.(type) {
	case *ir.StringLit:
		return e.emitExpr(ex, "ptr")
	case *ir.IntLit:
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_int_to_string(i64 %s)", reg, ex.Value))
		return reg
	case *ir.FloatLit:
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_float_to_string(double %s)", reg, ex.Value))
		return reg
	case *ir.BoolLit:
		val := "0"
		if ex.Value {
			val = "1"
		}
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_bool_to_string(i1 %s)", reg, val))
		return reg
	default:
		// Load as ptr and assume it's a string
		val := e.emitExpr(arg, "ptr")
		return val
	}
}

func (e *LLVMEmitter) emitStringConcat(ex *ir.StringConcat) string {
	left := e.emitExpr(ex.Left, "ptr")
	right := e.emitExpr(ex.Right, "ptr")
	reg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_string_concat(ptr %s, ptr %s)", reg, left, right))
	return reg
}

func (e *LLVMEmitter) emitPostfix(ex *ir.PostfixExpr) string {
	e.writelnIndent(fmt.Sprintf("; TODO: postfix %s", ex.Op))
	return "0"
}

func (e *LLVMEmitter) emitMethodCall(mc *ir.MethodCallExpr) string {
	e.writelnIndent(fmt.Sprintf("; TODO: method call .%s()", mc.Method))
	return "0"
}

// ========== Type Mapping ==========

func (e *LLVMEmitter) wolfTypeToLLVM(wolfType string) string {
	switch wolfType {
	case "int", "int64", "i64":
		return "i64"
	case "float", "float64", "double":
		return "double"
	case "bool", "i1":
		return "i1"
	case "string", "ptr", "":
		return "ptr"
	case "void":
		return "void"
	default:
		return "ptr" // Default to pointer for complex types
	}
}

// ========== Output Helpers ==========

func (e *LLVMEmitter) writeln(s string) {
	e.buf.WriteString(s)
	e.buf.WriteByte('\n')
}

func (e *LLVMEmitter) writelnIndent(s string) {
	for i := 0; i < e.indent; i++ {
		e.buf.WriteString("  ")
	}
	e.buf.WriteString(s)
	e.buf.WriteByte('\n')
}
