// Package emitter also contains the LLVM IR code generator.
// LLVMEmitter transforms WIR into LLVM IR text (.ll files).
// This emitter produces LLVM IR directly as text — no external
// Go dependencies required (no llir/llvm package needed).
package emitter

import (
	"fmt"
	"strings"

	"github.com/wolflang/wolf/internal/ir"
)

// LLVMEmitter generates LLVM IR text from WIR.
type LLVMEmitter struct {
	buf          strings.Builder
	stringConsts map[string]string // value → @.str.N label
	strCounter   int
	localCounter int
	labelCounter int
	indent       int
	// Track declared variables and their LLVM types
	varTypes map[string]string // varName → LLVM type ("i64", "double", "ptr", "i1")
	// Track user-defined function signatures
	funcSigs map[string]*ir.Function
	// Track declared external functions
	declaredExterns map[string]bool
}

// NewLLVMEmitter creates a new LLVM IR emitter.
func NewLLVMEmitter() *LLVMEmitter {
	return &LLVMEmitter{
		stringConsts:    make(map[string]string),
		varTypes:        make(map[string]string),
		funcSigs:        make(map[string]*ir.Function),
		declaredExterns: make(map[string]bool),
	}
}

// nextLocal returns a fresh LLVM local register name.
func (e *LLVMEmitter) nextLocal() string {
	e.localCounter++
	return fmt.Sprintf("%%t%d", e.localCounter)
}

// nextLabel returns a fresh LLVM label name.
func (e *LLVMEmitter) nextLabel(prefix string) string {
	e.labelCounter++
	return fmt.Sprintf("%s.%d", prefix, e.labelCounter)
}

// addStringConst registers a string constant and returns its global label.
func (e *LLVMEmitter) addStringConst(value string) string {
	if label, ok := e.stringConsts[value]; ok {
		return label
	}
	e.strCounter++
	label := fmt.Sprintf("@.str.%d", e.strCounter)
	e.stringConsts[value] = label
	return label
}

// llvmEscapeString escapes a string for LLVM IR string constants.
func llvmEscapeString(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		ch := s[i]
		switch ch {
		case '\\':
			b.WriteString("\\5C")
		case '"':
			b.WriteString("\\22")
		case '\n':
			b.WriteString("\\0A")
		case '\r':
			b.WriteString("\\0D")
		case '\t':
			b.WriteString("\\09")
		case '\x00':
			b.WriteString("\\00")
		default:
			if ch < 32 || ch > 126 {
				b.WriteString(fmt.Sprintf("\\%02X", ch))
			} else {
				b.WriteByte(ch)
			}
		}
	}
	return b.String()
}

// Emit generates LLVM IR text from a WIR program.
func (e *LLVMEmitter) Emit(program *ir.Program) string {
	e.buf.Reset()
	e.localCounter = 0
	e.labelCounter = 0

	// We'll collect all string constants during emission,
	// then prepend them at the top.
	var bodyBuf strings.Builder

	// Swap buffers: emit body first to collect string constants
	mainBuf := &e.buf
	e.buf = bodyBuf

	// Emit functions and track their signatures
	for _, fn := range program.Functions {
		e.funcSigs[fn.Name] = fn
		e.emitFunction(fn)
		e.writeln("")
	}

	// Emit classes
	for _, cls := range program.Classes {
		if cls.Constructor != nil {
			cls.Constructor.ReturnTypes = []string{"ptr"}
			e.funcSigs[cls.Constructor.Name] = cls.Constructor
			e.emitConstructor(cls.Constructor, cls.Name)
			e.writeln("")
		}
		for _, method := range cls.Methods {
			method.Params = append([]*ir.Param{{Name: "this", Type: "ptr"}}, method.Params...)
			method.Name = fmt.Sprintf("%s_%s", cls.Name, method.Name)
			e.funcSigs[method.Name] = method
			e.emitFunction(method)
			e.writeln("")
		}
	}

	// Emit main function from InitStmts
	if len(program.InitStmts) > 0 {
		e.writeln("define i32 @main() {")
		e.writeln("entry:")
		e.indent++
		for _, stmt := range program.InitStmts {
			e.emitStmt(stmt)
		}
		e.writelnIndent("ret i32 0")
		e.indent--
		e.writeln("}")
	}

	// Now assemble: header + string constants + body
	bodyStr := e.buf.String()
	e.buf = *mainBuf
	e.buf.Reset()

	// Module header
	e.writeln("; Wolf Language — LLVM IR Output")
	e.writeln("; Generated by wolf compiler")
	e.writeln("")
	e.writeln("target triple = \"x86_64-pc-linux-gnu\"")
	e.writeln("")

	// String constants
	if len(e.stringConsts) > 0 {
		e.writeln("; --- String Constants ---")
		for value, label := range e.stringConsts {
			escaped := llvmEscapeString(value)
			byteLen := len(value) + 1 // +1 for null terminator
			e.writeln(fmt.Sprintf("%s = private unnamed_addr constant [%d x i8] c\"%s\\00\"", label, byteLen, escaped))
		}
		e.writeln("")
	}

	// External function declarations
	e.writeln("; --- External Runtime Functions ---")
	e.writeln("declare void @wolf_print_str(ptr)")
	e.writeln("declare void @wolf_print_int(i64)")
	e.writeln("declare void @wolf_print_float(double)")
	e.writeln("declare void @wolf_print_bool(i1)")
	e.writeln("declare void @wolf_print_nil()")
	e.writeln("declare void @wolf_println()")
	e.writeln("declare ptr @wolf_string_concat(ptr, ptr)")
	e.writeln("declare i64 @wolf_string_length(ptr)")
	e.writeln("declare ptr @wolf_string_upper(ptr)")
	e.writeln("declare ptr @wolf_string_lower(ptr)")
	e.writeln("declare ptr @wolf_string_trim(ptr)")
	e.writeln("declare ptr @wolf_int_to_string(i64)")
	e.writeln("declare ptr @wolf_float_to_string(double)")
	e.writeln("declare ptr @wolf_bool_to_string(i1)")
	e.writeln("")

	e.writeln("; --- Math ---")
	e.writeln("declare double @wolf_math_abs(double)")
	e.writeln("declare double @wolf_math_ceil(double)")
	e.writeln("declare double @wolf_math_floor(double)")
	e.writeln("declare double @wolf_math_max(double, double)")
	e.writeln("declare double @wolf_math_min(double, double)")
	e.writeln("declare i64 @wolf_math_random(i64, i64)")
	e.writeln("declare double @wolf_math_sin(double)")
	e.writeln("declare double @wolf_math_cos(double)")
	e.writeln("declare double @wolf_math_tan(double)")
	e.writeln("declare double @wolf_math_asin(double)")
	e.writeln("declare double @wolf_math_acos(double)")
	e.writeln("declare double @wolf_math_atan(double)")
	e.writeln("declare double @wolf_math_atan2(double, double)")
	e.writeln("declare double @wolf_math_sqrt(double)")
	e.writeln("declare double @wolf_math_pow(double, double)")
	e.writeln("declare double @wolf_math_log(double)")
	e.writeln("declare double @wolf_math_log10(double)")
	e.writeln("declare double @wolf_math_exp(double)")
	e.writeln("declare double @wolf_math_round(double)")
	e.writeln("declare double @wolf_math_fmod(double, double)")
	e.writeln("declare double @wolf_math_pi()")
	e.writeln("declare ptr @wolf_number_format(double, i64, ptr, ptr)")
	e.writeln("")

	e.writeln("; --- Stdlib Strings & JSON ---")
	e.writeln("declare i1 @wolf_strings_contains(ptr, ptr)")
	e.writeln("declare ptr @wolf_strings_upper(ptr)")
	e.writeln("declare ptr @wolf_strings_split(ptr, ptr)")
	e.writeln("declare ptr @wolf_strings_join(ptr, ptr)")
	e.writeln("declare ptr @wolf_json_encode(ptr)")
	e.writeln("")

	e.writeln("; --- Output & Display ---")
	e.writeln("declare void @wolf_say(ptr)")
	e.writeln("declare void @wolf_show(ptr)")
	e.writeln("declare void @wolf_inspect(ptr)")
	e.writeln("")

	e.writeln("; --- Time & System ---")
	e.writeln("declare i64 @wolf_time_now()")
	e.writeln("declare ptr @wolf_time_date(ptr, i64)")
	e.writeln("declare i64 @wolf_time_strtotime(ptr)")
	e.writeln("declare void @wolf_system_sleep(i64)")
	e.writeln("declare void @wolf_system_exit(i64)")
	e.writeln("declare void @wolf_system_die(ptr)")
	e.writeln("declare ptr @wolf_env_get(ptr, ptr)")
	e.writeln("")

	e.writeln("; --- Sessions ---")
	e.writeln("declare void @wolf_session_begin()")
	e.writeln("declare void @wolf_session_set(ptr, ptr)")
	e.writeln("declare ptr @wolf_session_get(ptr)")
	e.writeln("declare void @wolf_session_end()")
	e.writeln("")

	e.writeln("; --- Define System (PHP-style constants) ---")
	e.writeln("declare void @wolf_define(ptr, ptr)")
	e.writeln("declare i1 @wolf_defined(ptr)")
	e.writeln("declare ptr @wolf_define_get(ptr)")
	e.writeln("")

	e.writeln("; --- Redis ---")
	e.writeln("declare ptr @wolf_redis_connect(ptr, i64, ptr)")
	e.writeln("declare void @wolf_redis_set(ptr, ptr, ptr, i64)")
	e.writeln("declare ptr @wolf_redis_get(ptr, ptr)")
	e.writeln("declare i64 @wolf_redis_del(ptr, ptr)")
	e.writeln("declare i1 @wolf_redis_exists(ptr, ptr)")
	e.writeln("declare void @wolf_redis_hset(ptr, ptr, ptr, ptr)")
	e.writeln("declare ptr @wolf_redis_hget(ptr, ptr, ptr)")
	e.writeln("declare void @wolf_redis_close(ptr)")
	e.writeln("")

	e.writeln("; --- Data Structures ---")
	e.writeln("declare ptr @wolf_array_create()")
	e.writeln("declare void @wolf_array_push(ptr, ptr)")
	e.writeln("declare ptr @wolf_array_get(ptr, i64)")
	e.writeln("declare i64 @wolf_array_length(ptr)")
	e.writeln("declare ptr @wolf_map_create()")
	e.writeln("declare void @wolf_map_set(ptr, ptr, ptr)")
	e.writeln("declare ptr @wolf_map_get(ptr, ptr)")
	e.writeln("declare ptr @wolf_class_create(ptr)")
	e.writeln("declare i1 @wolf_env_has(ptr)")
	e.writeln("")

	e.writeln("; --- HTTP Server (C FFI) ---")
	e.writeln("declare void @wolf_http_serve(i64, ptr)")
	e.writeln("declare ptr @wolf_http_req_method(i64)")
	e.writeln("declare ptr @wolf_http_req_path(i64)")
	e.writeln("declare ptr @wolf_http_req_query(i64, ptr)")
	e.writeln("declare ptr @wolf_http_req_header(i64, ptr)")
	e.writeln("declare ptr @wolf_http_req_body(i64)")
	e.writeln("declare void @wolf_http_res_header(i64, ptr, ptr)")
	e.writeln("declare void @wolf_http_res_status(i64, i64)")
	e.writeln("declare void @wolf_http_res_write(i64, ptr)")
	e.writeln("")

	// Body
	e.buf.WriteString(bodyStr)

	return e.buf.String()
}

// ========== Function Emission ==========

func (e *LLVMEmitter) emitFunction(fn *ir.Function) {
	// Build param list
	params := make([]string, len(fn.Params))
	for i, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		params[i] = fmt.Sprintf("%s %%%s.arg", llType, p.Name)
	}

	retType := "void"
	if len(fn.ReturnTypes) > 0 {
		retType = e.wolfTypeToLLVM(fn.ReturnTypes[0])
	}

	e.writeln(fmt.Sprintf("define %s @%s(%s) {", retType, fn.Name, strings.Join(params, ", ")))
	e.writeln("entry:")
	e.indent++

	// Allocate stack space for params and map their types
	for _, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		e.writelnIndent(fmt.Sprintf("%%%s = alloca %s", p.Name, llType))
		e.writelnIndent(fmt.Sprintf("store %s %%%s.arg, ptr %%%s", llType, p.Name, p.Name))
		e.varTypes[p.Name] = llType
	}

	for _, stmt := range fn.Body {
		e.emitStmt(stmt)
	}

	// Add implicit return if missing
	if retType == "void" && !e.lastStmtIsReturn(fn.Body) {
		e.writelnIndent("ret void")
	}

	e.indent--
	e.writeln("}")
}

func (e *LLVMEmitter) emitConstructor(fn *ir.Function, className string) {
	params := make([]string, len(fn.Params))
	for i, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		params[i] = fmt.Sprintf("%s %%%s.arg", llType, p.Name)
	}

	e.writeln(fmt.Sprintf("define ptr @%s(%s) {", fn.Name, strings.Join(params, ", ")))
	e.writeln("entry:")
	e.indent++

	for _, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		e.writelnIndent(fmt.Sprintf("%%%s = alloca %s", p.Name, llType))
		e.writelnIndent(fmt.Sprintf("store %s %%%s.arg, ptr %%%s", llType, p.Name, p.Name))
		e.varTypes[p.Name] = llType
	}

	clsLabel := e.addStringConst(className)
	clsLen := len(className) + 1
	e.writelnIndent(fmt.Sprintf("%%%s.name_var = getelementptr [%d x i8], ptr %s, i64 0, i64 0", className, clsLen, clsLabel))
	thisReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_class_create(ptr %%%s.name_var)", thisReg, className))
	e.writelnIndent("%this = alloca ptr")
	e.writelnIndent(fmt.Sprintf("store ptr %s, ptr %%this", thisReg))
	e.varTypes["this"] = "ptr"

	for _, stmt := range fn.Body {
		e.emitStmt(stmt)
	}

	retReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = load ptr, ptr %%this", retReg))
	e.writelnIndent(fmt.Sprintf("ret ptr %s", retReg))

	e.indent--
	e.writeln("}")
}

func (e *LLVMEmitter) lastStmtIsReturn(stmts []ir.Stmt) bool {
	if len(stmts) == 0 {
		return false
	}
	_, ok := stmts[len(stmts)-1].(*ir.ReturnStmt)
	return ok
}

// ========== Statement Emission ==========

func (e *LLVMEmitter) emitStmt(stmt ir.Stmt) {
	switch s := stmt.(type) {
	case *ir.VarDeclStmt:
		e.emitVarDecl(s)
	case *ir.AssignStmt:
		e.emitAssign(s)
	case *ir.ExprStmt:
		e.emitExprStmt(s)
	case *ir.ReturnStmt:
		e.emitReturn(s)
	case *ir.IfStmt:
		e.emitIf(s)
	case *ir.ForStmt:
		e.emitFor(s)
	case *ir.RangeStmt:
		e.emitRange(s)
	case *ir.SwitchStmt:
		e.emitSwitch(s)
	case *ir.BlockStmt:
		for _, inner := range s.Stmts {
			e.emitStmt(inner)
		}
	case *ir.RawStmt:
		e.writelnIndent(fmt.Sprintf("; raw: %s", s.Code))
	default:
		e.writelnIndent(fmt.Sprintf("; TODO: unhandled statement type %T", stmt))
	}
}

func (e *LLVMEmitter) emitVarDecl(s *ir.VarDeclStmt) {
	llType := e.wolfTypeToLLVM(s.Type)
	if llType == "" || llType == "ptr" {
		// Try to infer type from value
		if s.Value != nil {
			llType = e.inferExprType(s.Value)
		}
		if llType == "" {
			llType = "ptr"
		}
	}
	// Allocate on stack
	e.writelnIndent(fmt.Sprintf("%%%s = alloca %s", s.Name, llType))
	e.varTypes[s.Name] = llType

	if s.Value != nil {
		val := e.emitExpr(s.Value, llType)
		e.writelnIndent(fmt.Sprintf("store %s %s, ptr %%%s", llType, val, s.Name))
	}
}

func (e *LLVMEmitter) emitAssign(s *ir.AssignStmt) {
	switch target := s.Target.(type) {
	case *ir.Ident:
		// Infer type from value expression
		llType := e.inferExprType(s.Value)
		if llType == "" {
			llType = "ptr"
		}

		// := means first declaration — need alloca
		if s.Op == ":=" {
			e.writelnIndent(fmt.Sprintf("%%%s = alloca %s", target.Name, llType))
			e.varTypes[target.Name] = llType
		}

		// Get stored type (may differ for reassignment)
		storedType, ok := e.varTypes[target.Name]
		if !ok {
			storedType = llType
		}

		val := e.emitExpr(s.Value, storedType)
		e.writelnIndent(fmt.Sprintf("store %s %s, ptr %%%s", storedType, val, target.Name))
	case *ir.FieldAccess:
		objVal := e.emitExpr(target.Object, "ptr")
		valVal := e.emitArgAsString(s.Value)
		keyLabel := e.addStringConst(target.Field)
		keyReg := e.nextLocal()
		byteLen := len(target.Field) + 1
		e.writelnIndent(fmt.Sprintf("%s = getelementptr [%d x i8], ptr %s, i64 0, i64 0", keyReg, byteLen, keyLabel))
		e.writelnIndent(fmt.Sprintf("call void @wolf_map_set(ptr %s, ptr %s, ptr %s)", objVal, keyReg, valVal))
	case *ir.IndexExpr:
		objVal := e.emitExpr(target.Object, "ptr")
		idxType := e.inferExprType(target.Index)
		idxVal := e.emitExpr(target.Index, idxType)
		if idxType != "ptr" {
			stringPtr := e.emitArgAsString(target.Index)
			idxVal = stringPtr
		}
		valVal := e.emitArgAsString(s.Value)
		e.writelnIndent(fmt.Sprintf("call void @wolf_map_set(ptr %s, ptr %s, ptr %s)", objVal, idxVal, valVal))
	default:
		e.writelnIndent(fmt.Sprintf("; TODO: complex assignment target %T", s.Target))
	}
}

// inferExprType returns the LLVM type of the given expression.
func (e *LLVMEmitter) inferExprType(expr ir.Expr) string {
	switch ex := expr.(type) {
	case *ir.IntLit:
		return "i64"
	case *ir.FloatLit:
		return "double"
	case *ir.BoolLit:
		return "i1"
	case *ir.StringLit:
		return "ptr"
	case *ir.NilLit:
		return "ptr"
	case *ir.BinaryExpr:
		// Arithmetic ops on ints → i64, comparisons → i1
		switch ex.Op {
		case "==", "!=", "<", ">", "<=", ">=", "&&", "||":
			return "i1"
		default:
			if ex.Op == "+" && (e.inferExprType(ex.Left) == "ptr" || e.inferExprType(ex.Right) == "ptr") {
				return "ptr"
			}
			// Check if either side is float
			if e.inferExprType(ex.Left) == "double" || e.inferExprType(ex.Right) == "double" {
				return "double"
			}
			return "i64"
		}
	case *ir.UnaryExpr:
		if ex.Op == "!" {
			return "i1"
		}
		return e.inferExprType(ex.Operand)
	case *ir.FmtSprintf:
		return "ptr"
	case *ir.StringConcat:
		return "ptr"
	case *ir.CallExpr:
		if ident, ok := ex.Callee.(*ir.Ident); ok {
			switch ident.Name {
			case "time", "strtotime":
				return "i64"
			case "date", "env", "session_get":
				return "ptr"
			}
			if fnSig, exists := e.funcSigs[ident.Name]; exists && len(fnSig.ReturnTypes) > 0 {
				return e.wolfTypeToLLVM(fnSig.ReturnTypes[0])
			}
		}
		return "ptr" // default for function calls
	case *ir.MethodCallExpr:
		return "ptr" // default for method calls
	case *ir.StaticCall:
		// Convert Wolf_Math::Abs or math.abs to generic names
		cfunc := strings.ToLower(fmt.Sprintf("%s_%s", ex.Class, ex.Method))
		switch cfunc {
		case "wolf_math_abs", "wolf_math_ceil", "wolf_math_floor", "wolf_math_max", "wolf_math_min", "math_abs", "math_ceil", "math_floor", "math_max", "math_min",
			"wolf_math_sin", "wolf_math_cos", "wolf_math_tan", "wolf_math_asin", "wolf_math_acos", "wolf_math_atan", "wolf_math_atan2",
			"wolf_math_sqrt", "wolf_math_pow", "wolf_math_log", "wolf_math_log10", "wolf_math_exp",
			"wolf_math_round", "wolf_math_fmod", "wolf_math_pi",
			"math_sin", "math_cos", "math_tan", "math_asin", "math_acos", "math_atan", "math_atan2",
			"math_sqrt", "math_pow", "math_log", "math_log10", "math_exp",
			"math_round", "math_fmod", "math_pi":
			return "double"
		case "wolf_math_random", "math_random":
			return "i64"
		case "wolf_number_format":
			return "ptr"
		case "wolf_json_encode", "wolf_json_decode", "wolf_strings_upper", "wolf_strings_join", "wolf_strings_replace":
			return "ptr"
		case "wolf_strings_contains", "wolf_env_has":
			return "i1"
		}
		return "ptr"
	case *ir.Ident:
		if t, ok := e.varTypes[ex.Name]; ok {
			return t
		}
		return "ptr"
	default:
		return "ptr"
	}
}

func (e *LLVMEmitter) emitExprStmt(s *ir.ExprStmt) {
	switch expr := s.Expr.(type) {
	case *ir.CallExpr:
		e.emitCallExpr(expr)
	case *ir.MethodCallExpr:
		e.emitMethodCall(expr)
	default:
		e.emitExpr(s.Expr, "")
	}
}

func (e *LLVMEmitter) emitReturn(s *ir.ReturnStmt) {
	if len(s.Values) == 0 {
		e.writelnIndent("ret void")
	} else {
		llType := e.inferExprType(s.Values[0])
		val := e.emitExpr(s.Values[0], llType)
		e.writelnIndent(fmt.Sprintf("ret %s %s", llType, val))
	}
}

func (e *LLVMEmitter) emitIf(s *ir.IfStmt) {
	condVal := e.emitExpr(s.Condition, "i1")
	thenLabel := e.nextLabel("if.then")

	hasElseIfs := len(s.ElseIfs) > 0
	hasElse := s.ElseBody != nil
	endLabel := e.nextLabel("if.end")

	nextLabel := endLabel
	if hasElseIfs {
		nextLabel = e.nextLabel("if.elseif.cond")
	} else if hasElse {
		nextLabel = e.nextLabel("if.else")
	}

	e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", condVal, thenLabel, nextLabel))

	// Then block
	e.writeln(fmt.Sprintf("%s:", thenLabel))
	for _, stmt := range s.Body {
		e.emitStmt(stmt)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))

	// Else If blocks
	for i, elif := range s.ElseIfs {
		e.writeln(fmt.Sprintf("%s:", nextLabel))
		elifCondVal := e.emitExpr(elif.Condition, "i1")

		elifThenLabel := e.nextLabel("if.elseif.then")

		if i < len(s.ElseIfs)-1 {
			nextLabel = e.nextLabel("if.elseif.cond")
		} else if hasElse {
			nextLabel = e.nextLabel("if.else")
		} else {
			nextLabel = endLabel
		}

		e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", elifCondVal, elifThenLabel, nextLabel))

		// ElseIf Then block
		e.writeln(fmt.Sprintf("%s:", elifThenLabel))
		for _, stmt := range elif.Body {
			e.emitStmt(stmt)
		}
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
	}

	// Else block
	if hasElse {
		e.writeln(fmt.Sprintf("%s:", nextLabel))
		for _, stmt := range s.ElseBody {
			e.emitStmt(stmt)
		}
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
	}

	// End
	e.writeln(fmt.Sprintf("%s:", endLabel))
}

func (e *LLVMEmitter) emitFor(s *ir.ForStmt) {
	condLabel := e.nextLabel("for.cond")
	bodyLabel := e.nextLabel("for.body")
	updateLabel := e.nextLabel("for.update")
	endLabel := e.nextLabel("for.end")

	// Init
	if s.Init != nil {
		e.emitStmt(s.Init)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))

	// Condition
	e.writeln(fmt.Sprintf("%s:", condLabel))
	if s.Cond != nil {
		condVal := e.emitExpr(s.Cond, "i1")
		e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", condVal, bodyLabel, endLabel))
	} else {
		e.writelnIndent(fmt.Sprintf("br label %%%s", bodyLabel))
	}

	// Body
	e.writeln(fmt.Sprintf("%s:", bodyLabel))
	for _, stmt := range s.Body {
		e.emitStmt(stmt)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", updateLabel))

	// Update
	e.writeln(fmt.Sprintf("%s:", updateLabel))
	if s.Update != nil {
		e.emitStmt(s.Update)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))

	// End
	e.writeln(fmt.Sprintf("%s:", endLabel))
}

func (e *LLVMEmitter) emitRange(s *ir.RangeStmt) {
	arrVal := e.emitExpr(s.Iterable, "ptr")

	// Get length
	lenReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_array_length(ptr %s)", lenReg, arrVal))

	// Loop counter setup
	idxPtr := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = alloca i64", idxPtr))
	e.writelnIndent(fmt.Sprintf("store i64 0, ptr %s", idxPtr))

	condLabel := e.nextLabel("range.cond")
	bodyLabel := e.nextLabel("range.body")
	endLabel := e.nextLabel("range.end")

	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))
	e.writeln(fmt.Sprintf("%s:", condLabel))

	idxVal := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = load i64, ptr %s", idxVal, idxPtr))

	cmpReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = icmp slt i64 %s, %s", cmpReg, idxVal, lenReg))
	e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", cmpReg, bodyLabel, endLabel))

	e.writeln(fmt.Sprintf("%s:", bodyLabel))

	// Assign value
	if s.Value != "" && s.Value != "_" {
		valReg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_array_get(ptr %s, i64 %s)", valReg, arrVal, idxVal))
		e.writelnIndent(fmt.Sprintf("%%%s = alloca ptr", s.Value))
		e.varTypes[s.Value] = "ptr"
		e.writelnIndent(fmt.Sprintf("store ptr %s, ptr %%%s", valReg, s.Value))
	}

	// Assign key
	if s.Key != "" && s.Key != "_" {
		e.writelnIndent(fmt.Sprintf("%%%s = alloca i64", s.Key))
		e.varTypes[s.Key] = "i64"
		e.writelnIndent(fmt.Sprintf("store i64 %s, ptr %%%s", idxVal, s.Key))
	}

	for _, stmt := range s.Body {
		e.emitStmt(stmt)
	}

	// Update loop counter
	nextIdx := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = add i64 %s, 1", nextIdx, idxVal))
	e.writelnIndent(fmt.Sprintf("store i64 %s, ptr %s", nextIdx, idxPtr))
	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))

	e.writeln(fmt.Sprintf("%s:", endLabel))
}

func (e *LLVMEmitter) emitSwitch(s *ir.SwitchStmt) {
	subjType := e.inferExprType(s.Subject)
	if subjType == "" {
		subjType = "i64"
	}
	subjVal := e.emitExpr(s.Subject, subjType)
	endLabel := e.nextLabel("match.end")

	var nextCondLabel string
	if len(s.Cases) > 0 {
		nextCondLabel = e.nextLabel("match.case.cond")
		e.writelnIndent(fmt.Sprintf("br label %%%s", nextCondLabel))
	} else if len(s.Default) > 0 {
		nextCondLabel = e.nextLabel("match.default")
		e.writelnIndent(fmt.Sprintf("br label %%%s", nextCondLabel))
	} else {
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
		e.writeln(fmt.Sprintf("%s:", endLabel))
		return
	}

	for i, c := range s.Cases {
		e.writeln(fmt.Sprintf("%s:", nextCondLabel))

		caseVal := e.emitExpr(c.Value, subjType)
		cmpReg := e.nextLocal()

		// Note: Using integer/pointer naive equality for now. Strings would need strcmp.
		e.writelnIndent(fmt.Sprintf("%s = icmp eq %s %s, %s", cmpReg, subjType, subjVal, caseVal))

		caseBodyLabel := e.nextLabel("match.case.body")

		if i < len(s.Cases)-1 {
			nextCondLabel = e.nextLabel("match.case.cond")
		} else if len(s.Default) > 0 {
			nextCondLabel = e.nextLabel("match.default")
		} else {
			nextCondLabel = endLabel
		}

		e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", cmpReg, caseBodyLabel, nextCondLabel))

		e.writeln(fmt.Sprintf("%s:", caseBodyLabel))
		for _, stmt := range c.Body {
			e.emitStmt(stmt)
		}
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
	}

	if len(s.Default) > 0 {
		e.writeln(fmt.Sprintf("%s:", nextCondLabel))
		for _, stmt := range s.Default {
			e.emitStmt(stmt)
		}
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
	}

	e.writeln(fmt.Sprintf("%s:", endLabel))
}

// ========== Expression Emission ==========

// emitExpr emits LLVM IR for an expression and returns the register/value name.
func (e *LLVMEmitter) emitExpr(expr ir.Expr, expectedType string) string {
	switch ex := expr.(type) {
	case *ir.IntLit:
		return ex.Value
	case *ir.FloatLit:
		return ex.Value
	case *ir.BoolLit:
		if ex.Value {
			return "1"
		}
		return "0"
	case *ir.NilLit:
		return "null"
	case *ir.StringLit:
		label := e.addStringConst(ex.Value)
		reg := e.nextLocal()
		byteLen := len(ex.Value) + 1
		e.writelnIndent(fmt.Sprintf("%s = getelementptr [%d x i8], ptr %s, i64 0, i64 0", reg, byteLen, label))
		return reg
	case *ir.Ident:
		loadType := "ptr"
		if t, ok := e.varTypes[ex.Name]; ok {
			loadType = t
		}
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = load %s, ptr %%%s", reg, loadType, ex.Name))
		return reg
	case *ir.FieldAccess:
		objVal := e.emitExpr(ex.Object, "ptr")
		keyLabel := e.addStringConst(ex.Field)
		keyReg := e.nextLocal()
		byteLen := len(ex.Field) + 1
		e.writelnIndent(fmt.Sprintf("%s = getelementptr [%d x i8], ptr %s, i64 0, i64 0", keyReg, byteLen, keyLabel))
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_map_get(ptr %s, ptr %s)", reg, objVal, keyReg))
		return reg
	case *ir.BinaryExpr:
		return e.emitBinaryExpr(ex, expectedType)
	case *ir.UnaryExpr:
		return e.emitUnaryExpr(ex)
	case *ir.CallExpr:
		return e.emitCallExpr(ex)
	case *ir.MethodCallExpr:
		return e.emitMethodCall(ex)
	case *ir.StaticCall:
		return e.emitStaticCall(ex)
	case *ir.FmtSprintf:
		return e.emitFmtSprintf(ex)
	case *ir.StringConcat:
		return e.emitStringConcat(ex)
	case *ir.PostfixExpr:
		return e.emitPostfix(ex)
	case *ir.IndexExpr:
		return e.emitIndexExpr(ex)
	case *ir.SliceLit:
		return e.emitSliceLit(ex)
	case *ir.MapLit:
		return e.emitMapLit(ex)
	default:
		e.writelnIndent(fmt.Sprintf("; TODO: unhandled expr type %T", expr))
		return "null"
	}
}

func (e *LLVMEmitter) emitIndexExpr(ex *ir.IndexExpr) string {
	objVal := e.emitExpr(ex.Object, "ptr")
	idxType := e.inferExprType(ex.Index)
	idxVal := e.emitExpr(ex.Index, idxType)
	reg := e.nextLocal()

	if idxType == "i64" {
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_array_get(ptr %s, i64 %s)", reg, objVal, idxVal))
	} else {
		// Default to map_get if the index parameter is not a pure integer
		if idxType != "ptr" {
			stringPtr := e.emitArgAsString(ex.Index)
			idxVal = stringPtr
		}
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_map_get(ptr %s, ptr %s)", reg, objVal, idxVal))
	}
	return reg
}

func (e *LLVMEmitter) emitSliceLit(ex *ir.SliceLit) string {
	arrReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_array_create()", arrReg))
	for _, elem := range ex.Elements {
		elemVal := e.emitArgAsString(elem)
		e.writelnIndent(fmt.Sprintf("call void @wolf_array_push(ptr %s, ptr %s)", arrReg, elemVal))
	}
	return arrReg
}

func (e *LLVMEmitter) emitMapLit(ex *ir.MapLit) string {
	mapReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_map_create()", mapReg))
	for i := range ex.Keys {
		keyVal := e.emitArgAsString(ex.Keys[i])
		valVal := e.emitArgAsString(ex.Values[i])
		e.writelnIndent(fmt.Sprintf("call void @wolf_map_set(ptr %s, ptr %s, ptr %s)", mapReg, keyVal, valVal))
	}
	return mapReg
}

func (e *LLVMEmitter) emitBinaryExpr(ex *ir.BinaryExpr, expectedType string) string {
	leftType := e.inferExprType(ex.Left)
	rightType := e.inferExprType(ex.Right)

	if ex.Op == "+" && (leftType == "ptr" || rightType == "ptr") {
		leftVal := e.emitArgAsString(ex.Left)
		rightVal := e.emitArgAsString(ex.Right)
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_string_concat(ptr %s, ptr %s)", reg, leftVal, rightVal))
		return reg
	}

	left := e.emitExpr(ex.Left, "i64")
	right := e.emitExpr(ex.Right, "i64")
	reg := e.nextLocal()

	switch ex.Op {
	case "+":
		e.writelnIndent(fmt.Sprintf("%s = add i64 %s, %s", reg, left, right))
	case "-":
		e.writelnIndent(fmt.Sprintf("%s = sub i64 %s, %s", reg, left, right))
	case "*":
		e.writelnIndent(fmt.Sprintf("%s = mul i64 %s, %s", reg, left, right))
	case "/":
		e.writelnIndent(fmt.Sprintf("%s = sdiv i64 %s, %s", reg, left, right))
	case "%":
		e.writelnIndent(fmt.Sprintf("%s = srem i64 %s, %s", reg, left, right))
	case "==":
		e.writelnIndent(fmt.Sprintf("%s = icmp eq i64 %s, %s", reg, left, right))
	case "!=":
		e.writelnIndent(fmt.Sprintf("%s = icmp ne i64 %s, %s", reg, left, right))
	case "<":
		e.writelnIndent(fmt.Sprintf("%s = icmp slt i64 %s, %s", reg, left, right))
	case ">":
		e.writelnIndent(fmt.Sprintf("%s = icmp sgt i64 %s, %s", reg, left, right))
	case "<=":
		e.writelnIndent(fmt.Sprintf("%s = icmp sle i64 %s, %s", reg, left, right))
	case ">=":
		e.writelnIndent(fmt.Sprintf("%s = icmp sge i64 %s, %s", reg, left, right))
	case "&&":
		e.writelnIndent(fmt.Sprintf("%s = and i1 %s, %s", reg, left, right))
	case "||":
		e.writelnIndent(fmt.Sprintf("%s = or i1 %s, %s", reg, left, right))
	default:
		e.writelnIndent(fmt.Sprintf("; unknown binary op: %s", ex.Op))
		return "0"
	}
	return reg
}

func (e *LLVMEmitter) emitUnaryExpr(ex *ir.UnaryExpr) string {
	opType := e.inferExprType(ex.Operand)
	operand := e.emitExpr(ex.Operand, opType)
	reg := e.nextLocal()

	switch ex.Op {
	case "!":
		e.writelnIndent(fmt.Sprintf("%s = xor i1 %s, 1", reg, operand))
	case "-":
		if opType == "double" {
			e.writelnIndent(fmt.Sprintf("%s = fsub double 0.0, %s", reg, operand))
		} else {
			e.writelnIndent(fmt.Sprintf("%s = sub i64 0, %s", reg, operand))
		}
	default:
		e.writelnIndent(fmt.Sprintf("; unknown unary op: %s", ex.Op))
		return "0"
	}
	return reg
}

func (e *LLVMEmitter) emitCallExpr(call *ir.CallExpr) string {
	// Check for built-in print
	if ident, ok := call.Callee.(*ir.Ident); ok {
		switch ident.Name {
		case "fmt_Println", "fmt.Println", "wolf_print", "print":
			return e.emitPrintCall(call)
		}
	}

	// Generic function call
	calleeName := ""
	if ident, ok := call.Callee.(*ir.Ident); ok {
		calleeName = ident.Name

		// Map global wolf functions to C runtime equivalents
		switch calleeName {
		case "say":
			calleeName = "wolf_say"
		case "show":
			calleeName = "wolf_show"
		case "inspect":
			calleeName = "wolf_inspect"
		case "time":
			calleeName = "wolf_time_now"
		case "date":
			calleeName = "wolf_time_date"
		case "strtotime":
			calleeName = "wolf_time_strtotime"
		case "sleep":
			calleeName = "wolf_system_sleep"
		case "exit":
			calleeName = "wolf_system_exit"
		case "die":
			calleeName = "wolf_system_die"
		case "env":
			calleeName = "wolf_env_get"
		case "session_begin":
			calleeName = "wolf_session_begin"
		case "session_set":
			calleeName = "wolf_session_set"
		case "session_get":
			calleeName = "wolf_session_get"
		case "session_end":
			calleeName = "wolf_session_end"
		case "define":
			calleeName = "wolf_define"
		case "defined":
			calleeName = "wolf_defined"
		case "define_get":
			calleeName = "wolf_define_get"
		case "number_format":
			calleeName = "wolf_number_format"
		}
	}

	var fnSig *ir.Function
	if calleeName != "" {
		fnSig = e.funcSigs[calleeName]
	}

	args := make([]string, len(call.Args))
	for i, arg := range call.Args {
		expectedType := "ptr"
		if fnSig != nil && i < len(fnSig.Params) {
			expectedType = e.wolfTypeToLLVM(fnSig.Params[i].Type)
		} else if fnSig == nil {
			switch calleeName {
			case "wolf_system_sleep", "wolf_system_exit":
				expectedType = "i64"
			case "wolf_time_date":
				if i == 0 {
					expectedType = "ptr"
				}
				if i == 1 {
					expectedType = "i64"
				}
			case "wolf_math_abs", "wolf_math_ceil", "wolf_math_floor", "wolf_math_round",
				"wolf_math_sin", "wolf_math_cos", "wolf_math_tan",
				"wolf_math_asin", "wolf_math_acos", "wolf_math_atan",
				"wolf_math_sqrt", "wolf_math_log", "wolf_math_log10", "wolf_math_exp":
				expectedType = "double"
			case "wolf_math_max", "wolf_math_min", "wolf_math_atan2", "wolf_math_pow", "wolf_math_fmod":
				expectedType = "double"
			case "wolf_math_random":
				expectedType = "i64"
			case "wolf_number_format":
				if i == 0 {
					expectedType = "double"
				} else if i == 1 {
					expectedType = "i64"
				} else {
					expectedType = "ptr"
				}
			}
		}
		val := e.emitExpr(arg, expectedType)
		args[i] = fmt.Sprintf("%s %s", expectedType, val)
	}

	retType := "void"
	if fnSig != nil && len(fnSig.ReturnTypes) > 0 {
		retType = e.wolfTypeToLLVM(fnSig.ReturnTypes[0])
	} else if fnSig == nil {
		switch calleeName {
		case "wolf_say", "wolf_show", "wolf_inspect", "wolf_system_sleep", "wolf_system_exit", "wolf_system_die", "wolf_session_begin", "wolf_session_set", "wolf_session_end", "wolf_define":
			retType = "void"
		case "wolf_time_now", "wolf_time_strtotime", "wolf_redis_del":
			retType = "i64"
		case "wolf_defined", "wolf_redis_exists":
			retType = "i1"
		case "wolf_math_abs", "wolf_math_ceil", "wolf_math_floor", "wolf_math_max", "wolf_math_min",
			"wolf_math_sin", "wolf_math_cos", "wolf_math_tan",
			"wolf_math_asin", "wolf_math_acos", "wolf_math_atan", "wolf_math_atan2",
			"wolf_math_sqrt", "wolf_math_pow", "wolf_math_log", "wolf_math_log10", "wolf_math_exp",
			"wolf_math_round", "wolf_math_fmod", "wolf_math_pi":
			retType = "double"
		default:
			retType = "ptr" // Call to unknown func (e.g. external) typically returns ptr
		}
	}

	reg := e.nextLocal()
	if retType == "void" {
		e.writelnIndent(fmt.Sprintf("call void @%s(%s)", calleeName, strings.Join(args, ", ")))
		return "null" // return null as dummy
	}

	e.writelnIndent(fmt.Sprintf("%s = call %s @%s(%s)", reg, retType, calleeName, strings.Join(args, ", ")))
	return reg
}

func (e *LLVMEmitter) emitPrintCall(call *ir.CallExpr) string {
	for i, arg := range call.Args {
		// Add space between arguments (like Go's fmt.Println)
		if i > 0 {
			spaceLabel := e.addStringConst(" ")
			spaceReg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = getelementptr [2 x i8], ptr %s, i64 0, i64 0", spaceReg, spaceLabel))
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", spaceReg))
		}

		switch ex := arg.(type) {
		case *ir.StringLit:
			val := e.emitExpr(arg, "ptr")
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		case *ir.IntLit:
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_int(i64 %s)", ex.Value))
		case *ir.FloatLit:
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_float(double %s)", ex.Value))
		case *ir.BoolLit:
			val := "0"
			if ex.Value {
				val = "1"
			}
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_bool(i1 %s)", val))
		case *ir.NilLit:
			e.writelnIndent("call void @wolf_print_nil()")
		case *ir.FmtSprintf:
			val := e.emitFmtSprintf(ex)
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		default:
			// For all other types, convert to string using emitArgAsString and print as string
			val := e.emitArgAsString(arg)
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		}
	}

	// Newline at end
	e.writelnIndent("call void @wolf_println()")
	return "0"
}

func (e *LLVMEmitter) emitFmtSprintf(ex *ir.FmtSprintf) string {
	// For string interpolation: build the result by concatenating parts
	// The FmtSprintf has a Go-style format string and args.
	// We'll decompose it into concat calls.

	// Simple approach: emit each arg as a string, then concat them all
	parts := make([]string, 0)

	// Split the format string by %v and emit literal parts + args
	fmtStr := ex.Format
	argIdx := 0
	lastIdx := 0

	for i := 0; i < len(fmtStr)-1; i++ {
		if fmtStr[i] == '%' && fmtStr[i+1] == 'v' {
			// Emit literal part before %v
			if i > lastIdx {
				literal := fmtStr[lastIdx:i]
				val := e.emitExpr(&ir.StringLit{Value: literal}, "ptr")
				parts = append(parts, val)
			}
			// Emit the arg converted to string
			if argIdx < len(ex.Args) {
				argVal := e.emitArgAsString(ex.Args[argIdx])
				parts = append(parts, argVal)
				argIdx++
			}
			lastIdx = i + 2
			i++ // skip 'v'
		}
	}
	// Emit trailing literal
	if lastIdx < len(fmtStr) {
		literal := fmtStr[lastIdx:]
		val := e.emitExpr(&ir.StringLit{Value: literal}, "ptr")
		parts = append(parts, val)
	}

	// Concatenate all parts
	if len(parts) == 0 {
		return e.emitExpr(&ir.StringLit{Value: ""}, "ptr")
	}
	result := parts[0]
	for i := 1; i < len(parts); i++ {
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_string_concat(ptr %s, ptr %s)", reg, result, parts[i]))
		result = reg
	}
	return result
}

func (e *LLVMEmitter) emitArgAsString(arg ir.Expr) string {
	switch ex := arg.(type) {
	case *ir.StringLit:
		return e.emitExpr(ex, "ptr")
	case *ir.IntLit:
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_int_to_string(i64 %s)", reg, ex.Value))
		return reg
	case *ir.FloatLit:
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_float_to_string(double %s)", reg, ex.Value))
		return reg
	case *ir.BoolLit:
		val := "0"
		if ex.Value {
			val = "1"
		}
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_bool_to_string(i1 %s)", reg, val))
		return reg
	default:
		llType := e.inferExprType(arg)
		val := e.emitExpr(arg, llType)

		switch llType {
		case "i64":
			reg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_int_to_string(i64 %s)", reg, val))
			return reg
		case "double":
			reg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_float_to_string(double %s)", reg, val))
			return reg
		case "i1":
			reg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_bool_to_string(i1 %s)", reg, val))
			return reg
		default:
			return val
		}
	}
}

func (e *LLVMEmitter) emitStringConcat(ex *ir.StringConcat) string {
	left := e.emitArgAsString(ex.Left)
	right := e.emitArgAsString(ex.Right)
	reg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_string_concat(ptr %s, ptr %s)", reg, left, right))
	return reg
}

func (e *LLVMEmitter) emitPostfix(ex *ir.PostfixExpr) string {
	ident, ok := ex.Operand.(*ir.Ident)
	if !ok {
		e.writelnIndent(fmt.Sprintf("; TODO: postfix on non-ident %T", ex.Operand))
		return "null"
	}

	llType := e.inferExprType(ex.Operand)
	val := e.emitExpr(ex.Operand, llType)
	reg := e.nextLocal()

	switch ex.Op {
	case "++":
		if llType == "double" {
			e.writelnIndent(fmt.Sprintf("%s = fadd double %s, 1.0", reg, val))
		} else {
			e.writelnIndent(fmt.Sprintf("%s = add i64 %s, 1", reg, val))
		}
	case "--":
		if llType == "double" {
			e.writelnIndent(fmt.Sprintf("%s = fsub double %s, 1.0", reg, val))
		} else {
			e.writelnIndent(fmt.Sprintf("%s = sub i64 %s, 1", reg, val))
		}
	default:
		e.writelnIndent(fmt.Sprintf("; unknown postfix op: %s", ex.Op))
		return "null"
	}

	e.writelnIndent(fmt.Sprintf("store %s %s, ptr %%%s", llType, reg, ident.Name))
	return reg
}

func (e *LLVMEmitter) emitMethodCall(mc *ir.MethodCallExpr) string {
	objVal := e.emitExpr(mc.Object, "ptr")

	var calleeName string
	for name := range e.funcSigs {
		if strings.HasSuffix(name, "_"+mc.Method) {
			calleeName = name
			break
		}
	}
	if calleeName == "" {
		calleeName = mc.Method
	}

	fnSig := e.funcSigs[calleeName]

	args := []string{fmt.Sprintf("ptr %s", objVal)}
	for i, arg := range mc.Args {
		expectedType := "ptr"
		if fnSig != nil && i+1 < len(fnSig.Params) {
			expectedType = e.wolfTypeToLLVM(fnSig.Params[i+1].Type)
		}
		val := e.emitExpr(arg, expectedType)
		args = append(args, fmt.Sprintf("%s %s", expectedType, val))
	}

	retType := "void"
	if fnSig != nil && len(fnSig.ReturnTypes) > 0 {
		retType = e.wolfTypeToLLVM(fnSig.ReturnTypes[0])
	} else if fnSig == nil {
		retType = "ptr"
	}

	reg := e.nextLocal()
	if retType == "void" {
		e.writelnIndent(fmt.Sprintf("call void @%s(%s)", calleeName, strings.Join(args, ", ")))
		return "null"
	}

	e.writelnIndent(fmt.Sprintf("%s = call %s @%s(%s)", reg, retType, calleeName, strings.Join(args, ", ")))
	return reg
}

func (e *LLVMEmitter) emitStaticCall(sc *ir.StaticCall) string {
	// Standardize names: Wolf_Math::Abs or math.abs -> wolf_math_abs
	calleeName := strings.ToLower(fmt.Sprintf("%s_%s", sc.Class, sc.Method))

	switch strings.ToLower(sc.Class) {
	case "math", "wolf_math":
		calleeName = strings.ToLower(fmt.Sprintf("wolf_math_%s", sc.Method))
	case "json", "wolf_json":
		calleeName = strings.ToLower(fmt.Sprintf("wolf_json_%s", sc.Method))
	case "strings", "wolf_strings":
		calleeName = strings.ToLower(fmt.Sprintf("wolf_strings_%s", sc.Method))
	}

	args := make([]string, len(sc.Args))
	for i, arg := range sc.Args {
		llType := e.inferExprType(arg)
		val := e.emitExpr(arg, llType)
		args[i] = fmt.Sprintf("%s %s", llType, val)
	}

	retType := e.inferExprType(sc)
	reg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call %s @%s(%s)", reg, retType, calleeName, strings.Join(args, ", ")))
	return reg
}

// ========== Type Mapping ==========

func (e *LLVMEmitter) wolfTypeToLLVM(wolfType string) string {
	switch wolfType {
	case "int", "int64", "i64":
		return "i64"
	case "float", "float64", "double":
		return "double"
	case "bool", "i1":
		return "i1"
	case "string", "ptr", "":
		return "ptr"
	case "void":
		return "void"
	default:
		return "ptr" // Default to pointer for complex types
	}
}

// ========== Output Helpers ==========

func (e *LLVMEmitter) writeln(s string) {
	e.buf.WriteString(s)
	e.buf.WriteByte('\n')
}

func (e *LLVMEmitter) writelnIndent(s string) {
	for i := 0; i < e.indent; i++ {
		e.buf.WriteString("  ")
	}
	e.buf.WriteString(s)
	e.buf.WriteByte('\n')
}
