// Package emitter also contains the LLVM IR code generator.
// LLVMEmitter transforms WIR into LLVM IR text (.ll files).
// This emitter produces LLVM IR directly as text — no external
// Go dependencies required (no llir/llvm package needed).
package emitter

import (
	"fmt"
	"strings"

	"github.com/wolflang/wolf/internal/ir"
)

// LLVMEmitter generates LLVM IR text from WIR.
type LLVMEmitter struct {
	buf             strings.Builder
	stringConsts    map[string]string // value → @.str.N label
	strCounter      int
	localCounter    int
	labelCounter    int
	indent          int
	varTypes        map[string]string
	funcSigs        map[string]*ir.Function
	currentRetType  string
	declaredExterns map[string]bool
	emittedTypes    map[string]string // register → actual LLVM type emitted
	TargetTriple    string            // auto-detected or set by compiler
}

// NewLLVMEmitter creates a new LLVM IR emitter.
func NewLLVMEmitter() *LLVMEmitter {
	return &LLVMEmitter{
		stringConsts:    make(map[string]string),
		varTypes:        make(map[string]string),
		funcSigs:        make(map[string]*ir.Function),
		declaredExterns: make(map[string]bool),
		emittedTypes:    make(map[string]string),
	}
}

// nextLocal returns a fresh LLVM local register name.
func (e *LLVMEmitter) nextLocal() string {
	e.localCounter++
	return fmt.Sprintf("%%t%d", e.localCounter)
}

// nextLabel returns a fresh LLVM label name.
func (e *LLVMEmitter) nextLabel(prefix string) string {
	e.labelCounter++
	return fmt.Sprintf("%s.%d", prefix, e.labelCounter)
}

// addStringConst registers a string constant and returns its global label.
func (e *LLVMEmitter) addStringConst(value string) string {
	if label, ok := e.stringConsts[value]; ok {
		return label
	}
	e.strCounter++
	label := fmt.Sprintf("@.str.%d", e.strCounter)
	e.stringConsts[value] = label
	return label
}

// llvmEscapeString escapes a string for LLVM IR string constants.
func llvmEscapeString(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		ch := s[i]
		switch ch {
		case '\\':
			b.WriteString("\\5C")
		case '"':
			b.WriteString("\\22")
		case '\n':
			b.WriteString("\\0A")
		case '\r':
			b.WriteString("\\0D")
		case '\t':
			b.WriteString("\\09")
		case '\x00':
			b.WriteString("\\00")
		default:
			if ch < 32 || ch > 126 {
				b.WriteString(fmt.Sprintf("\\%02X", ch))
			} else {
				b.WriteByte(ch)
			}
		}
	}
	return b.String()
}

// Emit generates LLVM IR text from a WIR program.
func (e *LLVMEmitter) Emit(program *ir.Program) string {
	e.buf.Reset()
	e.localCounter = 0
	e.labelCounter = 0

	// We'll collect all string constants during emission,
	// then prepend them at the top.
	var bodyBuf strings.Builder

	// Swap buffers: emit body first to collect string constants
	mainBuf := &e.buf
	e.buf = bodyBuf

	// Pre-populate all signatures so forward references work
	for _, fn := range program.Functions {
		e.funcSigs[fn.Name] = fn
	}
	for _, cls := range program.Classes {
		if cls.Constructor != nil {
			cls.Constructor.Name = "New" + cls.Name
			cls.Constructor.ReturnTypes = []string{"ptr"}
			e.funcSigs[cls.Constructor.Name] = cls.Constructor
		}
		for _, method := range cls.Methods {
			method.Params = append([]*ir.Param{{Name: "this", Type: "ptr"}}, method.Params...)
			method.Name = fmt.Sprintf("%s_%s", cls.Name, method.Name)
			e.funcSigs[method.Name] = method
		}
	}

	// Emit functions
	for _, fn := range program.Functions {
		e.emitFunction(fn)
		e.writeln("")
	}

	// Emit classes
	for _, cls := range program.Classes {
		if cls.Constructor != nil {
			e.emitConstructor(cls.Constructor, cls.Name)
			e.writeln("")
		}
		for _, method := range cls.Methods {
			e.emitFunction(method)
			e.writeln("")
		}
	}

	// Emit main function from InitStmts
	if len(program.InitStmts) > 0 {
		e.writeln("define i32 @main(i32 %argc, ptr %argv) {")
		e.writeln("entry:")
		e.indent++
		e.writelnIndent("call void @wolf_init_args(i32 %argc, ptr %argv)")

		// Reset local var types for main
		oldVarTypes := e.varTypes
		e.varTypes = make(map[string]string)

		e.collectLocalVars(program.InitStmts)

		// Emit allocas in entry block
		for name, llType := range e.varTypes {
			e.writelnIndent(fmt.Sprintf("%%%s = alloca %s", name, llType))
		}

		for _, stmt := range program.InitStmts {
			e.emitStmt(stmt)
		}

		e.varTypes = oldVarTypes
		e.writelnIndent("ret i32 0")
		e.indent--
		e.writeln("}")
	}

	// Now assemble: header + string constants + body
	bodyStr := e.buf.String()
	e.buf = *mainBuf
	e.buf.Reset()

	// Module header
	e.writeln("; Wolf Language — LLVM IR Output")
	e.writeln("; Generated by wolf compiler")
	e.writeln("")
	triple := e.TargetTriple
	if triple == "" {
		triple = "x86_64-pc-linux-gnu" // fallback
	}
	e.writeln(fmt.Sprintf("target triple = \"%s\"", triple))
	e.writeln("")

	// String constants
	if len(e.stringConsts) > 0 {
		e.writeln("; --- String Constants ---")
		for value, label := range e.stringConsts {
			escaped := llvmEscapeString(value)
			byteLen := len(value) + 1 // +1 for null terminator
			e.writeln(fmt.Sprintf("%s = private unnamed_addr constant [%d x i8] c\"%s\\00\"", label, byteLen, escaped))
		}
		e.writeln("")
	}

	// External function declarations
	e.writeln("; --- External Runtime Functions ---")
	e.writeln("declare void @wolf_print_str(ptr)")
	e.writeln("declare void @wolf_print_int(i64)")
	e.writeln("declare void @wolf_print_float(double)")
	e.writeln("declare void @wolf_print_bool(i1)")
	e.writeln("declare void @wolf_print_nil()")
	e.writeln("declare void @wolf_println()")
	e.writeln("declare ptr @wolf_string_concat(ptr, ptr)")
	e.writeln("declare i64 @wolf_string_length(ptr)")
	e.writeln("declare ptr @wolf_string_upper(ptr)")
	e.writeln("declare ptr @wolf_string_lower(ptr)")
	e.writeln("declare ptr @wolf_string_trim(ptr)")
	e.writeln("declare ptr @wolf_int_to_string(i64)")
	e.writeln("declare ptr @wolf_float_to_string(double)")
	e.writeln("declare ptr @wolf_bool_to_string(i1)")
	e.writeln("")

	e.writeln("; --- Math ---")
	e.writeln("declare double @wolf_math_abs(double)")
	e.writeln("declare double @wolf_math_ceil(double)")
	e.writeln("declare double @wolf_math_floor(double)")
	e.writeln("declare double @wolf_math_max(double, double)")
	e.writeln("declare double @wolf_math_min(double, double)")
	e.writeln("declare i64 @wolf_math_random(i64, i64)")
	e.writeln("declare double @wolf_math_sin(double)")
	e.writeln("declare double @wolf_math_cos(double)")
	e.writeln("declare double @wolf_math_tan(double)")
	e.writeln("declare double @wolf_math_asin(double)")
	e.writeln("declare double @wolf_math_acos(double)")
	e.writeln("declare double @wolf_math_atan(double)")
	e.writeln("declare double @wolf_math_atan2(double, double)")
	e.writeln("declare double @wolf_math_sqrt(double)")
	e.writeln("declare double @wolf_math_pow(double, double)")
	e.writeln("declare double @wolf_math_log(double)")
	e.writeln("declare double @wolf_math_log10(double)")
	e.writeln("declare double @wolf_math_exp(double)")
	e.writeln("declare double @wolf_math_round(double)")
	e.writeln("declare double @wolf_math_fmod(double, double)")
	e.writeln("declare double @wolf_math_pi()")
	e.writeln("declare ptr @wolf_number_format(double, i64, ptr, ptr)")
	e.writeln("")

	e.writeln("; --- Database (Mock) ---")
	e.writeln("declare ptr @wolf_db_connect(ptr, ptr, ptr, ptr)")
	e.writeln("declare ptr @wolf_db_prepare(ptr, ptr)")
	e.writeln("declare void @wolf_db_bind(ptr, ptr, ptr)")
	e.writeln("declare i64 @wolf_db_execute(ptr)")
	e.writeln("declare ptr @wolf_db_fetch_all(ptr)")
	e.writeln("declare ptr @wolf_db_fetch_one(ptr)")
	e.writeln("declare i64 @wolf_db_row_count(ptr)")
	e.writeln("declare i64 @wolf_db_last_insert_id(ptr)")
	e.writeln("declare void @wolf_db_close(ptr)")
	e.writeln("declare void @wolf_db_begin_transaction(ptr)")
	e.writeln("declare void @wolf_db_commit(ptr)")
	e.writeln("declare void @wolf_db_rollback(ptr)")
	e.writeln("")

	e.writeln("; --- Stdlib Strings & JSON ---")
	e.writeln("declare i1 @wolf_strings_contains(ptr, ptr)")
	e.writeln("declare ptr @wolf_strings_upper(ptr)")
	e.writeln("declare ptr @wolf_strings_title(ptr)")
	e.writeln("declare ptr @wolf_strings_split(ptr, ptr)")
	e.writeln("declare ptr @wolf_strings_trimleft(ptr, ptr)")
	e.writeln("declare ptr @wolf_strings_trimright(ptr, ptr)")
	e.writeln("declare ptr @wolf_strings_join(ptr, ptr)")
	e.writeln("declare ptr @wolf_json_encode(ptr)")
	e.writeln("")

	e.writeln("; --- Output & Display ---")
	e.writeln("declare void @wolf_say(ptr)")
	e.writeln("declare void @wolf_show(ptr)")
	e.writeln("declare void @wolf_inspect(ptr)")
	e.writeln("")

	e.writeln("; --- Phase 1 Stdlib: Strings ---")
	e.writeln("declare ptr @wolf_strtoupper(ptr)")
	e.writeln("declare ptr @wolf_strtolower(ptr)")
	e.writeln("declare ptr @wolf_ucfirst(ptr)")
	e.writeln("declare ptr @wolf_ucwords(ptr)")
	e.writeln("declare ptr @wolf_lcfirst(ptr)")
	e.writeln("declare ptr @wolf_trim(ptr)")
	e.writeln("declare ptr @wolf_ltrim(ptr)")
	e.writeln("declare ptr @wolf_rtrim(ptr)")
	e.writeln("declare i1 @wolf_str_contains(ptr, ptr)")
	e.writeln("declare i1 @wolf_str_starts_with(ptr, ptr)")
	e.writeln("declare i1 @wolf_str_ends_with(ptr, ptr)")
	e.writeln("declare ptr @wolf_str_replace(ptr, ptr, ptr)")
	e.writeln("declare ptr @wolf_str_repeat(ptr, i64)")
	e.writeln("declare ptr @wolf_str_pad(ptr, i64, ptr)")
	e.writeln("declare ptr @wolf_explode(ptr, ptr)")
	e.writeln("declare ptr @wolf_implode(ptr, ptr)")
	e.writeln("declare ptr @wolf_substr(ptr, i64, i64)")
	e.writeln("declare i64 @wolf_strpos(ptr, ptr)")
	e.writeln("declare i64 @wolf_strrpos(ptr, ptr)")
	e.writeln("declare i64 @wolf_str_word_count(ptr)")
	e.writeln("declare i64 @wolf_strcmp(ptr, ptr)")
	e.writeln("declare ptr @wolf_nl2br(ptr)")
	e.writeln("declare ptr @wolf_strip_tags(ptr)")
	e.writeln("declare ptr @wolf_htmlspecialchars(ptr)")
	e.writeln("declare ptr @wolf_addslashes(ptr)")
	e.writeln("declare ptr @wolf_stripslashes(ptr)")
	e.writeln("declare ptr @wolf_sprintf(ptr, ...)")
	e.writeln("declare ptr @wolf_http_req_file(i64, ptr)")
	e.writeln("declare i64 @wolf_http_req_file_count(i64)")
	e.writeln("declare ptr @wolf_str_ireplace(ptr, ptr, ptr)")
	e.writeln("declare ptr @wolf_htmlspecialchars_decode(ptr)")
	e.writeln("declare double @wolf_similar_text(ptr, ptr)")
	e.writeln("declare ptr @wolf_wordwrap(ptr, i64, ptr, i1)")
	e.writeln("declare ptr @wolf_quoted_printable_encode(ptr)")
	e.writeln("")
	e.writeln("; --- Phase 1 Stdlib: Regex ---")
	e.writeln("declare i1 @wolf_preg_match(ptr, ptr)")
	e.writeln("declare ptr @wolf_preg_match_captures(ptr, ptr)")
	e.writeln("declare i64 @wolf_preg_match_all(ptr, ptr)")
	e.writeln("declare ptr @wolf_preg_replace(ptr, ptr, ptr)")
	e.writeln("declare ptr @wolf_preg_split(ptr, ptr)")
	e.writeln("")

	e.writeln("; --- Math Extras ---")
	e.writeln("declare double @wolf_deg2rad(double)")
	e.writeln("declare double @wolf_rad2deg(double)")
	e.writeln("declare double @wolf_clamp(double, double, double)")
	e.writeln("")

	e.writeln("; --- Type Casting ---")
	e.writeln("declare i64 @wolf_intval(ptr)")
	e.writeln("declare double @wolf_floatval(ptr)")
	e.writeln("declare ptr @wolf_strval(i64)")
	e.writeln("declare i1 @wolf_boolval(ptr)")
	e.writeln("declare i64 @wolf_intdiv(i64, i64)")
	e.writeln("declare ptr @wolf_gettype(ptr)")
	e.writeln("declare i1 @wolf_is_numeric(ptr)")
	e.writeln("")

	e.writeln("; --- Encoding ---")
	e.writeln("declare ptr @wolf_base64_encode(ptr)")
	e.writeln("declare ptr @wolf_base64_decode(ptr)")
	e.writeln("declare ptr @wolf_url_encode(ptr)")
	e.writeln("declare ptr @wolf_url_decode(ptr)")
	e.writeln("declare ptr @wolf_json_pretty(ptr)")
	e.writeln("declare ptr @wolf_json_decode(ptr)")
	e.writeln("")

	e.writeln("; --- Security & Crypto ---")
	e.writeln("declare ptr @wolf_md5(ptr)")
	e.writeln("declare ptr @wolf_sha256(ptr)")
	e.writeln("declare ptr @wolf_sha512(ptr)")
	e.writeln("declare ptr @wolf_hash(ptr, ptr)")
	e.writeln("declare ptr @wolf_hash_hmac(ptr, ptr, ptr)")
	e.writeln("declare i1 @wolf_hash_equals(ptr, ptr)")
	e.writeln("declare ptr @wolf_password_hash(ptr)")
	e.writeln("declare i1 @wolf_password_verify(ptr, ptr)")
	e.writeln("declare i1 @wolf_password_needs_rehash(ptr)")
	e.writeln("declare ptr @wolf_encrypt(ptr, ptr)")
	e.writeln("declare ptr @wolf_decrypt(ptr, ptr)")
	e.writeln("declare ptr @wolf_rand_bytes(i64)")
	e.writeln("declare ptr @wolf_rand_hex(i64)")
	e.writeln("declare ptr @wolf_rand_token()")
	e.writeln("declare ptr @wolf_uuid_v4()")
	e.writeln("declare ptr @wolf_uuid_v7()")
	e.writeln("declare ptr @wolf_nanoid(i64)")
	e.writeln("declare ptr @wolf_custom_id(ptr, i64)")
	e.writeln("declare ptr @wolf_base64_url_encode(ptr)")
	e.writeln("declare ptr @wolf_base64_url_decode(ptr)")
	e.writeln("declare ptr @wolf_hex_encode(ptr)")
	e.writeln("declare ptr @wolf_hex_decode(ptr)")
	e.writeln("declare ptr @wolf_jwt_encode(ptr, ptr)")
	e.writeln("declare ptr @wolf_jwt_decode(ptr, ptr)")
	e.writeln("declare ptr @wolf_jwt_decode_unverified(ptr)")
	e.writeln("declare i1 @wolf_jwt_expired(ptr)")
	e.writeln("declare ptr @wolf_curve25519_keypair()")
	e.writeln("declare ptr @wolf_curve25519_shared(ptr, ptr)")
	e.writeln("declare ptr @wolf_sign(ptr, ptr)")
	e.writeln("declare i1 @wolf_verify(ptr, ptr, ptr)")
	e.writeln("")

	e.writeln("; --- Debugging ---")
	e.writeln("declare void @wolf_dump(ptr)")
	e.writeln("declare void @wolf_dd(ptr)")
	e.writeln("declare void @wolf_log_info(ptr)")
	e.writeln("declare void @wolf_log_warning(ptr)")
	e.writeln("declare void @wolf_log_error(ptr)")
	e.writeln("")

	e.writeln("; --- Time & System ---")
	e.writeln("declare i64 @wolf_time_now()")
	e.writeln("declare ptr @wolf_time_date(ptr, i64)")
	e.writeln("declare i64 @wolf_time_strtotime(ptr)")
	e.writeln("declare void @wolf_system_sleep(i64)")
	e.writeln("declare void @wolf_system_exit(i64)")
	e.writeln("declare void @wolf_system_die(ptr)")
	e.writeln("declare ptr @wolf_env_get(ptr, ptr)")
	e.writeln("")

	e.writeln("; --- Phase 2: Arrays ---")
	e.writeln("declare i64 @wolf_count(ptr)")
	e.writeln("declare i1 @wolf_in_array(ptr, ptr)")
	e.writeln("declare i64 @wolf_array_search(ptr, ptr)")
	e.writeln("declare ptr @wolf_array_pop(ptr)")
	e.writeln("declare ptr @wolf_array_shift(ptr)")
	e.writeln("declare void @wolf_array_unshift(ptr, ptr)")
	e.writeln("declare ptr @wolf_array_reverse(ptr)")
	e.writeln("declare ptr @wolf_array_unique(ptr)")
	e.writeln("declare ptr @wolf_array_merge(ptr, ptr)")
	e.writeln("declare ptr @wolf_array_slice(ptr, i64, i64)")
	e.writeln("declare void @wolf_sort(ptr)")
	e.writeln("declare void @wolf_rsort(ptr)")
	e.writeln("declare double @wolf_array_sum(ptr)")
	e.writeln("declare ptr @wolf_array_keys(ptr)")
	e.writeln("declare ptr @wolf_array_values(ptr)")
	e.writeln("declare ptr @wolf_array_diff(ptr, ptr)")
	e.writeln("declare ptr @wolf_array_intersect(ptr, ptr)")
	e.writeln("declare ptr @wolf_array_flip(ptr)")
	e.writeln("declare ptr @wolf_range(i64, i64)")
	e.writeln("")

	e.writeln("; --- Phase 2 Stdlib: Additional Array Functions ---")
	e.writeln("declare ptr @wolf_array_fill(i64, i64, ptr)")
	e.writeln("declare ptr @wolf_array_combine(ptr, ptr)")
	e.writeln("declare ptr @wolf_array_chunk(ptr, i64)")
	e.writeln("declare ptr @wolf_array_column(ptr, ptr)")
	e.writeln("declare double @wolf_array_product(ptr)")
	e.writeln("declare ptr @wolf_array_diff_key(ptr, ptr)")
	e.writeln("declare ptr @wolf_array_splice(ptr, i64, i64)")
	e.writeln("declare ptr @wolf_array_pad(ptr, i64, ptr)")
	e.writeln("declare ptr @wolf_array_count_values(ptr)")
	e.writeln("declare i64 @wolf_array_rand_one(ptr)")
	e.writeln("declare double @wolf_array_mean(ptr)")
	e.writeln("declare double @wolf_array_median(ptr)")
	e.writeln("declare ptr @wolf_array_mode(ptr)")
	e.writeln("declare double @wolf_array_variance(ptr)")
	e.writeln("declare double @wolf_array_std_dev(ptr)")
	e.writeln("declare double @wolf_array_percentile(ptr, double)")
	e.writeln("")

	e.writeln("; --- Phase 3: Date/Time ---")
	e.writeln("declare i64 @wolf_time_ms()")
	e.writeln("declare i64 @wolf_time_ns()")
	e.writeln("declare i64 @wolf_mktime(i64, i64, i64, i64, i64, i64)")
	e.writeln("declare i64 @wolf_date_diff(i64, i64)")
	e.writeln("declare ptr @wolf_date_format(i64, ptr)")
	e.writeln("declare i64 @wolf_day_of_week(i64)")
	e.writeln("declare i64 @wolf_days_in_month(i64, i64)")
	e.writeln("declare i1 @wolf_is_leap_year(i64)")
	e.writeln("declare i64 @wolf_strtotime(ptr)")
	e.writeln("")

	e.writeln("; --- Phase 3: Validation ---")
	e.writeln("declare i1 @wolf_is_email(ptr)")
	e.writeln("declare i1 @wolf_is_url(ptr)")
	e.writeln("declare i1 @wolf_is_phone(ptr)")
	e.writeln("declare i1 @wolf_is_uuid(ptr)")
	e.writeln("declare i1 @wolf_is_json(ptr)")
	e.writeln("declare i1 @wolf_is_ip(ptr)")
	e.writeln("declare i1 @wolf_is_alpha(ptr)")
	e.writeln("declare i1 @wolf_is_alpha_num(ptr)")
	e.writeln("")

	e.writeln("; --- Phase 3: File System ---")
	e.writeln("declare i1 @wolf_file_exists(ptr)")
	e.writeln("declare ptr @wolf_file_read(ptr)")
	e.writeln("declare i1 @wolf_file_write(ptr, ptr)")
	e.writeln("declare i1 @wolf_file_append(ptr, ptr)")
	e.writeln("declare i1 @wolf_file_delete(ptr)")
	e.writeln("declare i64 @wolf_file_size(ptr)")
	e.writeln("declare ptr @wolf_file_extension(ptr)")
	e.writeln("declare ptr @wolf_file_basename(ptr)")
	e.writeln("declare ptr @wolf_file_dirname(ptr)")
	e.writeln("declare i1 @wolf_dir_exists(ptr)")
	e.writeln("")

	e.writeln("; --- Phase 3: Utilities ---")
	e.writeln("declare ptr @wolf_slug(ptr)")
	e.writeln("declare ptr @wolf_truncate(ptr, i64, ptr)")
	e.writeln("")

	e.writeln("; --- Sessions ---")
	e.writeln("declare void @wolf_session_begin()")
	e.writeln("declare void @wolf_session_set(ptr, ptr)")
	e.writeln("declare ptr @wolf_session_get(ptr)")
	e.writeln("declare void @wolf_session_end()")
	e.writeln("")

	e.writeln("; --- Define System (PHP-style constants) ---")
	e.writeln("declare void @wolf_define(ptr, ptr)")
	e.writeln("declare i1 @wolf_defined(ptr)")
	e.writeln("declare ptr @wolf_define_get(ptr)")
	e.writeln("")

	e.writeln("; --- Redis ---")
	e.writeln("declare ptr @wolf_redis_connect(ptr, i64, ptr)")
	e.writeln("declare void @wolf_redis_set(ptr, ptr, ptr, i64)")
	e.writeln("declare ptr @wolf_redis_get(ptr, ptr)")
	e.writeln("declare i64 @wolf_redis_del(ptr, ptr)")
	e.writeln("declare i1 @wolf_redis_exists(ptr, ptr)")
	e.writeln("declare void @wolf_redis_hset(ptr, ptr, ptr, ptr)")
	e.writeln("declare ptr @wolf_redis_hget(ptr, ptr, ptr)")
	e.writeln("declare void @wolf_redis_close(ptr)")
	e.writeln("")

	e.writeln("; --- Data Structures ---")
	e.writeln("declare ptr @wolf_array_create()")
	e.writeln("declare void @wolf_array_push(ptr, ptr)")
	e.writeln("declare ptr @wolf_array_get(ptr, i64)")
	e.writeln("declare i64 @wolf_array_length(ptr)")
	e.writeln("declare ptr @wolf_map_create()")
	e.writeln("declare void @wolf_map_set(ptr, ptr, ptr)")
	e.writeln("declare void @wolf_map_set_int(ptr, ptr, i64)")
	e.writeln("declare void @wolf_map_set_float(ptr, ptr, double)")
	e.writeln("declare void @wolf_map_set_bool(ptr, ptr, i1)")
	e.writeln("declare ptr @wolf_map_get(ptr, ptr)")
	e.writeln("declare ptr @wolf_class_create(ptr)")
	e.writeln("declare i1 @wolf_env_has(ptr)")
	e.writeln("declare ptr @wolf_val_int(i64)")
	e.writeln("declare ptr @wolf_val_float(double)")
	e.writeln("declare ptr @wolf_val_bool(i1)")
	e.writeln("")

	e.writeln("; --- Thread-Local Request Context ---")
	e.writeln("declare void @wolf_set_current_context(ptr, ptr)")
	e.writeln("declare ptr @wolf_get_request_body()")
	e.writeln("declare ptr @wolf_get_request_header(ptr)")
	e.writeln("declare ptr @wolf_get_request_method()")
	e.writeln("declare ptr @wolf_get_request_path()")
	e.writeln("declare ptr @wolf_input(ptr)")
	e.writeln("declare void @wolf_http_response_code(i64)")
	e.writeln("declare void @wolf_http_write_response(ptr)")
	e.writeln("")
	e.writeln("; --- CLI Arguments ---")
	e.writeln("declare void @wolf_init_args(i32, ptr)")
	e.writeln("declare i64 @wolf_argc()")
	e.writeln("declare ptr @wolf_argv(i64)")
	e.writeln("")

	e.writeln("; --- Sanitization ---")
	e.writeln("declare ptr @wolf_sanitize_string(ptr)")
	e.writeln("declare ptr @wolf_sanitize_email(ptr)")
	e.writeln("declare ptr @wolf_sanitize_url(ptr)")
	e.writeln("declare ptr @wolf_sanitize_int(ptr)")
	e.writeln("declare ptr @wolf_sanitize_float(ptr)")
	e.writeln("")

	e.writeln("; --- HTTP Server (C FFI) ---")
	e.writeln("declare void @wolf_http_serve(i64, ptr)")
	e.writeln("declare ptr @wolf_http_req_method(i64)")
	e.writeln("declare ptr @wolf_http_req_path(i64)")
	e.writeln("declare ptr @wolf_http_req_query(i64, ptr)")
	e.writeln("declare ptr @wolf_http_req_header(i64, ptr)")
	e.writeln("declare ptr @wolf_http_req_body(i64)")
	e.writeln("declare void @wolf_http_res_header(i64, ptr, ptr)")
	e.writeln("declare void @wolf_http_res_status(i64, i64)")
	e.writeln("declare void @wolf_http_res_write(i64, ptr)")
	e.writeln("")

	// Body
	e.buf.WriteString(bodyStr)

	return e.buf.String()
}

// ========== Function Emission ==========

func (e *LLVMEmitter) collectLocalVars(stmts []ir.Stmt) {
	for _, stmt := range stmts {
		switch s := stmt.(type) {
		case *ir.VarDeclStmt:
			llType := e.wolfTypeToLLVM(s.Type)
			if llType == "" || llType == "ptr" {
				if s.Value != nil {
					llType = e.inferExprType(s.Value)
				}
				if llType == "" {
					llType = "ptr"
				}
			}
			e.varTypes[s.Name] = llType
		case *ir.AssignStmt:
			if target, ok := s.Target.(*ir.Ident); ok {
				if e.varTypes[target.Name] == "" {
					llType := e.inferExprType(s.Value)
					if llType == "" {
						llType = "ptr"
					}
					e.varTypes[target.Name] = llType
				}
			}
		case *ir.IfStmt:
			e.collectLocalVars(s.Body)
			for _, elif := range s.ElseIfs {
				e.collectLocalVars(elif.Body)
			}
			if s.ElseBody != nil {
				e.collectLocalVars(s.ElseBody)
			}
		case *ir.ForStmt:
			if s.Init != nil {
				e.collectLocalVars([]ir.Stmt{s.Init})
			}
			e.collectLocalVars(s.Body)
		case *ir.RangeStmt:
			e.varTypes[s.Value] = "ptr"
			if s.Key != "" {
				e.varTypes[s.Key] = "ptr" // or infer
			}
			e.collectLocalVars(s.Body)
		case *ir.SwitchStmt:
			for _, c := range s.Cases {
				e.collectLocalVars(c.Body)
			}
			if s.Default != nil {
				e.collectLocalVars(s.Default)
			}
		case *ir.BlockStmt:
			e.collectLocalVars(s.Stmts)
		}
	}
}

// functionHasReturnValue scans a function body for any return statement
// that returns a value (i.e., not a bare "return").
func functionHasReturnValue(stmts []ir.Stmt) bool {
	for _, s := range stmts {
		switch st := s.(type) {
		case *ir.ReturnStmt:
			if len(st.Values) > 0 {
				return true
			}
		case *ir.IfStmt:
			if functionHasReturnValue(st.Body) || functionHasReturnValue(st.ElseBody) {
				return true
			}
		case *ir.BlockStmt:
			if functionHasReturnValue(st.Stmts) {
				return true
			}
		case *ir.ForStmt:
			if functionHasReturnValue(st.Body) {
				return true
			}
		case *ir.RangeStmt:
			if functionHasReturnValue(st.Body) {
				return true
			}
		case *ir.SwitchStmt:
			for _, c := range st.Cases {
				if functionHasReturnValue(c.Body) {
					return true
				}
			}
			if functionHasReturnValue(st.Default) {
				return true
			}
		}
	}
	return false
}

func (e *LLVMEmitter) emitFunction(fn *ir.Function) {
	// Build param list
	params := make([]string, len(fn.Params))
	for i, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		params[i] = fmt.Sprintf("%s %%%s.arg", llType, p.Name)
	}

	retType := "void"
	if len(fn.ReturnTypes) > 0 {
		retType = e.wolfTypeToLLVM(fn.ReturnTypes[0])
	} else if functionHasReturnValue(fn.Body) {
		// Wolf methods without explicit return types that return values
		// should be promoted to ptr (the universal Wolf type)
		retType = "ptr"
	}

	e.currentRetType = retType
	fullName := fn.Name
	e.writeln(fmt.Sprintf("define %s @wolf_%s(%s) {", retType, fullName, strings.Join(params, ", ")))
	e.writeln("entry:")
	e.indent++

	// Reset local var types (but keep param types!)
	oldVarTypes := e.varTypes
	e.varTypes = make(map[string]string)
	e.emittedTypes = make(map[string]string)

	// Register parameters first
	for _, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		e.varTypes[p.Name] = llType
	}

	// Pre-scan statements to find all local vars and determine their types
	e.collectLocalVars(fn.Body)

	// Emit allocas in entry block
	for name, llType := range e.varTypes {
		e.writelnIndent(fmt.Sprintf("%%%s = alloca %s", name, llType))
	}

	// Store args into parameter allocas
	for _, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		e.writelnIndent(fmt.Sprintf("store %s %%%s.arg, ptr %%%s", llType, p.Name, p.Name))
	}

	for _, stmt := range fn.Body {
		e.emitStmt(stmt)
	}

	// Add implicit return if missing
	if retType == "void" && !e.lastStmtIsReturn(fn.Body) {
		e.writelnIndent("ret void")
	}

	e.varTypes = oldVarTypes
	e.indent--
	e.writeln("}")
}

func (e *LLVMEmitter) emitConstructor(fn *ir.Function, className string) {
	params := make([]string, len(fn.Params))
	for i, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		params[i] = fmt.Sprintf("%s %%%s.arg", llType, p.Name)
	}

	emitName := fn.Name
	if !strings.HasPrefix(emitName, "wolf_") {
		emitName = "wolf_" + emitName
	}

	e.writeln(fmt.Sprintf("define ptr @%s(%s) {", emitName, strings.Join(params, ", ")))
	e.writeln("entry:")
	e.indent++

	// Reset local var types (but keep param types!)
	oldVarTypes := e.varTypes
	e.varTypes = make(map[string]string)
	e.emittedTypes = make(map[string]string)

	// Register parameters first
	for _, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		e.varTypes[p.Name] = llType
	}

	// Pre-scan statements to find all local vars and determine their types
	e.collectLocalVars(fn.Body)

	// Add special 'this' variable implicitly for constructor
	e.varTypes["this"] = "ptr"

	// Emit allocas in entry block
	for name, llType := range e.varTypes {
		e.writelnIndent(fmt.Sprintf("%%%s = alloca %s", name, llType))
	}

	// Store args into parameter allocas
	for _, p := range fn.Params {
		llType := e.wolfTypeToLLVM(p.Type)
		e.writelnIndent(fmt.Sprintf("store %s %%%s.arg, ptr %%%s", llType, p.Name, p.Name))
	}

	clsLabel := e.addStringConst(className)
	clsLen := len(className) + 1
	e.writelnIndent(fmt.Sprintf("%%%s.name_var = getelementptr [%d x i8], ptr %s, i64 0, i64 0", className, clsLen, clsLabel))
	thisReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_class_create(ptr %%%s.name_var)", thisReg, className))
	e.writelnIndent(fmt.Sprintf("store ptr %s, ptr %%this", thisReg))

	for _, stmt := range fn.Body {
		e.emitStmt(stmt)
	}

	retReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = load ptr, ptr %%this", retReg))
	e.writelnIndent(fmt.Sprintf("ret ptr %s", retReg))

	e.varTypes = oldVarTypes
	e.indent--
	e.writeln("}")
}

func (e *LLVMEmitter) lastStmtIsReturn(stmts []ir.Stmt) bool {
	if len(stmts) == 0 {
		return false
	}
	_, ok := stmts[len(stmts)-1].(*ir.ReturnStmt)
	return ok
}

// ========== Statement Emission ==========

func (e *LLVMEmitter) emitStmt(stmt ir.Stmt) {
	switch s := stmt.(type) {
	case *ir.VarDeclStmt:
		e.emitVarDecl(s)
	case *ir.AssignStmt:
		e.emitAssign(s)
	case *ir.ExprStmt:
		e.emitExprStmt(s)
	case *ir.ReturnStmt:
		e.emitReturn(s)
	case *ir.IfStmt:
		e.emitIf(s)
	case *ir.ForStmt:
		e.emitFor(s)
	case *ir.RangeStmt:
		e.emitRange(s)
	case *ir.SwitchStmt:
		e.emitSwitch(s)
	case *ir.BlockStmt:
		for _, inner := range s.Stmts {
			e.emitStmt(inner)
		}
	case *ir.RawStmt:
		e.writelnIndent(fmt.Sprintf("; raw: %s", s.Code))
	default:
		e.writelnIndent(fmt.Sprintf("; TODO: unhandled statement type %T", stmt))
	}
}

func (e *LLVMEmitter) emitVarDecl(s *ir.VarDeclStmt) {
	llType := e.wolfTypeToLLVM(s.Type)
	if llType == "" || llType == "ptr" {
		// Try to infer type from value
		if s.Value != nil {
			llType = e.inferExprType(s.Value)
		}
		if llType == "" {
			llType = "ptr"
		}
	}

	if s.Value != nil {
		val := e.emitExpr(s.Value, llType)
		e.writelnIndent(fmt.Sprintf("store %s %s, ptr %%%s", llType, val, s.Name))
	}
}

func (e *LLVMEmitter) emitAssign(s *ir.AssignStmt) {
	switch target := s.Target.(type) {
	case *ir.Ident:
		// Infer type from value expression
		llType := e.inferExprType(s.Value)
		if llType == "" {
			llType = "ptr"
		}

		// Get stored type (may differ for reassignment)
		storedType, ok := e.varTypes[target.Name]
		if !ok {
			storedType = llType
		}

		val := e.emitExpr(s.Value, storedType)
		e.writelnIndent(fmt.Sprintf("store %s %s, ptr %%%s", storedType, val, target.Name))
	case *ir.FieldAccess:
		objVal := e.emitExpr(target.Object, "ptr")
		valVal := e.emitArgAsString(s.Value)
		keyLabel := e.addStringConst(target.Field)
		keyReg := e.nextLocal()
		byteLen := len(target.Field) + 1
		e.writelnIndent(fmt.Sprintf("%s = getelementptr [%d x i8], ptr %s, i64 0, i64 0", keyReg, byteLen, keyLabel))
		e.writelnIndent(fmt.Sprintf("call void @wolf_map_set(ptr %s, ptr %s, ptr %s)", objVal, keyReg, valVal))
	case *ir.IndexExpr:
		objVal := e.emitExpr(target.Object, "ptr")
		idxType := e.inferExprType(target.Index)
		idxVal := e.emitExpr(target.Index, idxType)
		if idxType != "ptr" {
			stringPtr := e.emitArgAsString(target.Index)
			idxVal = stringPtr
		}
		valVal := e.emitArgAsString(s.Value)
		e.writelnIndent(fmt.Sprintf("call void @wolf_map_set(ptr %s, ptr %s, ptr %s)", objVal, idxVal, valVal))
	default:
		e.writelnIndent(fmt.Sprintf("; TODO: complex assignment target %T", s.Target))
	}
}

// inferExprType returns the LLVM type of the given expression.
func (e *LLVMEmitter) inferExprType(expr ir.Expr) string {
	switch ex := expr.(type) {
	case *ir.IntLit:
		return "i64"
	case *ir.FloatLit:
		return "double"
	case *ir.BoolLit:
		return "i1"
	case *ir.StringLit:
		return "ptr"
	case *ir.NilLit:
		return "ptr"
	case *ir.BinaryExpr:
		// Arithmetic ops on ints → i64, comparisons → i1
		switch ex.Op {
		case "==", "!=", "<", ">", "<=", ">=", "&&", "||":
			return "i1"
		default:
			if ex.Op == "+" && (e.inferExprType(ex.Left) == "ptr" || e.inferExprType(ex.Right) == "ptr") {
				return "ptr"
			}
			// Check if either side is float
			if e.inferExprType(ex.Left) == "double" || e.inferExprType(ex.Right) == "double" {
				return "double"
			}
			return "i64"
		}
	case *ir.UnaryExpr:
		if ex.Op == "!" {
			return "i1"
		}
		return e.inferExprType(ex.Operand)
	case *ir.FmtSprintf:
		return "ptr"
	case *ir.StringConcat:
		return "ptr"
	case *ir.CallExpr:
		if ident, ok := ex.Callee.(*ir.Ident); ok {
			switch ident.Name {
			case "time", "strtotime", "redis_del", "db_execute", "db_row_count", "db_last_insert_id",
				"count", "strlen", "strpos", "strrpos", "str_word_count", "strcmp",
				"intval", "intdiv", "array_length", "array_search", "rand", "argc",
				"wolf_intval", "wolf_intdiv", "wolf_count", "wolf_strcmp", "wolf_strlen", "wolf_strpos", "wolf_strrpos", "wolf_argc",
				"wolf_math_random", "wolf_rand_hex", "wolf_string_length", "wolf_array_length",
				"preg_match_all", "wolf_preg_match_all":
				return "i64"
			case "date", "env", "session_get":
				return "ptr"
			case "redis_exists", "wolf_redis_exists", "wolf_boolval", "wolf_is_numeric", "wolf_defined", "wolf_is_email",
				"preg_match", "wolf_preg_match":
				return "i1"
			case "similar_text", "wolf_similar_text":
				return "double"
			}
			if fnSig, exists := e.funcSigs[ident.Name]; exists && len(fnSig.ReturnTypes) > 0 {
				return e.wolfTypeToLLVM(fnSig.ReturnTypes[0])
			}
		}
		return "ptr" // default for function calls
	case *ir.MethodCallExpr:
		var calleeName string
		expectedArgs := len(ex.Args) + 1 // +1 for explicit 'this'
		for name, sig := range e.funcSigs {
			if strings.HasSuffix(name, "_"+ex.Method) {
				if len(sig.Params) == expectedArgs {
					calleeName = name
					break
				}
			}
		}
		if calleeName == "" {
			calleeName = ex.Method
		}

		fnSig := e.funcSigs[calleeName]
		if fnSig != nil && len(fnSig.ReturnTypes) > 0 {
			return e.wolfTypeToLLVM(fnSig.ReturnTypes[0])
		}
		return "ptr"
	case *ir.StaticCall:
		// Convert Wolf_Math::Abs or math.abs to generic names
		cfunc := strings.ToLower(fmt.Sprintf("%s_%s", ex.Class, ex.Method))
		switch cfunc {
		case "wolf_math_abs", "wolf_math_ceil", "wolf_math_floor", "wolf_math_max", "wolf_math_min", "math_abs", "math_ceil", "math_floor", "math_max", "math_min",
			"wolf_math_sin", "wolf_math_cos", "wolf_math_tan", "wolf_math_asin", "wolf_math_acos", "wolf_math_atan", "wolf_math_atan2",
			"wolf_math_sqrt", "wolf_math_pow", "wolf_math_log", "wolf_math_log10", "wolf_math_exp",
			"wolf_math_round", "wolf_math_fmod", "wolf_math_pi",
			"math_sin", "math_cos", "math_tan", "math_asin", "math_acos", "math_atan", "math_atan2",
			"math_sqrt", "math_pow", "math_log", "math_log10", "math_exp",
			"math_round", "math_fmod", "math_pi":
			return "double"
		case "wolf_math_random", "math_random", "db_execute", "db_row_count", "db_last_insert_id", "wolf_array_length":
			return "i64"
		case "wolf_number_format":
			return "ptr"
		case "wolf_json_encode", "wolf_json_decode", "wolf_strings_upper", "wolf_strings_join", "wolf_strings_replace":
			return "ptr"
		case "wolf_strings_contains", "wolf_env_has":
			return "i1"
		case "db_connect", "db_prepare", "db_fetch_all", "db_fetch_one":
			return "ptr"
		}
		return "ptr"
	case *ir.Ident:
		if t, ok := e.varTypes[ex.Name]; ok {
			return t
		}
		return "ptr"
	default:
		return "ptr"
	}
}

func (e *LLVMEmitter) emitExprStmt(s *ir.ExprStmt) {
	switch expr := s.Expr.(type) {
	case *ir.CallExpr:
		e.emitCallExpr(expr)
	case *ir.MethodCallExpr:
		e.emitMethodCall(expr)
	default:
		e.emitExpr(s.Expr, "")
	}
}

func (e *LLVMEmitter) emitReturn(s *ir.ReturnStmt) {
	if len(s.Values) == 0 {
		e.writelnIndent("ret void")
	} else {
		llType := e.inferExprType(s.Values[0])
		val := e.emitExpr(s.Values[0], llType)

		// If the function explicitly or implicitly returns ptr, coerce mismatching types
		if e.currentRetType == "ptr" {
			if llType == "i1" {
				casted := e.nextLocal()
				e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_bool_to_string(i1 %s)", casted, val))
				val = casted
				llType = "ptr"
			} else if llType == "i64" {
				casted := e.nextLocal()
				e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_int_to_string(i64 %s)", casted, val))
				val = casted
				llType = "ptr"
			} else if llType == "double" {
				casted := e.nextLocal()
				e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_float_to_string(double %s)", casted, val))
				val = casted
				llType = "ptr"
			}
		}

		e.writelnIndent(fmt.Sprintf("ret %s %s", llType, val))
	}
}

// ========== FIX: coerceToBool ==========
// coerceToBool guarantees the returned register is i1.
// Must be called on every branch condition before emitting br i1.
// Uses emittedTypes map as ground truth — inferExprType can be wrong
// when varTypes shadows the actual call return type (e.g. wolf_password_verify
// returns i1 but varTypes["token"] = "ptr" causes inferExprType to return "ptr").
func (e *LLVMEmitter) coerceToBool(val string, hintType string) string {
	// Use actual emitted type if tracked, otherwise fall back to hint
	actualType := hintType
	if tracked, ok := e.emittedTypes[val]; ok {
		actualType = tracked
	}
	switch actualType {
	case "i1":
		return val
	case "i64":
		casted := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = icmp ne i64 %s, 0", casted, val))
		return casted
	case "double":
		casted := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = fcmp one double %s, 0.0", casted, val))
		return casted
	default: // "ptr" or anything unexpected — treat as pointer truthiness
		casted := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call i1 @wolf_boolval(ptr %s)", casted, val))
		return casted
	}
}

// ========== FIX: emitIf — uses coerceToBool for all branch conditions ==========
func (e *LLVMEmitter) emitIf(s *ir.IfStmt) {
	condType := e.inferExprType(s.Condition)
	condVal := e.emitExpr(s.Condition, condType)
	condVal = e.coerceToBool(condVal, condType) // FIX: guaranteed i1

	thenLabel := e.nextLabel("if.then")
	hasElseIfs := len(s.ElseIfs) > 0
	hasElse := s.ElseBody != nil
	endLabel := e.nextLabel("if.end")

	nextLabel := endLabel
	if hasElseIfs {
		nextLabel = e.nextLabel("if.elseif.cond")
	} else if hasElse {
		nextLabel = e.nextLabel("if.else")
	}

	e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", condVal, thenLabel, nextLabel))

	// Then block
	e.writeln(fmt.Sprintf("%s:", thenLabel))
	for _, stmt := range s.Body {
		e.emitStmt(stmt)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))

	// Else If blocks
	for i, elif := range s.ElseIfs {
		e.writeln(fmt.Sprintf("%s:", nextLabel))
		// FIX: elseif conditions also go through coerceToBool
		elifCondType := e.inferExprType(elif.Condition)
		elifCondVal := e.emitExpr(elif.Condition, elifCondType)
		elifCondVal = e.coerceToBool(elifCondVal, elifCondType)

		elifThenLabel := e.nextLabel("if.elseif.then")

		if i < len(s.ElseIfs)-1 {
			nextLabel = e.nextLabel("if.elseif.cond")
		} else if hasElse {
			nextLabel = e.nextLabel("if.else")
		} else {
			nextLabel = endLabel
		}

		e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", elifCondVal, elifThenLabel, nextLabel))

		// ElseIf Then block
		e.writeln(fmt.Sprintf("%s:", elifThenLabel))
		for _, stmt := range elif.Body {
			e.emitStmt(stmt)
		}
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
	}

	// Else block
	if hasElse {
		e.writeln(fmt.Sprintf("%s:", nextLabel))
		for _, stmt := range s.ElseBody {
			e.emitStmt(stmt)
		}
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
	}

	// End
	e.writeln(fmt.Sprintf("%s:", endLabel))
}

// ========== FIX: emitFor — uses coerceToBool for loop condition ==========
func (e *LLVMEmitter) emitFor(s *ir.ForStmt) {
	condLabel := e.nextLabel("for.cond")
	bodyLabel := e.nextLabel("for.body")
	updateLabel := e.nextLabel("for.update")
	endLabel := e.nextLabel("for.end")

	// Init
	if s.Init != nil {
		e.emitStmt(s.Init)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))

	// Condition
	e.writeln(fmt.Sprintf("%s:", condLabel))
	if s.Cond != nil {
		// FIX: for loop conditions also go through coerceToBool
		forCondType := e.inferExprType(s.Cond)
		condVal := e.emitExpr(s.Cond, forCondType)
		condVal = e.coerceToBool(condVal, forCondType)
		e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", condVal, bodyLabel, endLabel))
	} else {
		e.writelnIndent(fmt.Sprintf("br label %%%s", bodyLabel))
	}

	// Body
	e.writeln(fmt.Sprintf("%s:", bodyLabel))
	for _, stmt := range s.Body {
		e.emitStmt(stmt)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", updateLabel))

	// Update
	e.writeln(fmt.Sprintf("%s:", updateLabel))
	if s.Update != nil {
		e.emitStmt(s.Update)
	}
	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))

	// End
	e.writeln(fmt.Sprintf("%s:", endLabel))
}

func (e *LLVMEmitter) emitRange(s *ir.RangeStmt) {
	arrVal := e.emitExpr(s.Iterable, "ptr")

	// Get length
	lenReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_array_length(ptr %s)", lenReg, arrVal))

	// Loop counter setup
	idxPtr := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = alloca i64", idxPtr))
	e.writelnIndent(fmt.Sprintf("store i64 0, ptr %s", idxPtr))

	condLabel := e.nextLabel("range.cond")
	bodyLabel := e.nextLabel("range.body")
	endLabel := e.nextLabel("range.end")

	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))
	e.writeln(fmt.Sprintf("%s:", condLabel))

	idxVal := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = load i64, ptr %s", idxVal, idxPtr))

	cmpReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = icmp slt i64 %s, %s", cmpReg, idxVal, lenReg))
	e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", cmpReg, bodyLabel, endLabel))

	e.writeln(fmt.Sprintf("%s:", bodyLabel))

	// Assign value
	if s.Value != "" && s.Value != "_" {
		valReg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_array_get(ptr %s, i64 %s)", valReg, arrVal, idxVal))
		e.writelnIndent(fmt.Sprintf("store ptr %s, ptr %%%s", valReg, s.Value))
	}

	// Assign key
	if s.Key != "" && s.Key != "_" {
		e.writelnIndent(fmt.Sprintf("store i64 %s, ptr %%%s", idxVal, s.Key))
	}

	for _, stmt := range s.Body {
		e.emitStmt(stmt)
	}

	// Update loop counter
	nextIdx := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = add i64 %s, 1", nextIdx, idxVal))
	e.writelnIndent(fmt.Sprintf("store i64 %s, ptr %s", nextIdx, idxPtr))
	e.writelnIndent(fmt.Sprintf("br label %%%s", condLabel))

	e.writeln(fmt.Sprintf("%s:", endLabel))
}

func (e *LLVMEmitter) emitSwitch(s *ir.SwitchStmt) {
	subjType := e.inferExprType(s.Subject)
	if subjType == "" {
		subjType = "i64"
	}
	subjVal := e.emitExpr(s.Subject, subjType)
	endLabel := e.nextLabel("match.end")

	var nextCondLabel string
	if len(s.Cases) > 0 {
		nextCondLabel = e.nextLabel("match.case.cond")
		e.writelnIndent(fmt.Sprintf("br label %%%s", nextCondLabel))
	} else if len(s.Default) > 0 {
		nextCondLabel = e.nextLabel("match.default")
		e.writelnIndent(fmt.Sprintf("br label %%%s", nextCondLabel))
	} else {
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
		e.writeln(fmt.Sprintf("%s:", endLabel))
		return
	}

	for i, c := range s.Cases {
		e.writeln(fmt.Sprintf("%s:", nextCondLabel))

		caseVal := e.emitExpr(c.Value, subjType)
		cmpReg := e.nextLocal()

		// Note: Using integer/pointer naive equality for now. Strings would need strcmp.
		e.writelnIndent(fmt.Sprintf("%s = icmp eq %s %s, %s", cmpReg, subjType, subjVal, caseVal))

		caseBodyLabel := e.nextLabel("match.case.body")

		if i < len(s.Cases)-1 {
			nextCondLabel = e.nextLabel("match.case.cond")
		} else if len(s.Default) > 0 {
			nextCondLabel = e.nextLabel("match.default")
		} else {
			nextCondLabel = endLabel
		}

		e.writelnIndent(fmt.Sprintf("br i1 %s, label %%%s, label %%%s", cmpReg, caseBodyLabel, nextCondLabel))

		e.writeln(fmt.Sprintf("%s:", caseBodyLabel))
		for _, stmt := range c.Body {
			e.emitStmt(stmt)
		}
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
	}

	if len(s.Default) > 0 {
		e.writeln(fmt.Sprintf("%s:", nextCondLabel))
		for _, stmt := range s.Default {
			e.emitStmt(stmt)
		}
		e.writelnIndent(fmt.Sprintf("br label %%%s", endLabel))
	}

	e.writeln(fmt.Sprintf("%s:", endLabel))
}

// ========== Expression Emission ==========

// emitExpr emits LLVM IR for an expression and returns the register/value name.
func (e *LLVMEmitter) emitExpr(expr ir.Expr, expectedType string) string {
	switch ex := expr.(type) {
	case *ir.IntLit:
		return ex.Value
	case *ir.FloatLit:
		return ex.Value
	case *ir.BoolLit:
		if ex.Value {
			return "1"
		}
		return "0"
	case *ir.NilLit:
		return "null"
	case *ir.StringLit:
		label := e.addStringConst(ex.Value)
		reg := e.nextLocal()
		byteLen := len(ex.Value) + 1
		e.writelnIndent(fmt.Sprintf("%s = getelementptr [%d x i8], ptr %s, i64 0, i64 0", reg, byteLen, label))
		return reg
	case *ir.Ident:
		// Check if it's a known function (function pointer)
		if _, isFunc := e.funcSigs[ex.Name]; isFunc {
			fullFuncName := ex.Name
			if !strings.HasPrefix(fullFuncName, "wolf_") {
				fullFuncName = "wolf_" + fullFuncName
			}
			return "@" + fullFuncName
		}

		loadType := "ptr"
		if t, ok := e.varTypes[ex.Name]; ok {
			loadType = t
		}
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = load %s, ptr %%%s", reg, loadType, ex.Name))
		return reg
	case *ir.FieldAccess:
		objVal := e.emitExpr(ex.Object, "ptr")
		keyLabel := e.addStringConst(ex.Field)
		keyReg := e.nextLocal()
		byteLen := len(ex.Field) + 1
		e.writelnIndent(fmt.Sprintf("%s = getelementptr [%d x i8], ptr %s, i64 0, i64 0", keyReg, byteLen, keyLabel))
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_map_get(ptr %s, ptr %s)", reg, objVal, keyReg))
		return reg
	case *ir.BinaryExpr:
		return e.emitBinaryExpr(ex, expectedType)
	case *ir.UnaryExpr:
		return e.emitUnaryExpr(ex)
	case *ir.CallExpr:
		return e.emitCallExpr(ex)
	case *ir.MethodCallExpr:
		return e.emitMethodCall(ex)
	case *ir.StaticCall:
		return e.emitStaticCall(ex)
	case *ir.FmtSprintf:
		return e.emitFmtSprintf(ex)
	case *ir.StringConcat:
		return e.emitStringConcat(ex)
	case *ir.PostfixExpr:
		return e.emitPostfix(ex)
	case *ir.IndexExpr:
		return e.emitIndexExpr(ex)
	case *ir.SliceLit:
		return e.emitSliceLit(ex)
	case *ir.MapLit:
		return e.emitMapLit(ex)
	default:
		e.writelnIndent(fmt.Sprintf("; TODO: unhandled expr type %T", expr))
		return "null"
	}
}

func (e *LLVMEmitter) emitIndexExpr(ex *ir.IndexExpr) string {
	objVal := e.emitExpr(ex.Object, "ptr")
	idxType := e.inferExprType(ex.Index)
	idxVal := e.emitExpr(ex.Index, idxType)
	reg := e.nextLocal()

	if idxType == "i64" {
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_array_get(ptr %s, i64 %s)", reg, objVal, idxVal))
	} else {
		// Default to map_get if the index parameter is not a pure integer
		if idxType != "ptr" {
			stringPtr := e.emitArgAsString(ex.Index)
			idxVal = stringPtr
		}
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_map_get(ptr %s, ptr %s)", reg, objVal, idxVal))
	}
	return reg
}

func (e *LLVMEmitter) emitSliceLit(ex *ir.SliceLit) string {
	arrReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_array_create()", arrReg))
	for _, elem := range ex.Elements {
		elemType := e.inferExprType(elem)
		switch elemType {
		case "i64":
			intVal := e.emitExpr(elem, "i64")
			reg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_val_int(i64 %s)", reg, intVal))
			e.writelnIndent(fmt.Sprintf("call void @wolf_array_push(ptr %s, ptr %s)", arrReg, reg))
		case "double":
			floatVal := e.emitExpr(elem, "double")
			reg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_val_float(double %s)", reg, floatVal))
			e.writelnIndent(fmt.Sprintf("call void @wolf_array_push(ptr %s, ptr %s)", arrReg, reg))
		case "i1":
			boolVal := e.emitExpr(elem, "i1")
			reg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_val_bool(i1 %s)", reg, boolVal))
			e.writelnIndent(fmt.Sprintf("call void @wolf_array_push(ptr %s, ptr %s)", arrReg, reg))
		default:
			elemVal := e.emitArgAsString(elem)
			e.writelnIndent(fmt.Sprintf("call void @wolf_array_push(ptr %s, ptr %s)", arrReg, elemVal))
		}
	}
	return arrReg
}

func (e *LLVMEmitter) emitMapLit(ex *ir.MapLit) string {
	mapReg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_map_create()", mapReg))
	for i := range ex.Keys {
		keyVal := e.emitArgAsString(ex.Keys[i])
		valType := e.inferExprType(ex.Values[i])
		switch valType {
		case "i64":
			intVal := e.emitExpr(ex.Values[i], "i64")
			e.writelnIndent(fmt.Sprintf("call void @wolf_map_set_int(ptr %s, ptr %s, i64 %s)", mapReg, keyVal, intVal))
		case "double":
			floatVal := e.emitExpr(ex.Values[i], "double")
			e.writelnIndent(fmt.Sprintf("call void @wolf_map_set_float(ptr %s, ptr %s, double %s)", mapReg, keyVal, floatVal))
		case "i1":
			boolVal := e.emitExpr(ex.Values[i], "i1")
			e.writelnIndent(fmt.Sprintf("call void @wolf_map_set_bool(ptr %s, ptr %s, i1 %s)", mapReg, keyVal, boolVal))
		default:
			valVal := e.emitArgAsString(ex.Values[i])
			e.writelnIndent(fmt.Sprintf("call void @wolf_map_set(ptr %s, ptr %s, ptr %s)", mapReg, keyVal, valVal))
		}
	}
	return mapReg
}

func (e *LLVMEmitter) emitBinaryExpr(ex *ir.BinaryExpr, expectedType string) string {
	leftType := e.inferExprType(ex.Left)
	rightType := e.inferExprType(ex.Right)

	if ex.Op == "+" && (leftType == "ptr" || rightType == "ptr") {
		leftVal := e.emitArgAsString(ex.Left)
		rightVal := e.emitArgAsString(ex.Right)
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_string_concat(ptr %s, ptr %s)", reg, leftVal, rightVal))
		return reg
	}

	commonType := "i64"
	if ex.Op == "&&" || ex.Op == "||" {
		commonType = "i1"
	} else if leftType == "double" || rightType == "double" {
		commonType = "double"
	} else if leftType == "ptr" || rightType == "ptr" {
		// If one side is actually an integer or bool, use i64 comparison not ptr/strcmp
		if leftType == "i64" || rightType == "i64" || leftType == "i1" || rightType == "i1" {
			commonType = "i64"
		} else {
			commonType = "ptr"
		}
	}

	left := e.emitExpr(ex.Left, commonType)
	right := e.emitExpr(ex.Right, commonType)
	reg := e.nextLocal()

	// Coerce i1 values to ptr when commonType is ptr
	// (e.g. wolf_password_verify returns i1 but is used in == / != string comparison)
	if commonType == "ptr" {
		if actual, ok := e.emittedTypes[left]; ok && actual == "i1" {
			casted := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_bool_to_string(i1 %s)", casted, left))
			left = casted
		}
		if actual, ok := e.emittedTypes[right]; ok && actual == "i1" {
			casted := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_bool_to_string(i1 %s)", casted, right))
			right = casted
		}
	}

	// Perform explicit casts if types don't match the required commonType
	if commonType == "i64" {
		if leftType == "ptr" {
			casted := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_intval(ptr %s)", casted, left))
			left = casted
		} else if leftType == "i1" {
			if _, isBoolLit := ex.Left.(*ir.BoolLit); !isBoolLit {
				casted := e.nextLocal()
				e.writelnIndent(fmt.Sprintf("%s = zext i1 %s to i64", casted, left))
				left = casted
			}
		}

		if rightType == "ptr" {
			casted := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_intval(ptr %s)", casted, right))
			right = casted
		} else if rightType == "i1" {
			if _, isBoolLit := ex.Right.(*ir.BoolLit); !isBoolLit {
				casted := e.nextLocal()
				e.writelnIndent(fmt.Sprintf("%s = zext i1 %s to i64", casted, right))
				right = casted
			}
		}
	}

	if commonType == "double" {
		switch ex.Op {
		case "+":
			e.writelnIndent(fmt.Sprintf("%s = fadd double %s, %s", reg, left, right))
		case "-":
			e.writelnIndent(fmt.Sprintf("%s = fsub double %s, %s", reg, left, right))
		case "*":
			e.writelnIndent(fmt.Sprintf("%s = fmul double %s, %s", reg, left, right))
		case "/":
			e.writelnIndent(fmt.Sprintf("%s = fdiv double %s, %s", reg, left, right))
		case "%":
			e.writelnIndent(fmt.Sprintf("%s = frem double %s, %s", reg, left, right))
		case "==":
			e.writelnIndent(fmt.Sprintf("%s = fcmp oeq double %s, %s", reg, left, right))
		case "!=":
			e.writelnIndent(fmt.Sprintf("%s = fcmp one double %s, %s", reg, left, right))
		case "<":
			e.writelnIndent(fmt.Sprintf("%s = fcmp olt double %s, %s", reg, left, right))
		case ">":
			e.writelnIndent(fmt.Sprintf("%s = fcmp ogt double %s, %s", reg, left, right))
		case "<=":
			e.writelnIndent(fmt.Sprintf("%s = fcmp ole double %s, %s", reg, left, right))
		case ">=":
			e.writelnIndent(fmt.Sprintf("%s = fcmp oge double %s, %s", reg, left, right))
		default:
			e.writelnIndent(fmt.Sprintf("; unknown binary op for double: %s", ex.Op))
			return "0.0"
		}
	} else if commonType == "ptr" {
		switch ex.Op {
		case "==":
			cmpReg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_strcmp(ptr %s, ptr %s)", cmpReg, left, right))
			e.writelnIndent(fmt.Sprintf("%s = icmp eq i64 %s, 0", reg, cmpReg))
		case "!=":
			cmpReg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_strcmp(ptr %s, ptr %s)", cmpReg, left, right))
			e.writelnIndent(fmt.Sprintf("%s = icmp ne i64 %s, 0", reg, cmpReg))
		default:
			// For numeric comparisons on ptr, coerce both sides to i64 via wolf_intval
			if ex.Op == ">" || ex.Op == "<" || ex.Op == ">=" || ex.Op == "<=" || ex.Op == "-" {
				leftI := e.nextLocal()
				rightI := e.nextLocal()
				e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_intval(ptr %s)", leftI, left))
				e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_intval(ptr %s)", rightI, right))
				switch ex.Op {
				case ">":
					e.writelnIndent(fmt.Sprintf("%s = icmp sgt i64 %s, %s", reg, leftI, rightI))
				case "<":
					e.writelnIndent(fmt.Sprintf("%s = icmp slt i64 %s, %s", reg, leftI, rightI))
				case ">=":
					e.writelnIndent(fmt.Sprintf("%s = icmp sge i64 %s, %s", reg, leftI, rightI))
				case "<=":
					e.writelnIndent(fmt.Sprintf("%s = icmp sle i64 %s, %s", reg, leftI, rightI))
				case "-":
					e.writelnIndent(fmt.Sprintf("%s = sub i64 %s, %s", reg, leftI, rightI))
				}
			} else {
				e.writelnIndent(fmt.Sprintf("; unknown binary op for ptr: %s", ex.Op))
				return "null"
			}
		}
	} else if commonType == "i1" {
		switch ex.Op {
		case "&&":
			e.writelnIndent(fmt.Sprintf("%s = and i1 %s, %s", reg, left, right))
		case "||":
			e.writelnIndent(fmt.Sprintf("%s = or i1 %s, %s", reg, left, right))
		case "==":
			e.writelnIndent(fmt.Sprintf("%s = icmp eq i1 %s, %s", reg, left, right))
		case "!=":
			e.writelnIndent(fmt.Sprintf("%s = icmp ne i1 %s, %s", reg, left, right))
		default:
			e.writelnIndent(fmt.Sprintf("; unknown binary op for i1: %s", ex.Op))
			return "0"
		}
	} else {
		// commonType == "i64"
		switch ex.Op {
		case "+":
			e.writelnIndent(fmt.Sprintf("%s = add i64 %s, %s", reg, left, right))
		case "-":
			e.writelnIndent(fmt.Sprintf("%s = sub i64 %s, %s", reg, left, right))
		case "*":
			e.writelnIndent(fmt.Sprintf("%s = mul i64 %s, %s", reg, left, right))
		case "/":
			e.writelnIndent(fmt.Sprintf("%s = sdiv i64 %s, %s", reg, left, right))
		case "%":
			e.writelnIndent(fmt.Sprintf("%s = srem i64 %s, %s", reg, left, right))
		case "==":
			e.writelnIndent(fmt.Sprintf("%s = icmp eq i64 %s, %s", reg, left, right))
		case "!=":
			e.writelnIndent(fmt.Sprintf("%s = icmp ne i64 %s, %s", reg, left, right))
		case "<":
			e.writelnIndent(fmt.Sprintf("%s = icmp slt i64 %s, %s", reg, left, right))
		case ">":
			e.writelnIndent(fmt.Sprintf("%s = icmp sgt i64 %s, %s", reg, left, right))
		case "<=":
			e.writelnIndent(fmt.Sprintf("%s = icmp sle i64 %s, %s", reg, left, right))
		case ">=":
			e.writelnIndent(fmt.Sprintf("%s = icmp sge i64 %s, %s", reg, left, right))
		default:
			e.writelnIndent(fmt.Sprintf("; unknown binary op for i64: %s", ex.Op))
			return "0"
		}
	}
	return reg
}

func (e *LLVMEmitter) emitUnaryExpr(ex *ir.UnaryExpr) string {
	opType := e.inferExprType(ex.Operand)
	operand := e.emitExpr(ex.Operand, opType)
	reg := e.nextLocal()

	switch ex.Op {
	case "!":
		boolReg := e.coerceToBool(operand, opType)
		e.writelnIndent(fmt.Sprintf("%s = xor i1 %s, 1", reg, boolReg))
	case "-":
		if opType == "double" {
			e.writelnIndent(fmt.Sprintf("%s = fsub double 0.0, %s", reg, operand))
		} else {
			e.writelnIndent(fmt.Sprintf("%s = sub i64 0, %s", reg, operand))
		}
	default:
		e.writelnIndent(fmt.Sprintf("; unknown unary op: %s", ex.Op))
		return "0"
	}
	return reg
}

func (e *LLVMEmitter) emitCallExpr(call *ir.CallExpr) string {
	// Check for built-in print
	if ident, ok := call.Callee.(*ir.Ident); ok {
		switch ident.Name {
		case "fmt_Println", "fmt.Println", "wolf_print", "print":
			return e.emitPrintCall(call)
		}
	}

	var fnSig *ir.Function
	if ident, ok := call.Callee.(*ir.Ident); ok {
		fnSig = e.funcSigs[ident.Name]
	}

	var calleeName string
	if ident, ok := call.Callee.(*ir.Ident); ok {
		calleeName = ident.Name

		// Map global wolf functions to C runtime equivalents
		switch calleeName {
		case "say":
			calleeName = "wolf_say"
		case "show":
			calleeName = "wolf_show"
		case "inspect":
			calleeName = "wolf_inspect"
		case "time":
			calleeName = "wolf_time_now"
		case "date":
			calleeName = "wolf_time_date"
		case "strtotime":
			calleeName = "wolf_time_strtotime"
		case "sleep":
			calleeName = "wolf_system_sleep"
		case "exit":
			calleeName = "wolf_system_exit"
		case "die":
			calleeName = "wolf_system_die"
		case "argc":
			calleeName = "wolf_argc"
		case "argv":
			calleeName = "wolf_argv"
		case "env":
			calleeName = "wolf_env_get"
		case "session_begin":
			calleeName = "wolf_session_begin"
		case "session_set":
			calleeName = "wolf_session_set"
		case "session_get":
			calleeName = "wolf_session_get"
		case "session_end":
			calleeName = "wolf_session_end"
		case "define":
			calleeName = "wolf_define"
		case "defined":
			calleeName = "wolf_defined"
		case "define_get":
			calleeName = "wolf_define_get"
		case "number_format":
			calleeName = "wolf_number_format"

		// --- Database (Mock) ---
		case "db_connect":
			calleeName = "wolf_db_connect"
		case "db_prepare":
			calleeName = "wolf_db_prepare"
		case "db_bind":
			calleeName = "wolf_db_bind"
		case "db_execute":
			calleeName = "wolf_db_execute"
		case "db_fetch_all":
			calleeName = "wolf_db_fetch_all"
		case "db_fetch_one":
			calleeName = "wolf_db_fetch_one"
		case "db_row_count":
			calleeName = "wolf_db_row_count"
		case "db_last_insert_id":
			calleeName = "wolf_db_last_insert_id"
		case "db_close":
			calleeName = "wolf_db_close"
		case "db_begin_transaction":
			calleeName = "wolf_db_begin_transaction"
		case "db_commit":
			calleeName = "wolf_db_commit"
		case "db_rollback":
			calleeName = "wolf_db_rollback"

		// --- Math globals (both sin(x) and math.sin(x) work) ---
		case "sin":
			calleeName = "wolf_math_sin"
		case "cos":
			calleeName = "wolf_math_cos"
		case "tan":
			calleeName = "wolf_math_tan"
		case "asin":
			calleeName = "wolf_math_asin"
		case "acos":
			calleeName = "wolf_math_acos"
		case "atan":
			calleeName = "wolf_math_atan"
		case "atan2":
			calleeName = "wolf_math_atan2"
		case "sqrt":
			calleeName = "wolf_math_sqrt"
		case "pow":
			calleeName = "wolf_math_pow"
		case "log":
			calleeName = "wolf_math_log"
		case "log10":
			calleeName = "wolf_math_log10"
		case "exp":
			calleeName = "wolf_math_exp"
		case "round":
			calleeName = "wolf_math_round"
		case "ceil":
			calleeName = "wolf_math_ceil"
		case "floor":
			calleeName = "wolf_math_floor"
		case "abs":
			calleeName = "wolf_math_abs"
		case "fmod":
			calleeName = "wolf_math_fmod"
		case "pi":
			calleeName = "wolf_math_pi"
		case "min":
			calleeName = "wolf_math_min"
		case "max":
			calleeName = "wolf_math_max"
		case "rand":
			calleeName = "wolf_math_random"
		case "deg2rad":
			calleeName = "wolf_deg2rad"
		case "rad2deg":
			calleeName = "wolf_rad2deg"
		case "clamp":
			calleeName = "wolf_clamp"
		case "rand_float":
			calleeName = "wolf_rand_float"
		case "rand_secure":
			calleeName = "wolf_rand_secure"
		case "math_inf", "INF":
			calleeName = "wolf_math_inf"
		case "math_nan", "NAN":
			calleeName = "wolf_math_nan"
		case "is_nan":
			calleeName = "wolf_is_nan"
		case "is_inf":
			calleeName = "wolf_is_inf"
		case "is_finite":
			calleeName = "wolf_is_finite"
		case "log_base":
			calleeName = "wolf_math_log_base"
		case "hypot":
			calleeName = "wolf_math_hypot"

		// --- Strings ---
		case "strlen":
			calleeName = "wolf_string_length"
		case "strtoupper":
			calleeName = "wolf_strtoupper"
		case "strtolower":
			calleeName = "wolf_strtolower"
		case "ucfirst":
			calleeName = "wolf_ucfirst"
		case "ucwords":
			calleeName = "wolf_ucwords"
		case "lcfirst":
			calleeName = "wolf_lcfirst"
		case "trim":
			calleeName = "wolf_trim"
		case "ltrim":
			calleeName = "wolf_ltrim"
		case "rtrim":
			calleeName = "wolf_rtrim"
		case "str_contains":
			calleeName = "wolf_str_contains"
		case "str_starts_with":
			calleeName = "wolf_str_starts_with"
		case "str_ends_with":
			calleeName = "wolf_str_ends_with"
		case "str_replace":
			calleeName = "wolf_str_replace"
		case "str_repeat":
			calleeName = "wolf_str_repeat"
		case "str_pad":
			calleeName = "wolf_str_pad"
		case "explode":
			calleeName = "wolf_explode"
		case "implode":
			calleeName = "wolf_implode"
		case "substr":
			calleeName = "wolf_substr"
		case "strpos":
			calleeName = "wolf_strpos"
		case "strrpos":
			calleeName = "wolf_strrpos"
		case "sprintf":
			calleeName = "wolf_sprintf"
		case "str_word_count":
			calleeName = "wolf_str_word_count"
		case "nl2br":
			calleeName = "wolf_nl2br"
		case "strip_tags":
			calleeName = "wolf_strip_tags"
		case "htmlspecialchars":
			calleeName = "wolf_htmlspecialchars"
		case "addslashes":
			calleeName = "wolf_addslashes"
		case "stripslashes":
			calleeName = "wolf_stripslashes"
		case "str_ireplace":
			calleeName = "wolf_str_ireplace"
		case "htmlspecialchars_decode":
			calleeName = "wolf_htmlspecialchars_decode"
		case "similar_text":
			calleeName = "wolf_similar_text"
		case "wordwrap":
			calleeName = "wolf_wordwrap"
		case "quoted_printable_encode":
			calleeName = "wolf_quoted_printable_encode"
		case "preg_match":
			calleeName = "wolf_preg_match"
		case "preg_match_captures":
			calleeName = "wolf_preg_match_captures"
		case "preg_match_all":
			calleeName = "wolf_preg_match_all"
		case "preg_replace":
			calleeName = "wolf_preg_replace"
		case "preg_split":
			calleeName = "wolf_preg_split"
		case "strcmp":
			calleeName = "wolf_strcmp"

		// --- Type Casting ---
		case "intval":
			calleeName = "wolf_intval"
		case "floatval":
			calleeName = "wolf_floatval"
		case "strval":
			calleeName = "wolf_strval"
		case "boolval":
			calleeName = "wolf_boolval"
		case "intdiv":
			calleeName = "wolf_intdiv"
		case "gettype":
			calleeName = "wolf_gettype"
		case "is_numeric":
			calleeName = "wolf_is_numeric"

		// --- Encoding ---
		case "base64_encode":
			calleeName = "wolf_base64_encode"
		case "base64_decode":
			calleeName = "wolf_base64_decode"
		case "url_encode":
			calleeName = "wolf_url_encode"
		case "url_decode":
			calleeName = "wolf_url_decode"
		case "json_encode":
			calleeName = "wolf_json_encode"
		case "json_decode":
			calleeName = "wolf_json_decode"
		case "json_pretty":
			calleeName = "wolf_json_pretty"

		// --- Security ---
		case "md5":
			calleeName = "wolf_md5"
		case "sha256":
			calleeName = "wolf_sha256"
		case "password_hash":
			calleeName = "wolf_password_hash"
		case "password_verify":
			calleeName = "wolf_password_verify"
		case "uuid_v4":
			calleeName = "wolf_uuid_v4"
		case "rand_hex":
			calleeName = "wolf_rand_hex"

		// --- Output ---
		case "dump":
			calleeName = "wolf_dump"
		case "dd":
			calleeName = "wolf_dd"
		case "log_info":
			calleeName = "wolf_log_info"
		case "log_warning":
			calleeName = "wolf_log_warning"
		case "log_error":
			calleeName = "wolf_log_error"

		// --- Arrays ---
		case "count":
			calleeName = "wolf_count"
		case "in_array":
			calleeName = "wolf_in_array"
		case "array_search":
			calleeName = "wolf_array_search"
		case "array_push":
			calleeName = "wolf_array_push"
		case "array_pop":
			calleeName = "wolf_array_pop"
		case "array_shift":
			calleeName = "wolf_array_shift"
		case "array_unshift":
			calleeName = "wolf_array_unshift"
		case "array_reverse":
			calleeName = "wolf_array_reverse"
		case "array_unique":
			calleeName = "wolf_array_unique"
		case "array_merge":
			calleeName = "wolf_array_merge"
		case "array_slice":
			calleeName = "wolf_array_slice"
		case "sort":
			calleeName = "wolf_sort"
		case "rsort":
			calleeName = "wolf_rsort"
		case "array_sum":
			calleeName = "wolf_array_sum"
		case "array_keys":
			calleeName = "wolf_array_keys"
		case "array_values":
			calleeName = "wolf_array_values"
		case "array_diff":
			calleeName = "wolf_array_diff"
		case "array_intersect":
			calleeName = "wolf_array_intersect"
		case "array_flip":
			calleeName = "wolf_array_flip"
		case "range":
			calleeName = "wolf_range"
		case "array_fill":
			calleeName = "wolf_array_fill"
		case "array_combine":
			calleeName = "wolf_array_combine"
		case "array_chunk":
			calleeName = "wolf_array_chunk"
		case "array_column":
			calleeName = "wolf_array_column"
		case "array_product":
			calleeName = "wolf_array_product"
		case "array_diff_key":
			calleeName = "wolf_array_diff_key"
		case "array_splice":
			calleeName = "wolf_array_splice"
		case "array_pad":
			calleeName = "wolf_array_pad"
		case "array_count_values":
			calleeName = "wolf_array_count_values"
		case "array_rand":
			calleeName = "wolf_array_rand_one"
		case "array_mean":
			calleeName = "wolf_array_mean"
		case "array_median":
			calleeName = "wolf_array_median"
		case "array_mode":
			calleeName = "wolf_array_mode"
		case "array_variance":
			calleeName = "wolf_array_variance"
		case "array_std_dev":
			calleeName = "wolf_array_std_dev"
		case "array_percentile":
			calleeName = "wolf_array_percentile"

		// --- Phase 3: Date/Time ---
		case "time_ms":
			calleeName = "wolf_time_ms"
		case "time_ns":
			calleeName = "wolf_time_ns"
		case "mktime":
			calleeName = "wolf_mktime"
		case "date_diff":
			calleeName = "wolf_date_diff"
		case "date_format":
			calleeName = "wolf_date_format"
		case "day_of_week":
			calleeName = "wolf_day_of_week"
		case "days_in_month":
			calleeName = "wolf_days_in_month"
		case "is_leap_year":
			calleeName = "wolf_is_leap_year"

		// --- Phase 3: Validation ---
		case "is_email":
			calleeName = "wolf_is_email"
		case "is_url":
			calleeName = "wolf_is_url"
		case "is_phone":
			calleeName = "wolf_is_phone"
		case "is_uuid":
			calleeName = "wolf_is_uuid"
		case "is_json":
			calleeName = "wolf_is_json"
		case "is_ip":
			calleeName = "wolf_is_ip"
		case "is_alpha":
			calleeName = "wolf_is_alpha"
		case "is_alpha_num":
			calleeName = "wolf_is_alpha_num"

		// --- Phase 3: File System ---
		case "file_exists":
			calleeName = "wolf_file_exists"
		case "file_read":
			calleeName = "wolf_file_read"
		case "file_write":
			calleeName = "wolf_file_write"
		case "file_append":
			calleeName = "wolf_file_append"
		case "file_delete":
			calleeName = "wolf_file_delete"
		case "file_size":
			calleeName = "wolf_file_size"
		case "file_extension":
			calleeName = "wolf_file_extension"
		case "file_basename":
			calleeName = "wolf_file_basename"
		case "file_dirname":
			calleeName = "wolf_file_dirname"
		case "dir_exists":
			calleeName = "wolf_dir_exists"

		// --- Phase 3: Utilities ---
		case "slug":
			calleeName = "wolf_slug"
		case "truncate":
			calleeName = "wolf_truncate"

		// --- Redis ---
		case "redis_connect":
			calleeName = "wolf_redis_connect"
		case "redis_set":
			calleeName = "wolf_redis_set"
		case "redis_get":
			calleeName = "wolf_redis_get"
		case "redis_del":
			calleeName = "wolf_redis_del"
		case "redis_exists":
			calleeName = "wolf_redis_exists"
		case "redis_hset":
			calleeName = "wolf_redis_hset"
		case "redis_hget":
			calleeName = "wolf_redis_hget"
		case "redis_close":
			calleeName = "wolf_redis_close"

		// --- Thread-Local Request Context ---
		case "wolf_get_request_body":
			calleeName = "wolf_get_request_body"
		case "wolf_get_request_header":
			calleeName = "wolf_get_request_header"
		case "wolf_get_request_method":
			calleeName = "wolf_get_request_method"
		case "wolf_get_request_path":
			calleeName = "wolf_get_request_path"
		case "wolf_set_current_context":
			calleeName = "wolf_set_current_context"
		case "input":
			calleeName = "wolf_input"
		case "http_response_code":
			calleeName = "wolf_http_response_code"
		case "wolf_http_write_response":
			calleeName = "wolf_http_write_response"

		// --- Sanitization ---
		case "sanitize_string":
			calleeName = "wolf_sanitize_string"
		case "sanitize_email":
			calleeName = "wolf_sanitize_email"
		case "sanitize_url":
			calleeName = "wolf_sanitize_url"
		case "sanitize_int":
			calleeName = "wolf_sanitize_int"
		case "sanitize_float":
			calleeName = "wolf_sanitize_float"

		// --- JWT ---
		case "sha512":
			calleeName = "wolf_sha512"
		case "hash":
			calleeName = "wolf_hash"
		case "hash_hmac":
			calleeName = "wolf_hash_hmac"
		case "hash_equals":
			calleeName = "wolf_hash_equals"
		case "password_needs_rehash":
			calleeName = "wolf_password_needs_rehash"
		case "encrypt":
			calleeName = "wolf_encrypt"
		case "decrypt":
			calleeName = "wolf_decrypt"
		case "rand_bytes":
			calleeName = "wolf_rand_bytes"
		case "rand_token":
			calleeName = "wolf_rand_token"
		case "uuid_v7":
			calleeName = "wolf_uuid_v7"
		case "nanoid":
			calleeName = "wolf_nanoid"
		case "custom_id":
			calleeName = "wolf_custom_id"
		case "base64_url_encode":
			calleeName = "wolf_base64_url_encode"
		case "base64_url_decode":
			calleeName = "wolf_base64_url_decode"
		case "hex_encode":
			calleeName = "wolf_hex_encode"
		case "hex_decode":
			calleeName = "wolf_hex_decode"
		case "jwt_encode":
			calleeName = "wolf_jwt_encode"
		case "jwt_decode":
			calleeName = "wolf_jwt_decode"
		case "jwt_decode_unverified":
			calleeName = "wolf_jwt_decode_unverified"
		case "jwt_expired":
			calleeName = "wolf_jwt_expired"
		case "curve25519_keypair":
			calleeName = "wolf_curve25519_keypair"
		case "curve25519_shared":
			calleeName = "wolf_curve25519_shared"
		case "sign":
			calleeName = "wolf_sign"
		case "verify":
			calleeName = "wolf_verify"
		default:
			// Prefix all other Wolf-defined global functions
			if calleeName != "" && !strings.HasPrefix(calleeName, "wolf_") {
				calleeName = "wolf_" + calleeName
			}
		}
	}

	args := make([]string, len(call.Args))
	for i, arg := range call.Args {
		expectedType := "ptr"
		if fnSig != nil && i < len(fnSig.Params) {
			expectedType = e.wolfTypeToLLVM(fnSig.Params[i].Type)
		} else if fnSig == nil {
			switch calleeName {
			case "wolf_system_sleep", "wolf_system_exit":
				expectedType = "i64"
			case "wolf_time_date":
				if i == 0 {
					expectedType = "ptr"
				}
				if i == 1 {
					expectedType = "i64"
				}
			case "wolf_argv":
				expectedType = "i64"
			case "wolf_http_serve", "wolf_http_req_method", "wolf_http_req_path", "wolf_http_req_query", "wolf_http_req_header", "wolf_http_req_body", "wolf_http_res_header", "wolf_http_res_status", "wolf_http_res_write",
				"wolf_http_req_file", "wolf_http_req_file_count":
				if i == 0 {
					expectedType = "i64" // the request/response ID or port is always i64
				} else if calleeName == "wolf_http_res_status" && i == 1 {
					expectedType = "i64" // status code
				} else {
					expectedType = "ptr"
				}
			case "wolf_redis_connect":
				if i == 1 {
					expectedType = "i64"
				} else {
					expectedType = "ptr"
				}
			case "wolf_redis_set":
				if i == 3 {
					expectedType = "i64"
				} else {
					expectedType = "ptr"
				}
			case "wolf_math_abs", "wolf_math_ceil", "wolf_math_floor", "wolf_math_round",
				"wolf_math_sin", "wolf_math_cos", "wolf_math_tan",
				"wolf_math_asin", "wolf_math_acos", "wolf_math_atan",
				"wolf_math_sqrt", "wolf_math_log", "wolf_math_log10", "wolf_math_exp":
				expectedType = "double"
			case "wolf_math_max", "wolf_math_min", "wolf_math_atan2", "wolf_math_pow", "wolf_math_fmod":
				expectedType = "double"
			case "wolf_math_random":
				expectedType = "i64"
			case "wolf_range":
				expectedType = "i64"
			case "wolf_array_slice":
				if i == 0 {
					expectedType = "ptr"
				} else {
					expectedType = "i64"
				}
			case "wolf_deg2rad", "wolf_rad2deg":
				expectedType = "double"
			case "wolf_rand_secure":
				expectedType = "i64"
			case "wolf_is_nan", "wolf_is_inf", "wolf_is_finite":
				expectedType = "double"
			case "wolf_math_log_base", "wolf_math_hypot":
				expectedType = "double"
			case "wolf_clamp":
				expectedType = "double"
			case "wolf_number_format":
				if i == 0 {
					expectedType = "double"
				} else if i == 1 {
					expectedType = "i64"
				} else {
					expectedType = "ptr"
				}
			case "wolf_http_response_code":
				expectedType = "i64"
			case "wolf_set_current_context":
				expectedType = "ptr"
			case "wolf_count", "wolf_array_length":
				expectedType = "ptr"
			case "wolf_str_repeat":
				if i == 0 {
					expectedType = "ptr"
				} else {
					expectedType = "i64"
				}
			case "wolf_substr":
				if i == 0 {
					expectedType = "ptr"
				} else {
					expectedType = "i64"
				}
			case "wolf_strpos", "wolf_strrpos":
				expectedType = "ptr"
			case "wolf_str_pad":
				if i == 1 {
					expectedType = "i64"
				} else {
					expectedType = "ptr"
				}
			case "wolf_mktime":
				expectedType = "i64"
			case "wolf_date_diff":
				expectedType = "i64"
			case "wolf_intdiv":
				expectedType = "i64"
			case "wolf_similar_text":
				expectedType = "ptr"
			case "wolf_wordwrap":
				if i == 0 {
					expectedType = "ptr"
				} else if i == 1 {
					expectedType = "i64"
				} else if i == 2 {
					expectedType = "ptr"
				} else if i == 3 {
					expectedType = "i1"
				}
			case "wolf_rand_hex", "wolf_rand_bytes", "wolf_nanoid":
				expectedType = "i64"
			case "wolf_array_fill":
				if i == 0 || i == 1 {
					expectedType = "i64"
				}
				if i == 2 {
					expectedType = "ptr"
				}
			case "wolf_array_chunk":
				if i == 0 {
					expectedType = "ptr"
				}
				if i == 1 {
					expectedType = "i64"
				}
			case "wolf_array_splice":
				if i == 0 {
					expectedType = "ptr"
				}
				if i == 1 || i == 2 {
					expectedType = "i64"
				}
			case "wolf_array_pad":
				if i == 0 {
					expectedType = "ptr"
				}
				if i == 1 {
					expectedType = "i64"
				}
				if i == 2 {
					expectedType = "ptr"
				}
			case "wolf_array_percentile":
				if i == 0 {
					expectedType = "ptr"
				}
				if i == 1 {
					expectedType = "double"
				}
			case "wolf_custom_id":
				if i == 0 {
					expectedType = "ptr"
				}
				if i == 1 {
					expectedType = "i64"
				}
			case "wolf_sprintf":
				expectedType = "ptr"
			}
		}
		var val string
		if expectedType == "ptr" {
			val = e.emitArgAsString(arg)
		} else {
			llType := e.inferExprType(arg)
			val = e.emitExpr(arg, expectedType)

			// Coerce ptr arguments to expected primitive type if necessary
			if llType == "ptr" {
				if expectedType == "i64" {
					casted := e.nextLocal()
					e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_intval(ptr %s)", casted, val))
					val = casted
				} else if expectedType == "double" {
					casted := e.nextLocal()
					e.writelnIndent(fmt.Sprintf("%s = call double @wolf_floatval(ptr %s)", casted, val))
					val = casted
				} else if expectedType == "i1" {
					casted := e.nextLocal()
					e.writelnIndent(fmt.Sprintf("%s = call i1 @wolf_boolval(ptr %s)", casted, val))
					val = casted
				}
			}
		}
		args[i] = fmt.Sprintf("%s %s", expectedType, val)
	}

	retType := "void"
	if fnSig != nil && len(fnSig.ReturnTypes) > 0 {
		retType = e.wolfTypeToLLVM(fnSig.ReturnTypes[0])
	} else if fnSig == nil {
		switch calleeName {
		case "wolf_say", "wolf_show", "wolf_inspect", "wolf_system_sleep", "wolf_system_exit", "wolf_system_die", "wolf_session_begin", "wolf_session_set", "wolf_session_end", "wolf_define",
			"wolf_dump", "wolf_dd", "wolf_log_info", "wolf_log_warning", "wolf_log_error",
			"wolf_redis_set", "wolf_redis_hset", "wolf_redis_close",
			"wolf_array_unshift", "wolf_sort", "wolf_rsort", "wolf_array_push":
			retType = "void"
		case "wolf_math_abs", "wolf_math_ceil", "wolf_math_floor", "wolf_math_max", "wolf_math_min",
			"wolf_math_sin", "wolf_math_cos", "wolf_math_tan",
			"wolf_math_asin", "wolf_math_acos", "wolf_math_atan", "wolf_math_atan2",
			"wolf_math_sqrt", "wolf_math_pow", "wolf_math_log", "wolf_math_log10", "wolf_math_exp",
			"wolf_math_round", "wolf_math_fmod", "wolf_math_pi",
			"wolf_deg2rad", "wolf_rad2deg", "wolf_clamp", "wolf_floatval",
			"wolf_rand_float", "wolf_math_inf", "wolf_math_nan",
			"wolf_math_log_base", "wolf_math_hypot",
			"wolf_array_sum", "wolf_similar_text":
			retType = "double"
		case "wolf_rand_secure":
			retType = "i64"
		case "wolf_is_nan", "wolf_is_inf", "wolf_is_finite":
			retType = "i1"
		case "wolf_time_now", "wolf_time_strtotime", "wolf_redis_del",
			"wolf_count", "wolf_array_search", "wolf_intval", "wolf_intdiv", "wolf_strpos", "wolf_strrpos", "wolf_str_word_count", "wolf_strcmp",
			"wolf_time_ms", "wolf_time_ns", "wolf_mktime", "wolf_date_diff", "wolf_day_of_week", "wolf_days_in_month",
			"wolf_strtotime", "wolf_file_size", "wolf_db_execute", "wolf_db_row_count", "wolf_db_last_insert_id", "wolf_math_random",
			"wolf_string_length", "wolf_array_length", "wolf_argc",
			"wolf_preg_match_all":
			retType = "i64"
		case "wolf_array_rand_one":
			retType = "i64"
		case "wolf_array_product", "wolf_array_mean", "wolf_array_median",
			"wolf_array_variance", "wolf_array_std_dev", "wolf_array_percentile":
			retType = "double"
		case "wolf_defined", "wolf_redis_exists",
			"wolf_str_contains", "wolf_str_starts_with", "wolf_str_ends_with",
			"wolf_boolval", "wolf_is_numeric", "wolf_password_verify",
			"wolf_password_needs_rehash", "wolf_hash_equals",
			"wolf_jwt_expired", "wolf_verify",
			"wolf_in_array",
			"wolf_is_email", "wolf_is_url", "wolf_is_phone", "wolf_is_uuid", "wolf_is_json",
			"wolf_is_ip", "wolf_is_alpha", "wolf_is_alpha_num", "wolf_is_leap_year",
			"wolf_file_exists", "wolf_file_write", "wolf_file_append", "wolf_file_delete", "wolf_dir_exists",
			"wolf_preg_match":
			retType = "i1"
		default:
			retType = "ptr" // Call to unknown func (e.g. external) typically returns ptr
		}
	}

	reg := e.nextLocal()
	callParams := ""
	if calleeName == "wolf_sprintf" {
		callParams = "(ptr, ...)"
	}

	if retType == "void" {
		if callParams != "" {
			e.writelnIndent(fmt.Sprintf("call void %s @%s(%s)", callParams, calleeName, strings.Join(args, ", ")))
		} else {
			e.writelnIndent(fmt.Sprintf("call void @%s(%s)", calleeName, strings.Join(args, ", ")))
		}
		return "null" // return null as dummy
	}

	if callParams != "" {
		e.writelnIndent(fmt.Sprintf("%s = call %s %s @%s(%s)", reg, retType, callParams, calleeName, strings.Join(args, ", ")))
	} else {
		e.writelnIndent(fmt.Sprintf("%s = call %s @%s(%s)", reg, retType, calleeName, strings.Join(args, ", ")))
	}
	e.emittedTypes[reg] = retType
	return reg
}

func (e *LLVMEmitter) emitPrintCall(call *ir.CallExpr) string {
	for i, arg := range call.Args {
		// Add space between arguments (like Go's fmt.Println)
		if i > 0 {
			spaceLabel := e.addStringConst(" ")
			spaceReg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = getelementptr [2 x i8], ptr %s, i64 0, i64 0", spaceReg, spaceLabel))
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", spaceReg))
		}

		switch ex := arg.(type) {
		case *ir.StringLit:
			val := e.emitExpr(arg, "ptr")
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		case *ir.IntLit:
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_int(i64 %s)", ex.Value))
		case *ir.FloatLit:
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_float(double %s)", ex.Value))
		case *ir.BoolLit:
			val := "0"
			if ex.Value {
				val = "1"
			}
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_bool(i1 %s)", val))
		case *ir.NilLit:
			e.writelnIndent("call void @wolf_print_nil()")
		case *ir.FmtSprintf:
			val := e.emitFmtSprintf(ex)
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		default:
			// For all other types, convert to string using emitArgAsString and print as string
			val := e.emitArgAsString(arg)
			e.writelnIndent(fmt.Sprintf("call void @wolf_print_str(ptr %s)", val))
		}
	}

	// Newline at end
	e.writelnIndent("call void @wolf_println()")
	return "0"
}

func (e *LLVMEmitter) emitFmtSprintf(ex *ir.FmtSprintf) string {
	// For string interpolation: build the result by concatenating parts
	// The FmtSprintf has a Go-style format string and args.
	// We'll decompose it into concat calls.

	// Simple approach: emit each arg as a string, then concat them all
	parts := make([]string, 0)

	// Split the format string by %v and emit literal parts + args
	fmtStr := ex.Format
	argIdx := 0
	lastIdx := 0

	for i := 0; i < len(fmtStr)-1; i++ {
		if fmtStr[i] == '%' && fmtStr[i+1] == 'v' {
			// Emit literal part before %v
			if i > lastIdx {
				literal := fmtStr[lastIdx:i]
				val := e.emitExpr(&ir.StringLit{Value: literal}, "ptr")
				parts = append(parts, val)
			}
			// Emit the arg converted to string
			if argIdx < len(ex.Args) {
				argVal := e.emitArgAsString(ex.Args[argIdx])
				parts = append(parts, argVal)
				argIdx++
			}
			lastIdx = i + 2
			i++ // skip 'v'
		}
	}
	// Emit trailing literal
	if lastIdx < len(fmtStr) {
		literal := fmtStr[lastIdx:]
		val := e.emitExpr(&ir.StringLit{Value: literal}, "ptr")
		parts = append(parts, val)
	}

	// Concatenate all parts
	if len(parts) == 0 {
		return e.emitExpr(&ir.StringLit{Value: ""}, "ptr")
	}
	result := parts[0]
	for i := 1; i < len(parts); i++ {
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_string_concat(ptr %s, ptr %s)", reg, result, parts[i]))
		result = reg
	}
	return result
}

func (e *LLVMEmitter) emitArgAsString(arg ir.Expr) string {
	switch ex := arg.(type) {
	case *ir.StringLit:
		return e.emitExpr(ex, "ptr")
	case *ir.IntLit:
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_int_to_string(i64 %s)", reg, ex.Value))
		return reg
	case *ir.FloatLit:
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_float_to_string(double %s)", reg, ex.Value))
		return reg
	case *ir.BoolLit:
		val := "0"
		if ex.Value {
			val = "1"
		}
		reg := e.nextLocal()
		e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_bool_to_string(i1 %s)", reg, val))
		return reg
	default:
		llType := e.inferExprType(arg)
		val := e.emitExpr(arg, llType)

		switch llType {
		case "i64":
			reg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_int_to_string(i64 %s)", reg, val))
			return reg
		case "double":
			reg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_float_to_string(double %s)", reg, val))
			return reg
		case "i1":
			reg := e.nextLocal()
			e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_bool_to_string(i1 %s)", reg, val))
			return reg
		default:
			return val
		}
	}
}

func (e *LLVMEmitter) emitStringConcat(ex *ir.StringConcat) string {
	left := e.emitArgAsString(ex.Left)
	right := e.emitArgAsString(ex.Right)
	reg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call ptr @wolf_string_concat(ptr %s, ptr %s)", reg, left, right))
	return reg
}

func (e *LLVMEmitter) emitPostfix(ex *ir.PostfixExpr) string {
	ident, ok := ex.Operand.(*ir.Ident)
	if !ok {
		e.writelnIndent(fmt.Sprintf("; TODO: postfix on non-ident %T", ex.Operand))
		return "null"
	}

	llType := e.inferExprType(ex.Operand)
	val := e.emitExpr(ex.Operand, llType)
	reg := e.nextLocal()

	switch ex.Op {
	case "++":
		if llType == "double" {
			e.writelnIndent(fmt.Sprintf("%s = fadd double %s, 1.0", reg, val))
		} else {
			e.writelnIndent(fmt.Sprintf("%s = add i64 %s, 1", reg, val))
		}
	case "--":
		if llType == "double" {
			e.writelnIndent(fmt.Sprintf("%s = fsub double %s, 1.0", reg, val))
		} else {
			e.writelnIndent(fmt.Sprintf("%s = sub i64 %s, 1", reg, val))
		}
	default:
		e.writelnIndent(fmt.Sprintf("; unknown postfix op: %s", ex.Op))
		return "null"
	}

	e.writelnIndent(fmt.Sprintf("store %s %s, ptr %%%s", llType, reg, ident.Name))
	return reg
}

func (e *LLVMEmitter) emitMethodCall(mc *ir.MethodCallExpr) string {
	objVal := e.emitExpr(mc.Object, "ptr")

	var calleeName string
	expectedArgs := len(mc.Args) + 1 // +1 for explicit 'this'
	for name, sig := range e.funcSigs {
		if strings.HasSuffix(name, "_"+mc.Method) {
			if len(sig.Params) == expectedArgs {
				calleeName = name
				break
			}
		}
	}
	if calleeName == "" {
		calleeName = mc.Method
	}

	fnSig := e.funcSigs[calleeName]

	args := []string{fmt.Sprintf("ptr %s", objVal)}
	for i, arg := range mc.Args {
		expectedType := "ptr"
		if fnSig != nil && i+1 < len(fnSig.Params) {
			expectedType = e.wolfTypeToLLVM(fnSig.Params[i+1].Type)
		}
		var val string
		if expectedType == "ptr" {
			val = e.emitArgAsString(arg)
		} else {
			llType := e.inferExprType(arg)
			val = e.emitExpr(arg, expectedType)

			// Coerce ptr arguments to expected primitive type if necessary
			if llType == "ptr" {
				if expectedType == "i64" {
					casted := e.nextLocal()
					e.writelnIndent(fmt.Sprintf("%s = call i64 @wolf_intval(ptr %s)", casted, val))
					val = casted
				} else if expectedType == "double" {
					casted := e.nextLocal()
					e.writelnIndent(fmt.Sprintf("%s = call double @wolf_floatval(ptr %s)", casted, val))
					val = casted
				} else if expectedType == "i1" {
					casted := e.nextLocal()
					e.writelnIndent(fmt.Sprintf("%s = call i1 @wolf_boolval(ptr %s)", casted, val))
					val = casted
				}
			}
		}
		args = append(args, fmt.Sprintf("%s %s", expectedType, val))
	}

	retType := "ptr"
	if fnSig != nil && len(fnSig.ReturnTypes) > 0 {
		retType = e.wolfTypeToLLVM(fnSig.ReturnTypes[0])
	} else if fnSig == nil {
		retType = "ptr"
	}

	emitName := calleeName
	if fnSig != nil && !strings.HasPrefix(emitName, "wolf_") {
		emitName = "wolf_" + emitName
	}

	reg := e.nextLocal()
	if retType == "void" {
		e.writelnIndent(fmt.Sprintf("call void @%s(%s)", emitName, strings.Join(args, ", ")))
		return "null"
	}

	e.writelnIndent(fmt.Sprintf("%s = call %s @%s(%s)", reg, retType, emitName, strings.Join(args, ", ")))
	e.emittedTypes[reg] = retType
	return reg
}

func (e *LLVMEmitter) emitStaticCall(sc *ir.StaticCall) string {
	// Standardize names: Wolf_Math::Abs or math.abs -> wolf_math_abs
	calleeName := strings.ToLower(fmt.Sprintf("%s_%s", sc.Class, sc.Method))

	switch strings.ToLower(sc.Class) {
	case "math", "wolf_math":
		calleeName = strings.ToLower(fmt.Sprintf("wolf_math_%s", sc.Method))
	case "json", "wolf_json":
		calleeName = strings.ToLower(fmt.Sprintf("wolf_json_%s", sc.Method))
	case "strings", "wolf_strings":
		calleeName = strings.ToLower(fmt.Sprintf("wolf_strings_%s", sc.Method))
	}

	args := make([]string, len(sc.Args))
	for i, arg := range sc.Args {
		llType := e.inferExprType(arg)
		val := e.emitExpr(arg, llType)
		args[i] = fmt.Sprintf("%s %s", llType, val)
	}

	retType := e.inferExprType(sc)
	reg := e.nextLocal()
	e.writelnIndent(fmt.Sprintf("%s = call %s @%s(%s)", reg, retType, calleeName, strings.Join(args, ", ")))
	return reg
}

// ========== Type Mapping ==========

func (e *LLVMEmitter) wolfTypeToLLVM(wolfType string) string {
	switch wolfType {
	case "int", "int64", "i64":
		return "i64"
	case "float", "float64", "double":
		return "double"
	case "bool", "i1":
		return "i1"
	case "string", "ptr", "":
		return "ptr"
	case "void":
		return "void"
	default:
		return "ptr" // Default to pointer for complex types
	}
}

// ========== Output Helpers ==========

func (e *LLVMEmitter) writeln(s string) {
	e.buf.WriteString(s)
	e.buf.WriteByte('\n')
}

func (e *LLVMEmitter) writelnIndent(s string) {
	for i := 0; i < e.indent; i++ {
		e.buf.WriteString("  ")
	}
	e.buf.WriteString(s)
	e.buf.WriteByte('\n')
}
