; Wolf Language — LLVM IR Output
; Generated by wolf compiler

target triple = "x86_64-pc-linux-gnu"

; --- String Constants ---
@.str.1 = private unnamed_addr constant [5 x i8] c"POST\00"
@.str.4 = private unnamed_addr constant [1 x i8] c"\00"
@.str.6 = private unnamed_addr constant [5 x i8] c"name\00"
@.str.7 = private unnamed_addr constant [5 x i8] c"size\00"
@.str.11 = private unnamed_addr constant [22 x i8] c"{\22error\22:\22not found\22}\00"
@.str.13 = private unnamed_addr constant [11 x i8] c"Dummy Data\00"
@.str.2 = private unnamed_addr constant [8 x i8] c"/upload\00"
@.str.3 = private unnamed_addr constant [7 x i8] c"avatar\00"
@.str.5 = private unnamed_addr constant [20 x i8] c"{\22error\22:\22no file\22}\00"
@.str.8 = private unnamed_addr constant [26 x i8] c"{\22received\22:true,\22name\22:\22\00"
@.str.9 = private unnamed_addr constant [10 x i8] c"\22,\22size\22:\00"
@.str.10 = private unnamed_addr constant [2 x i8] c"}\00"
@.str.12 = private unnamed_addr constant [10 x i8] c"Dummy_Api\00"

; --- External Runtime Functions ---
declare void @wolf_print_str(ptr)
declare void @wolf_throw(ptr)
declare i1 @wolf_has_error()
declare ptr @wolf_get_error()
declare void @wolf_clear_error()
declare void @wolf_print_int(i64)
declare void @wolf_print_float(double)
declare void @wolf_print_bool(i1)
declare void @wolf_print_nil()
declare void @wolf_println()
declare ptr @wolf_string_concat(ptr, ptr)
declare i64 @wolf_string_length(ptr)
declare ptr @wolf_string_upper(ptr)
declare ptr @wolf_string_lower(ptr)
declare ptr @wolf_string_trim(ptr)
declare ptr @wolf_int_to_string(i64)
declare ptr @wolf_float_to_string(double)
declare ptr @wolf_bool_to_string(i1)

; --- Math ---
declare double @wolf_math_abs(double)
declare double @wolf_math_ceil(double)
declare double @wolf_math_floor(double)
declare double @wolf_math_max(double, double)
declare double @wolf_math_min(double, double)
declare i64 @wolf_math_random(i64, i64)
declare double @wolf_math_sin(double)
declare double @wolf_math_cos(double)
declare double @wolf_math_tan(double)
declare double @wolf_math_asin(double)
declare double @wolf_math_acos(double)
declare double @wolf_math_atan(double)
declare double @wolf_math_atan2(double, double)
declare double @wolf_math_sqrt(double)
declare double @wolf_math_pow(double, double)
declare double @wolf_math_log(double)
declare double @wolf_math_log10(double)
declare double @wolf_math_exp(double)
declare double @wolf_math_round(double, i64)
declare double @wolf_math_fmod(double, double)
declare double @wolf_math_pi()
declare ptr @wolf_number_format(double, i64, ptr, ptr)
declare i64 @wolf_strings_length(ptr)

; --- Database (Mock) ---
declare ptr @wolf_db_connect(ptr, ptr, ptr, ptr)
declare ptr @wolf_db_prepare(ptr, ptr)
declare void @wolf_db_bind(ptr, ptr, ptr)
declare i64 @wolf_db_execute(ptr)
declare ptr @wolf_db_fetch_all(ptr)
declare ptr @wolf_db_fetch_one(ptr)
declare i64 @wolf_db_row_count(ptr)
declare i64 @wolf_db_last_insert_id(ptr)
declare void @wolf_db_close(ptr)
declare void @wolf_db_begin_transaction(ptr)
declare void @wolf_db_commit(ptr)
declare void @wolf_db_rollback(ptr)

; --- Stdlib Strings & JSON ---
declare i1 @wolf_strings_contains(ptr, ptr)
declare ptr @wolf_strings_upper(ptr)
declare ptr @wolf_strings_title(ptr)
declare ptr @wolf_strings_split(ptr, ptr)
declare ptr @wolf_strings_trimleft(ptr, ptr)
declare ptr @wolf_strings_trimright(ptr, ptr)
declare ptr @wolf_strings_join(ptr, ptr)
declare ptr @wolf_json_encode(ptr)

; --- Output & Display ---
declare void @wolf_say(ptr)
declare void @wolf_show(ptr)
declare void @wolf_inspect(ptr)

; --- Closures ---
declare ptr @wolf_closure_create(ptr, i64)
declare void @wolf_closure_set_env(ptr, i64, ptr)
declare ptr @wolf_closure_get_env(ptr, i64)
declare ptr @wolf_closure_get_fn(ptr)

; --- Phase 1 Stdlib: Strings ---
declare ptr @wolf_strtoupper(ptr)
declare ptr @wolf_strtolower(ptr)
declare ptr @wolf_ucfirst(ptr)
declare ptr @wolf_ucwords(ptr)
declare ptr @wolf_lcfirst(ptr)
declare ptr @wolf_trim(ptr)
declare ptr @wolf_ltrim(ptr)
declare ptr @wolf_rtrim(ptr)
declare i1 @wolf_str_contains(ptr, ptr)
declare i1 @wolf_str_starts_with(ptr, ptr)
declare i1 @wolf_str_ends_with(ptr, ptr)
declare ptr @wolf_str_replace(ptr, ptr, ptr)
declare ptr @wolf_str_repeat(ptr, i64)
declare ptr @wolf_str_pad(ptr, i64, ptr)
declare ptr @wolf_explode(ptr, ptr)
declare ptr @wolf_implode(ptr, ptr)
declare ptr @wolf_substr(ptr, i64, i64)
declare i64 @wolf_strpos(ptr, ptr)
declare i64 @wolf_strrpos(ptr, ptr)
declare i64 @wolf_str_word_count(ptr)
declare i64 @wolf_strcmp(ptr, ptr)
declare ptr @wolf_nl2br(ptr)
declare ptr @wolf_strip_tags(ptr)
declare ptr @wolf_htmlspecialchars(ptr)
declare ptr @wolf_addslashes(ptr)
declare ptr @wolf_stripslashes(ptr)
declare ptr @wolf_sprintf(ptr, ...)
declare ptr @wolf_http_req_file(i64, ptr)
declare i64 @wolf_http_req_file_count(i64)
declare void @wolf_http_header(ptr, ptr)
declare void @wolf_http_status(i64)
declare ptr @wolf_http_query(ptr)
declare i1 @wolf_strings_isempty(ptr)
declare ptr @wolf_strings_substring(ptr, i64, i64)
declare i64 @wolf_math_randomint(i64)
declare ptr @wolf_str_ireplace(ptr, ptr, ptr)
declare ptr @wolf_htmlspecialchars_decode(ptr)
declare double @wolf_similar_text(ptr, ptr)
declare ptr @wolf_wordwrap(ptr, i64, ptr, i1)
declare ptr @wolf_quoted_printable_encode(ptr)
declare ptr @wolf_ws_on_message(ptr)
declare ptr @wolf_ws_on_close(ptr)
declare ptr @wolf_ws_send(i64, ptr)
declare void @wolf_ws_broadcast(ptr)
declare void @wolf_ws_join(i64, ptr)
declare void @wolf_ws_broadcast_to(ptr, ptr)
declare void @wolf_presence_track(i64, ptr)
declare ptr @wolf_presence_list(ptr)
declare void @wolf_ws_close(i64)

; --- Phase 1 Stdlib: Regex ---
declare i1 @wolf_preg_match(ptr, ptr)
declare ptr @wolf_preg_match_captures(ptr, ptr)
declare i64 @wolf_preg_match_all(ptr, ptr)
declare ptr @wolf_preg_replace(ptr, ptr, ptr)
declare ptr @wolf_preg_split(ptr, ptr)

; --- Math Extras ---
declare double @wolf_deg2rad(double)
declare double @wolf_rad2deg(double)
declare double @wolf_clamp(double, double, double)

; --- Type Casting ---
declare i64 @wolf_intval(ptr)
declare double @wolf_floatval(ptr)
declare ptr @wolf_strval(i64)
declare i1 @wolf_boolval(ptr)
declare i64 @wolf_intdiv(i64, i64)
declare ptr @wolf_gettype(ptr)
declare i1 @wolf_is_numeric(ptr)
declare ptr @wolf_typeof(ptr)
declare i1 @wolf_is_string(ptr)
declare i1 @wolf_is_int(ptr)
declare i1 @wolf_is_float(ptr)
declare i1 @wolf_is_bool(ptr)
declare i1 @wolf_is_null(ptr)
declare i1 @wolf_is_array(ptr)
declare ptr @wolf_settype(ptr, ptr)
declare ptr @wolf_money_format(i64, ptr)
declare i64 @wolf_money_add(i64, i64)
declare i64 @wolf_money_subtract(i64, i64)
declare i64 @wolf_money_multiply(i64, double)
declare i64 @wolf_money_divide(i64, double)
declare i64 @wolf_money_percentage(i64, double)
declare ptr @wolf_pluralise(ptr, i64)
declare ptr @wolf_phone_format(ptr, ptr)
declare void @wolf_log_debug(ptr)
declare void @wolf_retry_sleep(i64, i64)

; --- Encoding ---
declare ptr @wolf_base64_encode(ptr)
declare ptr @wolf_base64_decode(ptr)
declare ptr @wolf_json_pretty(ptr)
declare ptr @wolf_json_decode(ptr)

; --- Security & Crypto ---
declare ptr @wolf_md5(ptr)
declare ptr @wolf_sha256(ptr)
declare ptr @wolf_sha512(ptr)
declare ptr @wolf_hash(ptr, ptr)
declare ptr @wolf_hash_hmac(ptr, ptr, ptr)
declare i1 @wolf_hash_equals(ptr, ptr)
declare ptr @wolf_password_hash(ptr)
declare i1 @wolf_password_verify(ptr, ptr)
declare i1 @wolf_password_needs_rehash(ptr)
declare ptr @wolf_encrypt(ptr, ptr)
declare ptr @wolf_decrypt(ptr, ptr)
declare ptr @wolf_rand_bytes(i64)
declare ptr @wolf_rand_hex(i64)
declare ptr @wolf_rand_token()
declare ptr @wolf_uuid_v4()
declare ptr @wolf_uuid_v7()
declare ptr @wolf_nanoid(i64)
declare ptr @wolf_custom_id(ptr, i64)
declare ptr @wolf_base64_url_encode(ptr)
declare ptr @wolf_base64_url_decode(ptr)
declare ptr @wolf_hex_encode(ptr)
declare ptr @wolf_hex_decode(ptr)
declare ptr @wolf_jwt_encode(ptr, ptr)
declare ptr @wolf_jwt_decode(ptr, ptr)
declare ptr @wolf_jwt_decode_unverified(ptr)
declare i1 @wolf_jwt_expired(ptr)
declare ptr @wolf_curve25519_keypair()
declare ptr @wolf_curve25519_shared(ptr, ptr)
declare ptr @wolf_sign(ptr, ptr)
declare i1 @wolf_verify(ptr, ptr, ptr)

; --- Debugging ---
declare void @wolf_dump(ptr)
declare void @wolf_dd(ptr)
declare void @wolf_log_info(ptr)
declare void @wolf_log_warning(ptr)
declare void @wolf_log_error(ptr)

; --- Time & System ---
declare i64 @wolf_time_now()
declare ptr @wolf_time_date(ptr, i64)
declare i64 @wolf_time_strtotime(ptr)
declare void @wolf_system_sleep(i64)
declare void @wolf_system_exit(i64)
declare void @wolf_system_die(ptr)
declare ptr @wolf_env_get(ptr, ptr)

; --- Phase 2: Arrays ---
declare i64 @wolf_count(ptr)
declare i1 @wolf_in_array(ptr, ptr)
declare i64 @wolf_array_search(ptr, ptr)
declare ptr @wolf_array_pop(ptr)
declare ptr @wolf_array_shift(ptr)
declare void @wolf_array_unshift(ptr, ptr)
declare ptr @wolf_array_reverse(ptr)
declare ptr @wolf_array_unique(ptr)
declare ptr @wolf_array_merge(ptr, ptr)
declare ptr @wolf_array_slice(ptr, i64, i64)
declare void @wolf_sort(ptr)
declare void @wolf_rsort(ptr)
declare double @wolf_array_sum(ptr)
declare ptr @wolf_array_keys(ptr)
declare ptr @wolf_array_values(ptr)
declare ptr @wolf_array_diff(ptr, ptr)
declare ptr @wolf_array_intersect(ptr, ptr)
declare ptr @wolf_array_flip(ptr)
declare ptr @wolf_range(i64, i64)

; --- Phase 2 Stdlib: Additional Array Functions ---
declare ptr @wolf_array_fill(i64, i64, ptr)
declare ptr @wolf_array_combine(ptr, ptr)
declare ptr @wolf_array_chunk(ptr, i64)
declare ptr @wolf_array_column(ptr, ptr)
declare double @wolf_array_product(ptr)
declare ptr @wolf_array_diff_key(ptr, ptr)
declare ptr @wolf_array_splice(ptr, i64, i64)
declare ptr @wolf_array_pad(ptr, i64, ptr)
declare ptr @wolf_array_count_values(ptr)
declare i64 @wolf_array_rand_one(ptr)
declare double @wolf_array_mean(ptr)
declare double @wolf_array_median(ptr)
declare ptr @wolf_array_mode(ptr)
declare double @wolf_array_variance(ptr)
declare double @wolf_array_std_dev(ptr)
declare double @wolf_array_percentile(ptr, double)

; --- Phase 3: Date/Time ---
declare i64 @wolf_time_ms()
declare i64 @wolf_time_ns()
declare i64 @wolf_mktime(i64, i64, i64, i64, i64, i64)
declare i64 @wolf_date_diff(i64, i64)
declare ptr @wolf_date_format(i64, ptr)
declare i64 @wolf_day_of_week(i64)
declare i64 @wolf_days_in_month(i64, i64)
declare i1 @wolf_is_leap_year(i64)
declare i64 @wolf_strtotime(ptr)
declare i64 @wolf_date_create(ptr)
declare i64 @wolf_date_add_days(i64, i64)
declare i64 @wolf_date_add_months(i64, i64)
declare i64 @wolf_date_diff_days(i64, i64)
declare i1 @wolf_date_is_past(i64)
declare i1 @wolf_date_is_future(i64)
declare ptr @wolf_date_to_iso(i64)

; --- Phase 3: Validation ---
declare i1 @wolf_is_email(ptr)
declare i1 @wolf_is_url(ptr)
declare i1 @wolf_is_phone(ptr)
declare i1 @wolf_is_uuid(ptr)
declare i1 @wolf_is_json(ptr)
declare i1 @wolf_is_ip(ptr)
declare i1 @wolf_is_alpha(ptr)
declare i1 @wolf_is_alpha_num(ptr)

; --- Phase 3: File System ---
declare i1 @wolf_file_exists(ptr)
declare ptr @wolf_file_read(ptr)
declare i1 @wolf_file_write(ptr, ptr)
declare i1 @wolf_file_append(ptr, ptr)
declare i1 @wolf_file_delete(ptr)
declare i64 @wolf_file_size(ptr)
declare ptr @wolf_file_extension(ptr)
declare ptr @wolf_file_basename(ptr)
declare ptr @wolf_file_dirname(ptr)
declare i1 @wolf_dir_exists(ptr)
declare i1 @wolf_file_copy(ptr, ptr)
declare i1 @wolf_file_move(ptr, ptr)
declare i1 @wolf_dir_create(ptr)
declare ptr @wolf_path_join(ptr, ptr)
declare ptr @wolf_scan_dir(ptr)

; --- Phase 3: Utilities ---
declare ptr @wolf_slug(ptr)
declare ptr @wolf_truncate(ptr, i64, ptr)

; --- STDLIB-08: Validation Rules Engine ---
declare ptr @wolf_validate(ptr, ptr)
declare i1 @wolf_validator_passes(ptr)
declare ptr @wolf_validator_errors(ptr)
declare ptr @wolf_validator_validated(ptr)

; --- DB-01: Query Builder ---
declare ptr @wolf_qb_create(ptr, ptr)
declare ptr @wolf_qb_with(ptr, ptr, ptr, ptr, ptr)
declare ptr @wolf_qb_where(ptr, ptr, ptr, ptr)
declare ptr @wolf_qb_order_by(ptr, ptr, ptr)
declare ptr @wolf_qb_limit(ptr, i64)
declare ptr @wolf_qb_offset(ptr, i64)
declare ptr @wolf_qb_get(ptr)
declare ptr @wolf_qb_first(ptr)
declare i64 @wolf_qb_insert(ptr, ptr)
declare i64 @wolf_qb_update(ptr, ptr)
declare i64 @wolf_qb_delete(ptr)
declare ptr @wolf_qb_paginate(ptr, i64, i64)

; --- Sessions ---
declare void @wolf_session_begin()
declare void @wolf_session_set(ptr, ptr)
declare ptr @wolf_session_get(ptr)
declare void @wolf_session_end()

; --- Define System (PHP-style constants) ---
declare void @wolf_define(ptr, ptr)
declare i1 @wolf_defined(ptr)
declare ptr @wolf_define_get(ptr)

; --- Redis ---
declare ptr @wolf_redis_connect(ptr, i64, ptr)
declare void @wolf_redis_set(ptr, ptr, i64)
declare ptr @wolf_redis_get(ptr)
declare i64 @wolf_redis_del(ptr)
declare i1 @wolf_redis_exists(ptr)
declare void @wolf_redis_hset(ptr, ptr, ptr)
declare ptr @wolf_redis_hget(ptr, ptr)
declare void @wolf_redis_close()

; --- Data Structures ---
declare ptr @wolf_array_create()
declare void @wolf_array_push(ptr, ptr)
declare ptr @wolf_array_get(ptr, i64)
declare i64 @wolf_array_length(ptr)
declare ptr @wolf_map_create()
declare void @wolf_map_set(ptr, ptr, ptr)
declare void @wolf_map_set_int(ptr, ptr, i64)
declare void @wolf_map_set_float(ptr, ptr, double)
declare void @wolf_map_set_bool(ptr, ptr, i1)
declare ptr @wolf_map_get(ptr, ptr)
declare ptr @wolf_class_create(ptr)
declare i1 @wolf_env_has(ptr)
declare ptr @wolf_val_int(i64)
declare ptr @wolf_val_float(double)
declare ptr @wolf_val_bool(i1)
declare ptr @wolf_val_array(ptr)

; --- Thread-Local Request Context ---
declare void @wolf_set_current_context(ptr, ptr)
declare ptr @wolf_get_request_body()
declare ptr @wolf_get_request_header(ptr)
declare ptr @wolf_get_request_method()
declare ptr @wolf_get_request_path()
declare ptr @wolf_input(ptr)
declare void @wolf_http_response_code(i64)
declare void @wolf_http_write_response(ptr)

; --- Phase 2: WolfScheduler ---
declare void @wolf_spawn_task(ptr)
declare void @wolf_task_wait_all()

; --- Phase 1: Concurrency (Legacy) ---
declare void @wolf_supervise_begin(i64, i64)
declare void @wolf_supervise_end()
declare void @wolf_trace_start(ptr)
declare void @wolf_trace_end(ptr)
declare void @wolf_metrics_increment(ptr)
declare void @wolf_metrics_gauge(ptr, double)
declare void @wolf_metrics_histogram(ptr, double)

; --- CLI Arguments ---
declare void @wolf_init_args(i32, ptr)
declare i64 @wolf_argc()
declare ptr @wolf_argv(i64)

; --- Sanitization ---
declare ptr @wolf_sanitize_string(ptr)
declare ptr @wolf_sanitize_email(ptr)
declare ptr @wolf_sanitize_url(ptr)
declare ptr @wolf_sanitize_int(ptr)
declare ptr @wolf_sanitize_float(ptr)

; --- HTTP Server (C FFI) ---
declare void @wolf_http_serve(i64, ptr)
declare ptr @wolf_http_req_method(i64)
declare ptr @wolf_http_req_path(i64)
declare ptr @wolf_http_req_query(i64, ptr)
declare ptr @wolf_http_req_header(i64, ptr)
declare ptr @wolf_http_req_body(i64)
declare void @wolf_http_res_header(i64, ptr, ptr)
declare void @wolf_http_res_status(i64, i64)
declare void @wolf_http_res_write(i64, ptr)

; --- HTTP Client (libcurl) ---
declare ptr @wolf_http_request(ptr, ptr, ptr, ptr)
declare ptr @wolf_http_get(ptr, ptr)
declare ptr @wolf_http_post(ptr, ptr, ptr)
declare ptr @wolf_http_put(ptr, ptr, ptr)
declare ptr @wolf_http_delete(ptr, ptr)
declare ptr @wolf_http_patch(ptr, ptr, ptr)
declare ptr @wolf_http_client_res_body(ptr)
declare ptr @wolf_http_client_res_json(ptr)
declare i64 @wolf_http_client_res_status(ptr)
declare i64 @wolf_http_client_res_ok(ptr)
declare i64 @wolf_http_client_res_failed(ptr)
declare ptr @wolf_http_client_res_header(ptr, ptr)
declare ptr @wolf_url_encode(ptr)
declare ptr @wolf_url_decode(ptr)
declare ptr @wolf_url_parse(ptr)
declare ptr @wolf_build_query(ptr)
declare ptr @wolf_dns_lookup(ptr)
declare ptr @wolf_get_client_ip()


define ptr @__wrapper_wolf_handler(ptr %__env_ignored, i64 %arg0, i64 %arg1) {
entry:
  %res = call ptr @wolf_handler(i64 %arg0, i64 %arg1)
  ret ptr %res
}
define void @wolf_handler(i64 %req_id.arg, i64 %res_id.arg) {
entry:
  %req_id = alloca i64
  %res_id = alloca i64
  %method = alloca ptr
  %path = alloca ptr
  %file = alloca ptr
  %meta = alloca ptr
  %name = alloca ptr
  %size = alloca ptr
  store i64 %req_id.arg, ptr %req_id
  store i64 %res_id.arg, ptr %res_id
  %t1 = load i64, ptr %req_id
  %t2 = call ptr @wolf_http_req_method(i64 %t1)
  %t3 = call i1 @wolf_has_error()
  br i1 %t3, label %err.true.1, label %err.false.2

err.true.1:
    ret void

err.false.2:
  store ptr %t2, ptr %method
  %t4 = load i64, ptr %req_id
  %t5 = call ptr @wolf_http_req_path(i64 %t4)
  %t6 = call i1 @wolf_has_error()
  br i1 %t6, label %err.true.3, label %err.false.4

err.true.3:
    ret void

err.false.4:
  store ptr %t5, ptr %path
  %t7 = load ptr, ptr %method
  %t8 = getelementptr [5 x i8], ptr @.str.1, i64 0, i64 0
  %t10 = call i64 @wolf_strcmp(ptr %t7, ptr %t8)
  %t9 = icmp eq i64 %t10, 0
  %t11 = load ptr, ptr %path
  %t12 = getelementptr [8 x i8], ptr @.str.2, i64 0, i64 0
  %t14 = call i64 @wolf_strcmp(ptr %t11, ptr %t12)
  %t13 = icmp eq i64 %t14, 0
  %t15 = and i1 %t9, %t13
  br i1 %t15, label %if.then.5, label %if.end.6
if.then.5:
  %t16 = load i64, ptr %req_id
  %t17 = getelementptr [7 x i8], ptr @.str.3, i64 0, i64 0
  %t18 = call ptr @wolf_http_req_file(i64 %t16, ptr %t17)
  %t19 = call i1 @wolf_has_error()
  br i1 %t19, label %err.true.7, label %err.false.8

err.true.7:
    ret void

err.false.8:
  store ptr %t18, ptr %file
  %t20 = load ptr, ptr %file
  %t21 = getelementptr [1 x i8], ptr @.str.4, i64 0, i64 0
  %t23 = call i64 @wolf_strcmp(ptr %t20, ptr %t21)
  %t22 = icmp eq i64 %t23, 0
  br i1 %t22, label %if.then.9, label %if.else.11
if.then.9:
  %t24 = load i64, ptr %res_id
  %t25 = call ptr @wolf_http_res_status(i64 %t24, i64 400)
  %t26 = call i1 @wolf_has_error()
  br i1 %t26, label %err.true.12, label %err.false.13

err.true.12:
    ret void

err.false.13:
  %t27 = load i64, ptr %res_id
  %t28 = getelementptr [20 x i8], ptr @.str.5, i64 0, i64 0
  %t29 = call ptr @wolf_http_res_write(i64 %t27, ptr %t28)
  %t30 = call i1 @wolf_has_error()
  br i1 %t30, label %err.true.14, label %err.false.15

err.true.14:
    ret void

err.false.15:
  br label %if.end.10
if.else.11:
  %t31 = load ptr, ptr %file
  %t32 = call ptr @wolf_json_decode(ptr %t31)
  %t33 = call i1 @wolf_has_error()
  br i1 %t33, label %err.true.16, label %err.false.17

err.true.16:
    ret void

err.false.17:
  store ptr %t32, ptr %meta
  %t34 = load ptr, ptr %meta
  %t35 = getelementptr [5 x i8], ptr @.str.6, i64 0, i64 0
  %t36 = call ptr @wolf_map_get(ptr %t34, ptr %t35)
  store ptr %t36, ptr %name
  %t37 = load ptr, ptr %meta
  %t38 = getelementptr [5 x i8], ptr @.str.7, i64 0, i64 0
  %t39 = call ptr @wolf_map_get(ptr %t37, ptr %t38)
  store ptr %t39, ptr %size
  %t40 = load i64, ptr %res_id
  %t41 = getelementptr [26 x i8], ptr @.str.8, i64 0, i64 0
  %t42 = load ptr, ptr %name
  %t43 = getelementptr [10 x i8], ptr @.str.9, i64 0, i64 0
  %t44 = load ptr, ptr %size
  %t45 = getelementptr [2 x i8], ptr @.str.10, i64 0, i64 0
  %t46 = call ptr @wolf_string_concat(ptr %t41, ptr %t42)
  %t47 = call ptr @wolf_string_concat(ptr %t46, ptr %t43)
  %t48 = call ptr @wolf_string_concat(ptr %t47, ptr %t44)
  %t49 = call ptr @wolf_string_concat(ptr %t48, ptr %t45)
  %t50 = call ptr @wolf_http_res_write(i64 %t40, ptr %t49)
  %t51 = call i1 @wolf_has_error()
  br i1 %t51, label %err.true.18, label %err.false.19

err.true.18:
    ret void

err.false.19:
  br label %if.end.10
if.end.10:
  ret void
  br label %if.end.6
if.end.6:
  %t52 = load i64, ptr %res_id
  %t53 = call ptr @wolf_http_res_status(i64 %t52, i64 404)
  %t54 = call i1 @wolf_has_error()
  br i1 %t54, label %err.true.20, label %err.false.21

err.true.20:
    ret void

err.false.21:
  %t55 = load i64, ptr %res_id
  %t56 = getelementptr [22 x i8], ptr @.str.11, i64 0, i64 0
  %t57 = call ptr @wolf_http_res_write(i64 %t55, ptr %t56)
  %t58 = call i1 @wolf_has_error()
  br i1 %t58, label %err.true.22, label %err.false.23

err.true.22:
    ret void

err.false.23:
  ret void
}

define i1 @wolf___compiler_dispatch_controller(ptr %c.arg, ptr %m.arg, ptr %args.arg, ptr %req.arg, ptr %res.arg) {
entry:
  %c = alloca ptr
  %m = alloca ptr
  %args = alloca ptr
  %req = alloca ptr
  %res = alloca ptr
  store ptr %c.arg, ptr %c
  store ptr %m.arg, ptr %m
  store ptr %args.arg, ptr %args
  store ptr %req.arg, ptr %req
  store ptr %res.arg, ptr %res
  ret i1 0
}

define ptr @wolf___compiler_create_model(ptr %name.arg) {
entry:
  %name = alloca ptr
  store ptr %name.arg, ptr %name
  %t59 = load ptr, ptr %name
  %t60 = getelementptr [10 x i8], ptr @.str.12, i64 0, i64 0
  %t62 = call i64 @wolf_strcmp(ptr %t59, ptr %t60)
  %t61 = icmp eq i64 %t62, 0
  br i1 %t61, label %if.then.24, label %if.end.25
if.then.24:
  %t63 = call ptr @wolf_NewDummy_Api()
  %t64 = call i1 @wolf_has_error()
  br i1 %t64, label %err.true.26, label %err.false.27

err.true.26:
    ret ptr null

err.false.27:
  ret ptr %t63
  br label %if.end.25
if.end.25:
  ret ptr null
}

define ptr @wolf_NewDummy_Api() {
entry:
  %this = alloca ptr
  %Dummy_Api.name_var = getelementptr [10 x i8], ptr @.str.12, i64 0, i64 0
  %t65 = call ptr @wolf_class_create(ptr %Dummy_Api.name_var)
  store ptr %t65, ptr %this
  %t66 = load ptr, ptr %this
  ret ptr %t66
}

define ptr @wolf_Dummy_Api_get(ptr %this.arg) {
entry:
  %this = alloca ptr
  store ptr %this.arg, ptr %this
  %t67 = getelementptr [11 x i8], ptr @.str.13, i64 0, i64 0
  ret ptr %t67
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  call void @wolf_init_args(i32 %argc, ptr %argv)
  %t68 = call ptr @wolf_closure_create(ptr @__wrapper_wolf_handler, i64 0)
  %t69 = call ptr @wolf_http_serve(i64 9292, ptr %t68)
  %t70 = call i1 @wolf_has_error()
  br i1 %t70, label %err.true.28, label %err.false.29

err.true.28:
    ret i32 1

err.false.29:
  ret i32 0
}
