// Package scaffold generates new Wolf project structures.
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

// ProjectType defines the type of project to be created.
type ProjectType string

const (
	TypeScript ProjectType = "script"
	TypeAPI    ProjectType = "api"
	TypeMCU    ProjectType = "mcu"
)

// Project creates a new Wolf project with standard directory structure.
func Project(name string, projectType ProjectType) error {
	if name == "" {
		return fmt.Errorf("wolf: project name is required")
	}

	if projectType == "" {
		projectType = TypeScript
	}

	// MCU has its own distinct scaffold — delegate
	if projectType == TypeMCU {
		return scaffoldMCU(name)
	}

	var dirs []string
	if projectType == TypeScript {
		dirs = []string{
			name,
			filepath.Join(name, "src"),
			filepath.Join(name, "config"),
		}
	} else {
		dirs = []string{
			name,
			filepath.Join(name, "controllers"),
			filepath.Join(name, "models"),
			filepath.Join(name, "libraries"),
			filepath.Join(name, "views"),
			filepath.Join(name, "config"),
			filepath.Join(name, "public"),
			filepath.Join(name, "tests"),
		}
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("wolf: failed to create %s: %w", dir, err)
		}
	}

	files := make(map[string]string)

	if projectType == TypeScript {
		// Script-Mode files
		files[filepath.Join(name, "src", "main.wolf")] = fmt.Sprintf(`# %s — A Wolf Script
# Generated by wolf new --type=script

func main() {
    print("Hello from your new Wolf script!")
}

main()
`, name)

		files[filepath.Join(name, "wolf.config")] = `# wolf.config — Script project
[target]
mode = script     # lightweight runtime, single-threaded, run-to-completion
arch = native

[app]
name    = ` + name + `
version = 1.0.0
env     = development
`
	} else {
		// API-Mode files
		files[filepath.Join(name, "public", "index.wolf")] = fmt.Sprintf(`# %s — API Entry Point
# Generated by wolf new --type=api

# Load base libraries
require("libraries/Controller.wolf")
require("libraries/Database.wolf")

# Load controllers
require("controllers/WelcomeController.wolf")

# Simple Routing
$path = wolf_get_request_path()

if $path == "/" || $path == "" {
    $c = new WelcomeController()
    $c->index()
} else {
    print("404 Not Found")
}
`, name)
		files[filepath.Join(name, "controllers", "WelcomeController.wolf")] = `class WelcomeController extends Controller {
    func index() {
        $this->sendResponse(true, "Welcome to ` + name + ` API", {
            "version": "1.0.0",
            "status": "online"
        }, 200)
    }
}
`
		files[filepath.Join(name, "libraries", "Controller.wolf")] = `# Base Controller
class Controller {
    func model($model) {
        return __compiler_create_model($model)
    }

    func getData() {
        $raw = wolf_get_request_body()
        return json_decode($raw)
    }

    func sendResponse($status, $message, $data, $httpCode) {
        http_response_code($httpCode)
        print(json_encode({
            "status": $status,
            "message": $message,
            "data": $data,
            "timestamp": time()
        }))
    }
}
`
		files[filepath.Join(name, "libraries", "Database.wolf")] = `# Base Database
class Database {
    $dbh
    func __construct() {
        $this->dbh = db_connect(env("DB_HOST"), env("DB_USER"), env("DB_PASS"), env("DB_NAME"))
    }
    func query($q) { return db_prepare($this->dbh, $q) }
}
`
		files[filepath.Join(name, "wolf.config")] = `# wolf.config — API project
# Generated by wolf new --type=api

[target]
mode = api        # full HTTP server, Thread-Per-Core, arena pool
arch = native     # compile for the host machine

[app]
name    = ` + name + `
version = 1.0.0
env     = development

[server]
host    = 0.0.0.0
port    = 2006
workers = 0       # 0 = auto-detect CPU count at startup

[database]
driver   = mysql
host     = localhost
port     = 3306
name     = ` + name + `_db
user     = root
password =
pool_size = 10

[redis]
host = 127.0.0.1
port = 6379
`
		files[filepath.Join(name, "docker-compose.yml")] = `version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ` + name + `_db
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
`
	}

	// Shared files
	files[filepath.Join(name, "wolf.python")] = `{
  "python_version": "3",
  "packages": [],
  "venv_path": ".wolf-venv",
  "auto_activate": true
}
`
	files[filepath.Join(name, ".gitignore")] = `wolf_out/
*.exe
.wolf-venv/
__pycache__/
wolf.python.lock
`
	files[filepath.Join(name, "README.md")] = fmt.Sprintf(`# %s
Generated by Wolf 🐺

## Getting Started
`+"```bash"+`
wolf run %s
`+"```"+`
`, name, map[bool]string{true: "src/main.wolf", false: "public/index.wolf"}[projectType == TypeScript])

	for path, content := range files {
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("wolf: failed to write %s: %w", path, err)
		}
	}

	return nil
}

// scaffoldMCU creates a Wolf MCU/embedded project.
// The generated project uses a cooperative event loop (no pthreads, no epoll),
// a static memory slab, and compiles via the arm-none-eabi toolchain.
func scaffoldMCU(name string) error {
	dirs := []string{
		name,
		filepath.Join(name, "src"),
		filepath.Join(name, "hal"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("wolf: failed to create %s: %w", dir, err)
		}
	}

	files := map[string]string{
		// Main cooperative event loop — no HTTP, no threads
		filepath.Join(name, "src", "main.wolf"): fmt.Sprintf(`# %s — Wolf MCU Entry Point
# Generated by wolf new --type=mcu
#
# This runs in a cooperative bare-metal loop.
# No OS, no threads, no malloc.
# I/O is driven by interrupt callbacks registered via wolf_timer_set / wolf_gpio_watch.

# Load hardware abstraction layer
require("hal/board.wolf")

# Setup phase — runs once at boot
func setup() {
    # Configure GPIO, UART, SPI, I2C here
    wolf_gpio_mode(Board::LED_PIN, "output")
    wolf_uart_init(Board::UART_PORT, 115200)
    wolf_uart_send(Board::UART_PORT, "Boot OK\n")
}

# Loop phase — called by the runtime on every cooperative tick
func loop() {
    # Application logic here
    # Keep this non-blocking: no busy-waits, no sleep()
    wolf_gpio_toggle(Board::LED_PIN)
    wolf_delay_ms(500)
}

setup()
wolf_mcu_run(loop)   # hands control to the cooperative scheduler
`, name),

		// Hardware Abstraction Layer — board-specific pin declarations
		filepath.Join(name, "hal", "board.wolf"): fmt.Sprintf(`# hal/board.wolf — %s Board Configuration
# Edit these constants to match your actual hardware.
# Refer to your MCU datasheet for pin numbers and peripheral addresses.

class Board {
    # GPIO pins (logical pin numbers for your HAL driver)
    const LED_PIN    = 13     # onboard LED, typically PA5 on STM32 Nucleo
    const BUTTON_PIN = 0      # user button, typically PC13

    # UART port identifiers (0-indexed, matches USART1/2/3 etc.)
    const UART_PORT  = 0      # primary debug UART

    # SPI / I2C port identifiers (optional — uncomment when needed)
    # const SPI_PORT  = 0
    # const I2C_PORT  = 0
}
`, name),

		// wolf.config — MCU target (no server, no DB, no Redis)
		filepath.Join(name, "wolf.config"): `# wolf.config — MCU/Embedded project
# Generated by wolf new --type=mcu
#
# wolf build reads [target] and compiles with the appropriate toolchain.
# No [server], [database], or [redis] sections — bare metal has none of these.

[target]
mode = mcu               # cooperative scheduler, static heap, no OS primitives
arch = arm-cortex-m4     # change to match your MCU: arm-cortex-m0, riscv32, etc.

[app]
name    = ` + name + `
version = 1.0.0
env     = production     # no development mode on bare metal

[build]
out_dir    = wolf_out
optimise   = true        # always optimise for MCU (code size + speed)
keep_ll    = false
`,

		// Makefile — invokes wolf build then flashes via OpenOCD
		filepath.Join(name, "Makefile"): fmt.Sprintf(`# Makefile — %s MCU Project
# Requires: wolf, arm-none-eabi-gcc, openocd (for flashing)
#
# make         — build the firmware
# make flash   — build and flash via OpenOCD (ST-Link V2)
# make clean   — remove build artifacts

WOLF     := wolf
TARGET   := wolf_out/%s
ENTRY    := src/main.wolf

.PHONY: all flash clean

all:
	$(WOLF) build $(ENTRY)

flash: all
	openocd -f interface/stlink.cfg -f target/stm32f4x.cfg \
	  -c "program $(TARGET) verify reset exit"

clean:
	rm -rf wolf_out/
`, name, name),

		// .gitignore
		filepath.Join(name, ".gitignore"): `wolf_out/
*.elf
*.bin
*.hex
*.map
`,

		// README
		filepath.Join(name, "README.md"): fmt.Sprintf(`# %s — Wolf MCU Project
Generated by Wolf 🐺

## Build

`+"```bash"+`
wolf build src/main.wolf
`+"```"+`

## Flash (STM32 via OpenOCD)

`+"```bash"+`
make flash
`+"```"+`

## Targeting a different MCU

Edit `+"`wolf.config`"+` and change `+"`arch`"+`:

| MCU Family | arch value |
|---|---|
| ARM Cortex-M4 (STM32F4) | `+"`arm-cortex-m4`"+` |
| ARM Cortex-M0 (STM32F0) | `+"`arm-cortex-m0`"+` |
| RISC-V 32-bit | `+"`riscv32`"+` |
`, name),
	}

	for path, content := range files {
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("wolf: failed to write %s: %w", path, err)
		}
	}
	return nil
}

// Generate creates a new Wolf file of the given type and name.
// Types: controller, model, service, library
func Generate(kind, name string) (string, error) {
	if name == "" {
		return "", fmt.Errorf("wolf: name is required for generate")
	}

	var dir, filename, content string

	switch kind {
	case "controller":
		dir = "controllers"
		filename = name + ".wolf"
		content = fmt.Sprintf(`# controllers/%s.wolf
# Auto-generated by wolf generate

class %s extends Controller {
    $%sModel

    func __construct() {
        $this->%sModel = $this->model("%s")
    }

    func sendResponse($status, $message, $data, $httpCode: int) {
        http_response_code($httpCode)
        echo json_encode({
            "status": $status,
            "message": $message,
            "data": $data,
            "timestamp": time()
        })
    }

    # GET /%s
    func index() {
        $this->sendResponse(true, "%s API", {
            "version": "1.0",
            "controller": "%s"
        }, 200)
    }
}
`, name, name, toLowerFirst(name), toLowerFirst(name), name, toLowerFirst(name), name, name)

	case "model":
		dir = "models"
		filename = name + ".wolf"
		content = fmt.Sprintf(`# models/%s.wolf
# Auto-generated by wolf generate

class %s {
    $db

    func __construct() {
        $this->db = new Database()
    }

    func findAll() {
        $this->db->query("SELECT * FROM %ss")
        return $this->db->resultset()
    }

    func findById($id) {
        $this->db->query("SELECT * FROM %ss WHERE id = :id")
        $this->db->bind(":id", $id)
        return $this->db->single()
    }

    func create($data) {
        $this->db->query("INSERT INTO %ss (name) VALUES (:name)")
        $this->db->bind(":name", $data["name"])
        return $this->db->execute()
    }

    func update($id, $data) {
        $this->db->query("UPDATE %ss SET name = :name WHERE id = :id")
        $this->db->bind(":id", $id)
        $this->db->bind(":name", $data["name"])
        return $this->db->execute()
    }

    func delete($id) {
        $this->db->query("DELETE FROM %ss WHERE id = :id")
        $this->db->bind(":id", $id)
        return $this->db->execute()
    }
}
`, name, name, toLowerFirst(name), toLowerFirst(name), toLowerFirst(name), toLowerFirst(name), toLowerFirst(name))

	case "service":
		dir = "services"
		filename = name + "Service.wolf"
		content = fmt.Sprintf(`# services/%sService.wolf
# Auto-generated by wolf generate

class %sService {

    func __construct() {
        # Initialize dependencies here
    }

    func execute($data) {
        # Service logic here
        return {"status": true, "message": "%sService executed"}
    }
}
`, name, name, name)

	case "library":
		dir = "libraries"
		filename = name + ".wolf"
		content = fmt.Sprintf(`# libraries/%s.wolf
# Auto-generated by wolf generate

class %s {

    func __construct() {
        # Initialize here
    }
}
`, name, name)

	default:
		return "", fmt.Errorf("wolf: unknown generate type '%s'. Use: controller, model, service, library", kind)
	}

	// Create directory if it doesn't exist
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("wolf: failed to create %s/: %w", dir, err)
	}

	outPath := filepath.Join(dir, filename)

	// Don't overwrite existing files
	if _, err := os.Stat(outPath); err == nil {
		return "", fmt.Errorf("wolf: %s already exists", outPath)
	}

	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("wolf: failed to write %s: %w", outPath, err)
	}

	return outPath, nil
}

func toLowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return string(s[0]|0x20) + s[1:]
}
