// Package scaffold generates new Wolf project structures.
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

// ProjectType defines the type of project to be created.
type ProjectType string

const (
	TypeScript ProjectType = "script"
	TypeAPI    ProjectType = "api"
)

// Project creates a new Wolf project with standard directory structure.
func Project(name string, projectType ProjectType) error {
	if name == "" {
		return fmt.Errorf("wolf: project name is required")
	}

	if projectType == "" {
		projectType = TypeScript
	}

	var dirs []string
	if projectType == TypeScript {
		dirs = []string{
			name,
			filepath.Join(name, "src"),
			filepath.Join(name, "config"),
		}
	} else {
		dirs = []string{
			name,
			filepath.Join(name, "controllers"),
			filepath.Join(name, "models"),
			filepath.Join(name, "libraries"),
			filepath.Join(name, "views"),
			filepath.Join(name, "config"),
			filepath.Join(name, "public"),
			filepath.Join(name, "tests"),
		}
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("wolf: failed to create %s: %w", dir, err)
		}
	}

	files := make(map[string]string)

	if projectType == TypeScript {
		// Script-Mode files
		files[filepath.Join(name, "src", "main.wolf")] = fmt.Sprintf(`# %s — A Wolf Script
# Generated by wolf new --type=script

func main() {
    print("Hello from your new Wolf script!")
}

main()
`, name)

		files[filepath.Join(name, "config", "wolf.config.json")] = `{
  "name": "` + name + `",
  "version": "1.0.0",
  "main": "src/main.wolf"
}
`
	} else {
		// API-Mode files
		files[filepath.Join(name, "public", "index.wolf")] = fmt.Sprintf(`# %s — API Entry Point
# Generated by wolf new --type=api

# Load base libraries
require("libraries/Controller.wolf")
require("libraries/Database.wolf")

# Load controllers
require("controllers/WelcomeController.wolf")

# Simple Routing
$path = wolf_get_request_path()

if $path == "/" || $path == "" {
    $c = new WelcomeController()
    $c->index()
} else {
    print("404 Not Found")
}
`, name)
		files[filepath.Join(name, "controllers", "WelcomeController.wolf")] = `class WelcomeController extends Controller {
    func index() {
        $this->sendResponse(true, "Welcome to ` + name + ` API", {
            "version": "1.0.0",
            "status": "online"
        }, 200)
    }
}
`
		files[filepath.Join(name, "libraries", "Controller.wolf")] = `# Base Controller
class Controller {
    func model($model) {
        return __compiler_create_model($model)
    }

    func getData() {
        $raw = wolf_get_request_body()
        return json_decode($raw)
    }

    func sendResponse($status, $message, $data, $httpCode) {
        http_response_code($httpCode)
        print(json_encode({
            "status": $status,
            "message": $message,
            "data": $data,
            "timestamp": time()
        }))
    }
}
`
		files[filepath.Join(name, "libraries", "Database.wolf")] = `# Base Database
class Database {
    $dbh
    func __construct() {
        $this->dbh = db_connect(env("DB_HOST"), env("DB_USER"), env("DB_PASS"), env("DB_NAME"))
    }
    func query($q) { return db_prepare($this->dbh, $q) }
}
`
		files[filepath.Join(name, "config", "wolf.config.json")] = `{
  "name": "` + name + `",
  "version": "1.0.0",
  "server": {
    "port": 8080,
    "workers": 4
  },
  "database": {
    "driver": "mysql",
    "host": "localhost",
    "user": "root",
    "pass": "secret",
    "name": "` + name + `_db"
  },
  "redis": {
    "host": "localhost",
    "port": 6379
  }
}
`
		files[filepath.Join(name, "docker-compose.yml")] = `version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ` + name + `_db
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
`
	}

	// Shared files
	files[filepath.Join(name, "wolf.python")] = `{
  "python_version": "3",
  "packages": [],
  "venv_path": ".wolf-venv",
  "auto_activate": true
}
`
	files[filepath.Join(name, ".gitignore")] = `wolf_out/
*.exe
.wolf-venv/
__pycache__/
wolf.python.lock
`
	files[filepath.Join(name, "README.md")] = fmt.Sprintf(`# %s
Generated by Wolf 🐺

## Getting Started
`+"```bash"+`
wolf run %s
`+"```"+`
`, name, map[bool]string{true: "src/main.wolf", false: "public/index.wolf"}[projectType == TypeScript])

	for path, content := range files {
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("wolf: failed to write %s: %w", path, err)
		}
	}

	return nil
}

// Generate creates a new Wolf file of the given type and name.
// Types: controller, model, service, library
func Generate(kind, name string) (string, error) {
	if name == "" {
		return "", fmt.Errorf("wolf: name is required for generate")
	}

	var dir, filename, content string

	switch kind {
	case "controller":
		dir = "controllers"
		filename = name + ".wolf"
		content = fmt.Sprintf(`# controllers/%s.wolf
# Auto-generated by wolf generate

class %s extends Controller {
    $%sModel

    func __construct() {
        $this->%sModel = $this->model("%s")
    }

    func sendResponse($status, $message, $data, $httpCode: int) {
        http_response_code($httpCode)
        echo json_encode({
            "status": $status,
            "message": $message,
            "data": $data,
            "timestamp": time()
        })
    }

    # GET /%s
    func index() {
        $this->sendResponse(true, "%s API", {
            "version": "1.0",
            "controller": "%s"
        }, 200)
    }
}
`, name, name, toLowerFirst(name), toLowerFirst(name), name, toLowerFirst(name), name, name)

	case "model":
		dir = "models"
		filename = name + ".wolf"
		content = fmt.Sprintf(`# models/%s.wolf
# Auto-generated by wolf generate

class %s {
    $db

    func __construct() {
        $this->db = new Database()
    }

    func findAll() {
        $this->db->query("SELECT * FROM %ss")
        return $this->db->resultset()
    }

    func findById($id) {
        $this->db->query("SELECT * FROM %ss WHERE id = :id")
        $this->db->bind(":id", $id)
        return $this->db->single()
    }

    func create($data) {
        $this->db->query("INSERT INTO %ss (name) VALUES (:name)")
        $this->db->bind(":name", $data["name"])
        return $this->db->execute()
    }

    func update($id, $data) {
        $this->db->query("UPDATE %ss SET name = :name WHERE id = :id")
        $this->db->bind(":id", $id)
        $this->db->bind(":name", $data["name"])
        return $this->db->execute()
    }

    func delete($id) {
        $this->db->query("DELETE FROM %ss WHERE id = :id")
        $this->db->bind(":id", $id)
        return $this->db->execute()
    }
}
`, name, name, toLowerFirst(name), toLowerFirst(name), toLowerFirst(name), toLowerFirst(name), toLowerFirst(name))

	case "service":
		dir = "services"
		filename = name + "Service.wolf"
		content = fmt.Sprintf(`# services/%sService.wolf
# Auto-generated by wolf generate

class %sService {

    func __construct() {
        # Initialize dependencies here
    }

    func execute($data) {
        # Service logic here
        return {"status": true, "message": "%sService executed"}
    }
}
`, name, name, name)

	case "library":
		dir = "libraries"
		filename = name + ".wolf"
		content = fmt.Sprintf(`# libraries/%s.wolf
# Auto-generated by wolf generate

class %s {

    func __construct() {
        # Initialize here
    }
}
`, name, name)

	default:
		return "", fmt.Errorf("wolf: unknown generate type '%s'. Use: controller, model, service, library", kind)
	}

	// Create directory if it doesn't exist
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("wolf: failed to create %s/: %w", dir, err)
	}

	outPath := filepath.Join(dir, filename)

	// Don't overwrite existing files
	if _, err := os.Stat(outPath); err == nil {
		return "", fmt.Errorf("wolf: %s already exists", outPath)
	}

	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("wolf: failed to write %s: %w", outPath, err)
	}

	return outPath, nil
}

func toLowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return string(s[0]|0x20) + s[1:]
}
