// Package scaffold generates new Wolf project structures.
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

// Project creates a new Wolf project with standard directory structure.
func Project(name string) error {
	if name == "" {
		return fmt.Errorf("wolf: project name is required")
	}

	dirs := []string{
		name,
		filepath.Join(name, "src"),
		filepath.Join(name, "tests"),
		filepath.Join(name, "config"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("wolf: failed to create %s: %w", dir, err)
		}
	}

	// Main entry point
	mainWolf := filepath.Join(name, "src", "main.wolf")
	mainContent := fmt.Sprintf(`# %s — A Wolf Application
# Generated by wolf new

print("Welcome to %s!")

func main() {
    print("Hello from Wolf!")
}

main()
`, name, name)

	// Config file
	configPath := filepath.Join(name, "config", "wolf.config.json")
	configContent := fmt.Sprintf(`{
  "name": "%s",
  "version": "0.1.0",
  "main": "src/main.wolf",
  "database": {
    "driver": "mysql",
    "host": "localhost",
    "port": 3306,
    "user": "root",
    "pass": "",
    "name": "%s"
  }
}
`, name, name)

	// Python config
	pythonPath := filepath.Join(name, "wolf.python")
	pythonContent := `{
  "python_version": "3",
  "packages": [],
  "venv_path": ".wolf-venv",
  "auto_activate": true
}
`

	// .gitignore
	gitignorePath := filepath.Join(name, ".gitignore")
	gitignoreContent := `# Wolf build output
wolf_out/
*.exe

# Python venv
.wolf-venv/
__pycache__/
*.pyc

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db

# Lock files (generated)
wolf.python.lock
`

	// README
	readmePath := filepath.Join(name, "README.md")
	readmeContent := fmt.Sprintf(`# %s

A Wolf Language application.

## Getting Started

`+"```bash"+`
wolf run src/main.wolf
`+"```"+`

## Project Structure

`+"```"+`
%s/
├── src/
│   └── main.wolf      # Entry point
├── tests/              # Test files
├── config/
│   └── wolf.config.json
├── wolf.python         # Python env config
├── .gitignore
└── README.md
`+"```"+`

## Built with Wolf 🐺
`, name, name)

	files := map[string]string{
		mainWolf:      mainContent,
		configPath:    configContent,
		pythonPath:    pythonContent,
		gitignorePath: gitignoreContent,
		readmePath:    readmeContent,
	}

	for path, content := range files {
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("wolf: failed to write %s: %w", path, err)
		}
	}

	return nil
}
