; Wolf Language — LLVM IR Output
; Generated by wolf compiler

target triple = "x86_64-pc-linux-gnu"

; --- String Constants ---
@.str.5 = private unnamed_addr constant [8 x i8] c"message\00"
@.str.1 = private unnamed_addr constant [36 x i8] c"var $a = 1; var $b = 2; var $c = 3;\00"
@.str.24 = private unnamed_addr constant [10 x i8] c" | Path: \00"
@.str.27 = private unnamed_addr constant [43 x i8] c"\F0\9F\90\BA Starting Timeout Test on port 8080...\00"
@.str.28 = private unnamed_addr constant [47 x i8] c"\F0\9F\90\BA Starting WS Metadata Test on port 8080...\00"
@.str.3 = private unnamed_addr constant [9 x i8] c"Errors: \00"
@.str.15 = private unnamed_addr constant [63 x i8] c"Starting slow request (60s)... Watchdog should kill it at 30s.\00"
@.str.23 = private unnamed_addr constant [13 x i8] c"WS Message: \00"
@.str.26 = private unnamed_addr constant [20 x i8] c" | Handshake Path: \00"
@.str.16 = private unnamed_addr constant [53 x i8] c"CRITICAL FAILURE: Watchdog did NOT kill the request!\00"
@.str.19 = private unnamed_addr constant [2 x i8] c"/\00"
@.str.20 = private unnamed_addr constant [13 x i8] c"Content-Type\00"
@.str.22 = private unnamed_addr constant [21 x i8] c"scratch/test_ws.html\00"
@.str.33 = private unnamed_addr constant [8 x i8] c" failed\00"
@.str.2 = private unnamed_addr constant [10 x i8] c"test.wolf\00"
@.str.14 = private unnamed_addr constant [6 x i8] c"/slow\00"
@.str.32 = private unnamed_addr constant [10 x i8] c" passed, \00"
@.str.25 = private unnamed_addr constant [7 x i8] c"Echo: \00"
@.str.29 = private unnamed_addr constant [15 x i8] c"\E2\9C\85 test_debug\00"
@.str.30 = private unnamed_addr constant [26 x i8] c"\E2\9D\8C test_debug - FAILED: \00"
@.str.6 = private unnamed_addr constant [13 x i8] c"Statements: \00"
@.str.8 = private unnamed_addr constant [6 x i8] c"Stmt \00"
@.str.9 = private unnamed_addr constant [3 x i8] c": \00"
@.str.13 = private unnamed_addr constant [5 x i8] c"name\00"
@.str.18 = private unnamed_addr constant [17 x i8] c"Fast response OK\00"
@.str.31 = private unnamed_addr constant [9 x i8] c"\0ATests: \00"
@.str.11 = private unnamed_addr constant [8 x i8] c"VarDecl\00"
@.str.21 = private unnamed_addr constant [10 x i8] c"text/html\00"
@.str.4 = private unnamed_addr constant [6 x i8] c"Err: \00"
@.str.7 = private unnamed_addr constant [11 x i8] c"statements\00"
@.str.10 = private unnamed_addr constant [5 x i8] c"type\00"
@.str.12 = private unnamed_addr constant [8 x i8] c"  name=\00"
@.str.17 = private unnamed_addr constant [23 x i8] c"Slow response finished\00"

; --- External Runtime Functions ---
declare void @wolf_print_str(ptr)
declare void @wolf_throw(ptr)
declare i1 @wolf_has_error()
declare ptr @wolf_get_error()
declare void @wolf_clear_error()
declare void @wolf_print_int(i64)
declare void @wolf_print_float(double)
declare void @wolf_print_bool(i1)
declare void @wolf_print_nil()
declare void @wolf_println()
declare ptr @wolf_string_concat(ptr, ptr)
declare i64 @wolf_string_length(ptr)
declare ptr @wolf_string_upper(ptr)
declare ptr @wolf_string_lower(ptr)
declare ptr @wolf_string_trim(ptr)
declare ptr @wolf_int_to_string(i64)
declare ptr @wolf_float_to_string(double)
declare ptr @wolf_bool_to_string(i1)

; --- Math ---
declare double @wolf_math_abs(double)
declare double @wolf_math_ceil(double)
declare double @wolf_math_floor(double)
declare double @wolf_math_max(double, double)
declare double @wolf_math_min(double, double)
declare i64 @wolf_math_random(i64, i64)
declare double @wolf_math_sin(double)
declare double @wolf_math_cos(double)
declare double @wolf_math_tan(double)
declare double @wolf_math_asin(double)
declare double @wolf_math_acos(double)
declare double @wolf_math_atan(double)
declare double @wolf_math_atan2(double, double)
declare double @wolf_math_sqrt(double)
declare double @wolf_math_pow(double, double)
declare double @wolf_math_log(double)
declare double @wolf_math_log10(double)
declare double @wolf_math_exp(double)
declare double @wolf_math_round(double, i64)
declare double @wolf_math_fmod(double, double)
declare double @wolf_math_pi()
declare ptr @wolf_number_format(double, i64, ptr, ptr)
declare i64 @wolf_strings_length(ptr)
declare i64 @wolf_strings_charcode_at(ptr, i64)

; --- Database (Mock) ---
declare ptr @wolf_db_connect(ptr, ptr, ptr, ptr)
declare ptr @wolf_db_prepare(ptr, ptr)
declare void @wolf_db_bind(ptr, ptr, ptr)
declare i64 @wolf_db_execute(ptr)
declare ptr @wolf_db_fetch_all(ptr)
declare ptr @wolf_db_fetch_one(ptr)
declare i64 @wolf_db_row_count(ptr)
declare i64 @wolf_db_last_insert_id(ptr)
declare void @wolf_db_close(ptr)
declare void @wolf_db_begin_transaction(ptr)
declare void @wolf_db_commit(ptr)
declare void @wolf_db_rollback(ptr)

; --- Stdlib Strings & JSON ---
declare i1 @wolf_strings_contains(ptr, ptr)
declare ptr @wolf_strings_upper(ptr)
declare ptr @wolf_strings_title(ptr)
declare ptr @wolf_strings_split(ptr, ptr)
declare ptr @wolf_strings_trimleft(ptr, ptr)
declare ptr @wolf_strings_trimright(ptr, ptr)
declare ptr @wolf_strings_join(ptr, ptr)
declare ptr @wolf_json_encode(ptr)

; --- Output & Display ---
declare void @wolf_say(ptr)
declare void @wolf_show(ptr)
declare void @wolf_inspect(ptr)

; --- Closures ---
declare ptr @wolf_closure_create(ptr, i64)
declare void @wolf_closure_set_env(ptr, i64, ptr)
declare ptr @wolf_closure_get_env(ptr, i64)
declare ptr @wolf_closure_get_fn(ptr)

; --- Phase 1 Stdlib: Strings ---
declare ptr @wolf_strtoupper(ptr)
declare ptr @wolf_strtolower(ptr)
declare ptr @wolf_ucfirst(ptr)
declare ptr @wolf_ucwords(ptr)
declare ptr @wolf_lcfirst(ptr)
declare ptr @wolf_trim(ptr)
declare ptr @wolf_ltrim(ptr)
declare ptr @wolf_rtrim(ptr)
declare i1 @wolf_str_contains(ptr, ptr)
declare i1 @wolf_str_starts_with(ptr, ptr)
declare i1 @wolf_str_ends_with(ptr, ptr)
declare ptr @wolf_str_replace(ptr, ptr, ptr)
declare ptr @wolf_str_repeat(ptr, i64)
declare ptr @wolf_str_pad(ptr, i64, ptr)
declare ptr @wolf_explode(ptr, ptr)
declare ptr @wolf_implode(ptr, ptr)
declare ptr @wolf_substr(ptr, i64, i64)
declare i64 @wolf_strpos(ptr, ptr)
declare i64 @wolf_strrpos(ptr, ptr)
declare i64 @wolf_str_word_count(ptr)
declare i64 @wolf_strcmp(ptr, ptr)
declare i32 @strcmp(ptr, ptr)
declare ptr @wolf_nl2br(ptr)
declare ptr @wolf_strip_tags(ptr)
declare ptr @wolf_htmlspecialchars(ptr)
declare ptr @wolf_addslashes(ptr)
declare ptr @wolf_stripslashes(ptr)
declare ptr @wolf_sprintf(ptr, ...)
declare ptr @wolf_http_req_file(i64, ptr)
declare i64 @wolf_http_req_file_count(i64)
declare void @wolf_http_header(ptr, ptr)
declare void @wolf_http_status(i64)
declare ptr @wolf_http_query(ptr)
declare i1 @wolf_strings_isempty(ptr)
declare ptr @wolf_strings_substring(ptr, i64, i64)
declare i64 @wolf_math_randomint(i64)
declare ptr @wolf_str_ireplace(ptr, ptr, ptr)
declare ptr @wolf_htmlspecialchars_decode(ptr)
declare double @wolf_similar_text(ptr, ptr)
declare ptr @wolf_wordwrap(ptr, i64, ptr, i1)
declare ptr @wolf_quoted_printable_encode(ptr)
declare ptr @wolf_ws_on_message(ptr)
declare ptr @wolf_ws_on_close(ptr)
declare ptr @wolf_ws_send(i64, ptr)
declare void @wolf_ws_broadcast(ptr)
declare void @wolf_ws_join(i64, ptr)
declare void @wolf_ws_broadcast_to(ptr, ptr)
declare void @wolf_presence_track(i64, ptr)
declare ptr @wolf_presence_list(ptr)
declare void @wolf_ws_close(i64)

; --- Phase 1 Stdlib: Regex ---
declare i1 @wolf_preg_match(ptr, ptr)
declare ptr @wolf_preg_match_captures(ptr, ptr)
declare i64 @wolf_preg_match_all(ptr, ptr)
declare ptr @wolf_preg_replace(ptr, ptr, ptr)
declare ptr @wolf_preg_split(ptr, ptr)

; --- Math Extras ---
declare double @wolf_deg2rad(double)
declare double @wolf_rad2deg(double)
declare double @wolf_clamp(double, double, double)

; --- Type Casting ---
declare i64 @wolf_intval(ptr)
declare double @wolf_floatval(ptr)
declare ptr @wolf_strval(i64)
declare i1 @wolf_boolval(ptr)
declare i64 @wolf_intdiv(i64, i64)
declare ptr @wolf_gettype(ptr)
declare i1 @wolf_is_numeric(ptr)
declare ptr @wolf_typeof(ptr)
declare i1 @wolf_is_string(ptr)
declare i1 @wolf_is_int(ptr)
declare i1 @wolf_is_float(ptr)
declare i1 @wolf_is_bool(ptr)
declare i1 @wolf_is_null(ptr)
declare i1 @wolf_is_array(ptr)
declare ptr @wolf_settype(ptr, ptr)
declare ptr @wolf_money_format(i64, ptr)
declare i64 @wolf_money_add(i64, i64)
declare i64 @wolf_money_subtract(i64, i64)
declare i64 @wolf_money_multiply(i64, double)
declare i64 @wolf_money_divide(i64, double)
declare i64 @wolf_money_percentage(i64, double)
declare ptr @wolf_pluralise(ptr, i64)
declare ptr @wolf_phone_format(ptr, ptr)
declare void @wolf_log_debug(ptr)
declare void @wolf_retry_sleep(i64, i64)

; --- Encoding ---
declare ptr @wolf_base64_encode(ptr)
declare ptr @wolf_base64_decode(ptr)
declare ptr @wolf_json_pretty(ptr)
declare ptr @wolf_json_decode(ptr)

; --- Security & Crypto ---
declare ptr @wolf_md5(ptr)
declare ptr @wolf_sha256(ptr)
declare ptr @wolf_sha512(ptr)
declare ptr @wolf_hash(ptr, ptr)
declare ptr @wolf_hash_hmac(ptr, ptr, ptr)
declare i1 @wolf_hash_equals(ptr, ptr)
declare ptr @wolf_password_hash(ptr)
declare i1 @wolf_password_verify(ptr, ptr)
declare i1 @wolf_password_needs_rehash(ptr)
declare ptr @wolf_encrypt(ptr, ptr)
declare ptr @wolf_decrypt(ptr, ptr)
declare ptr @wolf_rand_bytes(i64)
declare ptr @wolf_rand_hex(i64)
declare ptr @wolf_rand_token()
declare ptr @wolf_uuid_v4()
declare ptr @wolf_uuid_v7()
declare ptr @wolf_nanoid(i64)
declare ptr @wolf_custom_id(ptr, i64)
declare ptr @wolf_base64_url_encode(ptr)
declare ptr @wolf_base64_url_decode(ptr)
declare ptr @wolf_hex_encode(ptr)
declare ptr @wolf_hex_decode(ptr)
declare ptr @wolf_jwt_encode(ptr, ptr)
declare ptr @wolf_jwt_decode(ptr, ptr)
declare ptr @wolf_jwt_decode_unverified(ptr)
declare i1 @wolf_jwt_expired(ptr)
declare ptr @wolf_curve25519_keypair()
declare ptr @wolf_curve25519_shared(ptr, ptr)
declare ptr @wolf_sign(ptr, ptr)
declare i1 @wolf_verify(ptr, ptr, ptr)

; --- Debugging ---
declare void @wolf_dump(ptr)
declare void @wolf_dd(ptr)
declare void @wolf_log_info(ptr)
declare void @wolf_log_warning(ptr)
declare void @wolf_log_error(ptr)

; --- Time & System ---
declare i64 @wolf_time_now()
declare ptr @wolf_time_date(ptr, i64)
declare i64 @wolf_time_strtotime(ptr)
declare void @wolf_system_sleep(i64)
declare void @wolf_system_exit(i64)
declare void @wolf_system_die(ptr)
declare void @wolf_thread_yield()
declare ptr @wolf_env_get(ptr, ptr)

; --- Phase 2: Arrays ---
declare i64 @wolf_count(ptr)
declare i1 @wolf_in_array(ptr, ptr)
declare i64 @wolf_array_search(ptr, ptr)
declare ptr @wolf_array_pop(ptr)
declare ptr @wolf_array_shift(ptr)
declare void @wolf_array_unshift(ptr, ptr)
declare ptr @wolf_array_reverse(ptr)
declare ptr @wolf_array_unique(ptr)
declare ptr @wolf_array_merge(ptr, ptr)
declare ptr @wolf_array_slice(ptr, i64, i64)
declare void @wolf_sort(ptr)
declare void @wolf_rsort(ptr)
declare double @wolf_array_sum(ptr)
declare ptr @wolf_array_keys(ptr)
declare ptr @wolf_array_values(ptr)
declare ptr @wolf_array_diff(ptr, ptr)
declare ptr @wolf_array_intersect(ptr, ptr)
declare ptr @wolf_array_flip(ptr)
declare ptr @wolf_range(i64, i64)

; --- Phase 2 Stdlib: Additional Array Functions ---
declare ptr @wolf_array_fill(i64, i64, ptr)
declare ptr @wolf_array_combine(ptr, ptr)
declare ptr @wolf_array_chunk(ptr, i64)
declare ptr @wolf_array_column(ptr, ptr)
declare double @wolf_array_product(ptr)
declare ptr @wolf_array_diff_key(ptr, ptr)
declare ptr @wolf_array_splice(ptr, i64, i64)
declare ptr @wolf_array_pad(ptr, i64, ptr)
declare ptr @wolf_array_count_values(ptr)
declare i64 @wolf_array_rand_one(ptr)
declare double @wolf_array_mean(ptr)
declare double @wolf_array_median(ptr)
declare ptr @wolf_array_mode(ptr)
declare double @wolf_array_variance(ptr)
declare double @wolf_array_std_dev(ptr)
declare double @wolf_array_percentile(ptr, double)

; --- Phase 3: Date/Time ---
declare i64 @wolf_time_ms()
declare i64 @wolf_time_ns()
declare i64 @wolf_mktime(i64, i64, i64, i64, i64, i64)
declare i64 @wolf_date_diff(i64, i64)
declare ptr @wolf_date_format(i64, ptr)
declare i64 @wolf_day_of_week(i64)
declare i64 @wolf_days_in_month(i64, i64)
declare i1 @wolf_is_leap_year(i64)
declare i64 @wolf_strtotime(ptr)
declare i64 @wolf_date_create(ptr)
declare i64 @wolf_date_add_days(i64, i64)
declare i64 @wolf_date_add_months(i64, i64)
declare i64 @wolf_date_diff_days(i64, i64)
declare i1 @wolf_date_is_past(i64)
declare i1 @wolf_date_is_future(i64)
declare ptr @wolf_date_to_iso(i64)

; --- Phase 3: Validation ---
declare i1 @wolf_is_email(ptr)
declare i1 @wolf_is_url(ptr)
declare i1 @wolf_is_phone(ptr)
declare i1 @wolf_is_uuid(ptr)
declare i1 @wolf_is_json(ptr)
declare i1 @wolf_is_ip(ptr)
declare i1 @wolf_is_alpha(ptr)
declare i1 @wolf_is_alpha_num(ptr)

; --- Phase 3: File System ---
declare i1 @wolf_file_exists(ptr)
declare ptr @wolf_file_read(ptr)
declare i1 @wolf_file_write(ptr, ptr)
declare i1 @wolf_file_append(ptr, ptr)
declare i1 @wolf_file_delete(ptr)
declare i64 @wolf_file_size(ptr)
declare ptr @wolf_file_extension(ptr)
declare ptr @wolf_file_basename(ptr)
declare ptr @wolf_file_dirname(ptr)
declare i1 @wolf_dir_exists(ptr)
declare i1 @wolf_file_copy(ptr, ptr)
declare i1 @wolf_file_move(ptr, ptr)
declare i1 @wolf_dir_create(ptr)
declare ptr @wolf_path_join(ptr, ptr)
declare ptr @wolf_scan_dir(ptr)
declare ptr @wolf_file_list_dir(ptr)
declare ptr @wolf_sys_getenv(ptr)
declare ptr @wolf_os_exec(ptr)

; --- Phase 3: Utilities ---
declare ptr @wolf_slug(ptr)
declare ptr @wolf_truncate(ptr, i64, ptr)

; --- STDLIB-08: Validation Rules Engine ---
declare ptr @wolf_validate(ptr, ptr)
declare i1 @wolf_validator_passes(ptr)
declare ptr @wolf_validator_errors(ptr)
declare ptr @wolf_validator_validated(ptr)

; --- DB-01: Query Builder ---
declare ptr @wolf_qb_create(ptr, ptr)
declare ptr @wolf_qb_with(ptr, ptr, ptr, ptr, ptr)
declare ptr @wolf_qb_where(ptr, ptr, ptr, ptr)
declare ptr @wolf_qb_order_by(ptr, ptr, ptr)
declare ptr @wolf_qb_limit(ptr, i64)
declare ptr @wolf_qb_offset(ptr, i64)
declare ptr @wolf_qb_get(ptr)
declare ptr @wolf_qb_first(ptr)
declare i64 @wolf_qb_insert(ptr, ptr)
declare i64 @wolf_qb_update(ptr, ptr)
declare i64 @wolf_qb_delete(ptr)
declare ptr @wolf_qb_paginate(ptr, i64, i64)

; --- Sessions ---
declare void @wolf_session_begin()
declare void @wolf_session_set(ptr, ptr)
declare ptr @wolf_session_get(ptr)
declare void @wolf_session_end()

; --- Define System (PHP-style constants) ---
declare void @wolf_define(ptr, ptr)
declare i1 @wolf_defined(ptr)
declare ptr @wolf_define_get(ptr)

; --- Redis ---
declare ptr @wolf_redis_connect(ptr, i64, ptr)
declare void @wolf_redis_set(ptr, ptr, i64)
declare ptr @wolf_redis_get(ptr)
declare i64 @wolf_redis_del(ptr)
declare i1 @wolf_redis_exists(ptr)
declare void @wolf_redis_hset(ptr, ptr, ptr)
declare ptr @wolf_redis_hget(ptr, ptr)
declare void @wolf_redis_close()

; --- Data Structures ---
declare ptr @wolf_array_create()
declare void @wolf_array_push(ptr, ptr)
declare ptr @wolf_array_get(ptr, i64)
declare i64 @wolf_array_length(ptr)
declare ptr @wolf_map_create()
declare void @wolf_map_set(ptr, ptr, ptr)
declare void @wolf_map_set_int(ptr, ptr, i64)
declare void @wolf_map_set_float(ptr, ptr, double)
declare void @wolf_map_set_bool(ptr, ptr, i1)
declare ptr @wolf_map_get(ptr, ptr)
declare ptr @wolf_class_create(ptr)
declare i1 @wolf_env_has(ptr)
declare ptr @wolf_val_int(i64)
declare ptr @wolf_val_float(double)
declare ptr @wolf_val_bool(i1)
declare ptr @wolf_val_array(ptr)

; --- Thread-Local Request Context ---
declare void @wolf_set_current_context(ptr, ptr)
declare ptr @wolf_get_request_body()
declare ptr @wolf_get_request_header(ptr)
declare ptr @wolf_get_request_method()
declare ptr @wolf_get_request_path()
declare ptr @wolf_input(ptr)
declare void @wolf_http_response_code(i64)
declare void @wolf_http_write_response(ptr)

; --- Phase 2: WolfScheduler ---
declare void @wolf_spawn_task(ptr)
declare void @wolf_task_wait_all()

; --- Phase 1: Concurrency (Legacy) ---
declare void @wolf_supervise_begin(i64, i64)
declare void @wolf_supervise_end()
declare void @wolf_trace_start(ptr)
declare void @wolf_trace_end(ptr)
declare void @wolf_metrics_increment(ptr)
declare void @wolf_metrics_gauge(ptr, double)
declare void @wolf_metrics_histogram(ptr, double)

; --- CLI Arguments ---
declare void @wolf_init_args(i32, ptr)
declare i64 @wolf_argc()
declare ptr @wolf_argv(i64)

; --- Sanitization ---
declare ptr @wolf_sanitize_string(ptr)
declare ptr @wolf_sanitize_email(ptr)
declare ptr @wolf_sanitize_url(ptr)
declare ptr @wolf_sanitize_int(ptr)
declare ptr @wolf_sanitize_float(ptr)

; --- HTTP Server (C FFI) ---
declare void @wolf_http_serve(i64, ptr)
declare ptr @wolf_http_req_method(i64)
declare ptr @wolf_http_req_path(i64)
declare ptr @wolf_http_req_query(i64, ptr)
declare ptr @wolf_http_req_header(i64, ptr)
declare ptr @wolf_http_req_body(i64)
declare void @wolf_http_res_header(i64, ptr, ptr)
declare void @wolf_http_res_status(i64, i64)
declare void @wolf_http_res_write(i64, ptr)

; --- HTTP Client (libcurl) ---
declare ptr @wolf_http_request(ptr, ptr, ptr, ptr)
declare ptr @wolf_http_get(ptr, ptr)
declare ptr @wolf_http_post(ptr, ptr, ptr)
declare ptr @wolf_http_put(ptr, ptr, ptr)
declare ptr @wolf_http_delete(ptr, ptr)
declare ptr @wolf_http_patch(ptr, ptr, ptr)
declare ptr @wolf_http_set_header(ptr, ptr, ptr)
declare ptr @wolf_http_client_res_body(ptr)
declare ptr @wolf_http_client_res_json(ptr)
declare i64 @wolf_http_client_res_status(ptr)
declare i64 @wolf_http_client_res_ok(ptr)
declare i64 @wolf_http_client_res_failed(ptr)
declare ptr @wolf_http_client_res_header(ptr, ptr)
declare ptr @wolf_url_encode(ptr)
declare ptr @wolf_url_decode(ptr)
declare ptr @wolf_url_parse(ptr)
declare ptr @wolf_build_query(ptr)
declare ptr @wolf_dns_lookup(ptr)
declare ptr @wolf_get_client_ip()
declare i64 @wolf_socket_create(i64, i64, i64)
declare i64 @wolf_socket_connect(i64, ptr, i64)
declare i64 @wolf_socket_send(i64, ptr)
declare ptr @wolf_socket_recv(i64, i64)
declare void @wolf_socket_close(i64)


define ptr @__wrapper_wolf_handler(ptr %__env_ignored, ptr %arg0, ptr %arg1) {
entry:
  %res = call ptr @wolf_handler(ptr %arg0, ptr %arg1)
  ret ptr %res
}

define ptr @__wrapper_wolf_ws_handler(ptr %__env_ignored, ptr %arg0, ptr %arg1) {
entry:
  %res = call ptr @wolf_ws_handler(ptr %arg0, ptr %arg1)
  ret ptr %res
}
define void @wolf_assert(i1 %cond.arg, ptr %msg.arg) {
entry:
  %cond = alloca i1
  %msg = alloca ptr
  store i1 %cond.arg, ptr %cond
  store ptr %msg.arg, ptr %msg
  %t1 = load i1, ptr %cond
  %t2 = xor i1 %t1, 1
  br i1 %t2, label %if.then.1, label %if.end.2
if.then.1:
  %t3 = load ptr, ptr %msg
  call void @wolf_throw(ptr %t3)
  %t4 = call i1 @wolf_has_error()
  br i1 %t4, label %err.true.3, label %err.false.4

err.true.3:
    ret void

err.false.4:
  br label %if.end.2
if.end.2:
  ret void
}

define void @wolf_test_debug() {
entry:
  %tokens = alloca ptr
  %ast = alloca ptr
  %i = alloca i64
  %src = alloca ptr
  %lexer = alloca ptr
  %p = alloca ptr
  %errs = alloca ptr
  %j = alloca i64
  %stmt = alloca ptr
  %t5 = getelementptr [36 x i8], ptr @.str.1, i64 0, i64 0
  store ptr %t5, ptr %src
  %t6 = load ptr, ptr %src
  %t7 = getelementptr [10 x i8], ptr @.str.2, i64 0, i64 0
  %t8 = call ptr @wolf_NewLexer(ptr %t6, ptr %t7)
  %t9 = call i1 @wolf_has_error()
  br i1 %t9, label %err.true.5, label %err.false.6

err.true.5:
    ret void

err.false.6:
  store ptr %t8, ptr %lexer
  %t10 = load ptr, ptr %lexer
  ; DEBUG ident.Name=lexer, varClass=Lexer
  ; DEBUG directName=Lexer_Tokenize, foundInSigs=false
  call void @Tokenize(ptr %t10)
  %t12 = call i1 @wolf_has_error()
  br i1 %t12, label %err.true.7, label %err.false.8

err.true.7:
    ret void

err.false.8:
  store ptr null, ptr %tokens
  %t13 = load ptr, ptr %tokens
  %t14 = getelementptr [10 x i8], ptr @.str.2, i64 0, i64 0
  %t15 = load ptr, ptr %src
  %t16 = call ptr @wolf_NewParser(ptr %t13, ptr %t14, ptr %t15)
  %t17 = call i1 @wolf_has_error()
  br i1 %t17, label %err.true.9, label %err.false.10

err.true.9:
    ret void

err.false.10:
  store ptr %t16, ptr %p
  %t18 = load ptr, ptr %p
  ; DEBUG ident.Name=p, varClass=Parser
  ; DEBUG directName=Parser_Parse, foundInSigs=false
  call void @Parse(ptr %t18)
  %t20 = call i1 @wolf_has_error()
  br i1 %t20, label %err.true.11, label %err.false.12

err.true.11:
    ret void

err.false.12:
  store ptr null, ptr %ast
  %t21 = load ptr, ptr %p
  ; DEBUG ident.Name=p, varClass=Parser
  ; DEBUG directName=Parser_Errors, foundInSigs=false
  call void @Errors(ptr %t21)
  %t23 = call i1 @wolf_has_error()
  br i1 %t23, label %err.true.13, label %err.false.14

err.true.13:
    ret void

err.false.14:
  store ptr null, ptr %errs
  %t24 = getelementptr [9 x i8], ptr @.str.3, i64 0, i64 0
  %t25 = load ptr, ptr %errs
  %t26 = call i64 @wolf_count(ptr %t25)
  %t27 = call i1 @wolf_has_error()
  br i1 %t27, label %err.true.15, label %err.false.16

err.true.15:
    ret void

err.false.16:
  %t28 = call ptr @wolf_int_to_string(i64 %t26)
  %t29 = call ptr @wolf_string_concat(ptr %t24, ptr %t28)
  call void @wolf_print_str(ptr %t29)
  call void @wolf_println()
  store i64 0, ptr %j
  br label %for.cond.17
for.cond.17:
  %t30 = load i64, ptr %j
  %t31 = load ptr, ptr %errs
  %t32 = call i64 @wolf_count(ptr %t31)
  %t33 = call i1 @wolf_has_error()
  br i1 %t33, label %err.true.21, label %err.false.22

err.true.21:
    ret void

err.false.22:
  %t34 = icmp slt i64 %t30, %t32
  br i1 %t34, label %for.body.18, label %for.end.20
for.body.18:
  call void @wolf_thread_yield()
  %t35 = getelementptr [6 x i8], ptr @.str.4, i64 0, i64 0
  %t36 = load ptr, ptr %errs
  %t37 = load i64, ptr %j
  %t38 = call ptr @wolf_array_get(ptr %t36, i64 %t37)
  %t39 = getelementptr [8 x i8], ptr @.str.5, i64 0, i64 0
  %t40 = call ptr @wolf_map_get(ptr %t38, ptr %t39)
  %t41 = call ptr @wolf_string_concat(ptr %t35, ptr %t40)
  call void @wolf_print_str(ptr %t41)
  call void @wolf_println()
  %t42 = load i64, ptr %j
  %t43 = add i64 %t42, 1
  store i64 %t43, ptr %j
  br label %for.update.19
for.update.19:
  br label %for.cond.17
for.end.20:
  %t44 = getelementptr [13 x i8], ptr @.str.6, i64 0, i64 0
  %t45 = load ptr, ptr %ast
  %t46 = getelementptr [11 x i8], ptr @.str.7, i64 0, i64 0
  %t47 = call ptr @wolf_map_get(ptr %t45, ptr %t46)
  %t48 = call i64 @wolf_count(ptr %t47)
  %t49 = call i1 @wolf_has_error()
  br i1 %t49, label %err.true.23, label %err.false.24

err.true.23:
    ret void

err.false.24:
  %t50 = call ptr @wolf_int_to_string(i64 %t48)
  %t51 = call ptr @wolf_string_concat(ptr %t44, ptr %t50)
  call void @wolf_print_str(ptr %t51)
  call void @wolf_println()
  store i64 0, ptr %i
  br label %for.cond.25
for.cond.25:
  %t52 = load i64, ptr %i
  %t53 = load ptr, ptr %ast
  %t54 = getelementptr [11 x i8], ptr @.str.7, i64 0, i64 0
  %t55 = call ptr @wolf_map_get(ptr %t53, ptr %t54)
  %t56 = call i64 @wolf_count(ptr %t55)
  %t57 = call i1 @wolf_has_error()
  br i1 %t57, label %err.true.29, label %err.false.30

err.true.29:
    ret void

err.false.30:
  %t58 = icmp slt i64 %t52, %t56
  br i1 %t58, label %for.body.26, label %for.end.28
for.body.26:
  call void @wolf_thread_yield()
  %t59 = load ptr, ptr %ast
  %t60 = getelementptr [11 x i8], ptr @.str.7, i64 0, i64 0
  %t61 = call ptr @wolf_map_get(ptr %t59, ptr %t60)
  %t62 = load i64, ptr %i
  %t63 = call ptr @wolf_array_get(ptr %t61, i64 %t62)
  store ptr %t63, ptr %stmt
  %t64 = getelementptr [6 x i8], ptr @.str.8, i64 0, i64 0
  %t65 = load i64, ptr %i
  %t66 = call ptr @wolf_int_to_string(i64 %t65)
  %t67 = call ptr @wolf_string_concat(ptr %t64, ptr %t66)
  %t68 = getelementptr [3 x i8], ptr @.str.9, i64 0, i64 0
  %t69 = call ptr @wolf_string_concat(ptr %t67, ptr %t68)
  %t70 = load ptr, ptr %stmt
  %t71 = getelementptr [5 x i8], ptr @.str.10, i64 0, i64 0
  %t72 = call ptr @wolf_map_get(ptr %t70, ptr %t71)
  %t73 = call ptr @wolf_string_concat(ptr %t69, ptr %t72)
  call void @wolf_print_str(ptr %t73)
  call void @wolf_println()
  %t74 = load ptr, ptr %stmt
  %t75 = getelementptr [5 x i8], ptr @.str.10, i64 0, i64 0
  %t76 = call ptr @wolf_map_get(ptr %t74, ptr %t75)
  %t77 = getelementptr [8 x i8], ptr @.str.11, i64 0, i64 0
  %t79 = call i64 @wolf_strcmp(ptr %t76, ptr %t77)
  %t78 = icmp eq i64 %t79, 0
  br i1 %t78, label %if.then.31, label %if.end.32
if.then.31:
  %t80 = getelementptr [8 x i8], ptr @.str.12, i64 0, i64 0
  %t81 = load ptr, ptr %stmt
  %t82 = getelementptr [5 x i8], ptr @.str.13, i64 0, i64 0
  %t83 = call ptr @wolf_map_get(ptr %t81, ptr %t82)
  %t84 = call ptr @wolf_string_concat(ptr %t80, ptr %t83)
  call void @wolf_print_str(ptr %t84)
  call void @wolf_println()
  br label %if.end.32
if.end.32:
  %t85 = load i64, ptr %i
  %t86 = add i64 %t85, 1
  store i64 %t86, ptr %i
  br label %for.update.27
for.update.27:
  br label %for.cond.25
for.end.28:
  ret void
}

define void @wolf_handler(ptr %req_id.arg, ptr %res_id.arg) {
entry:
  %req_id = alloca ptr
  %res_id = alloca ptr
  %path = alloca ptr
  store ptr %req_id.arg, ptr %req_id
  store ptr %res_id.arg, ptr %res_id
  %t87 = call ptr @wolf_get_request_path()
  %t88 = call i1 @wolf_has_error()
  br i1 %t88, label %err.true.33, label %err.false.34

err.true.33:
    ret void

err.false.34:
  store ptr %t87, ptr %path
  %t89 = load ptr, ptr %path
  %t90 = getelementptr [6 x i8], ptr @.str.14, i64 0, i64 0
  %t92 = call i64 @wolf_strcmp(ptr %t89, ptr %t90)
  %t91 = icmp eq i64 %t92, 0
  br i1 %t91, label %if.then.35, label %if.else.37
if.then.35:
  %t93 = getelementptr [63 x i8], ptr @.str.15, i64 0, i64 0
  call void @wolf_print_str(ptr %t93)
  call void @wolf_println()
  call void @wolf_system_sleep(i64 60)
  %t95 = call i1 @wolf_has_error()
  br i1 %t95, label %err.true.38, label %err.false.39

err.true.38:
    ret void

err.false.39:
  %t96 = getelementptr [53 x i8], ptr @.str.16, i64 0, i64 0
  call void @wolf_print_str(ptr %t96)
  call void @wolf_println()
  %t97 = getelementptr [23 x i8], ptr @.str.17, i64 0, i64 0
  %t98 = call ptr @wolf_http_write_response(ptr %t97)
  %t99 = call i1 @wolf_has_error()
  br i1 %t99, label %err.true.40, label %err.false.41

err.true.40:
    ret void

err.false.41:
  br label %if.end.36
if.else.37:
  %t100 = getelementptr [17 x i8], ptr @.str.18, i64 0, i64 0
  %t101 = call ptr @wolf_http_write_response(ptr %t100)
  %t102 = call i1 @wolf_has_error()
  br i1 %t102, label %err.true.42, label %err.false.43

err.true.42:
    ret void

err.false.43:
  br label %if.end.36
if.end.36:
  ret void
}

define void @wolf_handler(ptr %req_id.arg, ptr %res_id.arg) {
entry:
  %html = alloca ptr
  %req_id = alloca ptr
  %res_id = alloca ptr
  %path = alloca ptr
  store ptr %req_id.arg, ptr %req_id
  store ptr %res_id.arg, ptr %res_id
  %t103 = call ptr @wolf_get_request_path()
  %t104 = call i1 @wolf_has_error()
  br i1 %t104, label %err.true.44, label %err.false.45

err.true.44:
    ret void

err.false.45:
  store ptr %t103, ptr %path
  %t105 = load ptr, ptr %path
  %t106 = getelementptr [2 x i8], ptr @.str.19, i64 0, i64 0
  %t108 = call i64 @wolf_strcmp(ptr %t105, ptr %t106)
  %t107 = icmp eq i64 %t108, 0
  br i1 %t107, label %if.then.46, label %if.end.47
if.then.46:
  %t109 = load ptr, ptr %res_id
  %t110 = call i64 @wolf_intval(ptr %t109)
  %t111 = getelementptr [13 x i8], ptr @.str.20, i64 0, i64 0
  %t112 = getelementptr [10 x i8], ptr @.str.21, i64 0, i64 0
  %t113 = call ptr @wolf_http_res_header(i64 %t110, ptr %t111, ptr %t112)
  %t114 = call i1 @wolf_has_error()
  br i1 %t114, label %err.true.48, label %err.false.49

err.true.48:
    ret void

err.false.49:
  %t115 = getelementptr [21 x i8], ptr @.str.22, i64 0, i64 0
  %t116 = call ptr @wolf_file_read(ptr %t115)
  %t117 = call i1 @wolf_has_error()
  br i1 %t117, label %err.true.50, label %err.false.51

err.true.50:
    ret void

err.false.51:
  store ptr %t116, ptr %html
  %t118 = load ptr, ptr %html
  %t119 = call ptr @wolf_http_write_response(ptr %t118)
  %t120 = call i1 @wolf_has_error()
  br i1 %t120, label %err.true.52, label %err.false.53

err.true.52:
    ret void

err.false.53:
  br label %if.end.47
if.end.47:
  ret void
}

define void @wolf_ws_handler(ptr %req_id.arg, ptr %message.arg) {
entry:
  %req_id = alloca ptr
  %message = alloca ptr
  %path = alloca ptr
  store ptr %req_id.arg, ptr %req_id
  store ptr %message.arg, ptr %message
  %t121 = call ptr @wolf_get_request_path()
  %t122 = call i1 @wolf_has_error()
  br i1 %t122, label %err.true.54, label %err.false.55

err.true.54:
    ret void

err.false.55:
  store ptr %t121, ptr %path
  %t123 = getelementptr [13 x i8], ptr @.str.23, i64 0, i64 0
  %t124 = load ptr, ptr %message
  %t125 = call ptr @wolf_string_concat(ptr %t123, ptr %t124)
  %t126 = getelementptr [10 x i8], ptr @.str.24, i64 0, i64 0
  %t127 = call ptr @wolf_string_concat(ptr %t125, ptr %t126)
  %t128 = load ptr, ptr %path
  %t129 = call ptr @wolf_string_concat(ptr %t127, ptr %t128)
  call void @wolf_print_str(ptr %t129)
  call void @wolf_println()
  %t130 = load ptr, ptr %req_id
  %t131 = call i64 @wolf_intval(ptr %t130)
  %t132 = getelementptr [7 x i8], ptr @.str.25, i64 0, i64 0
  %t133 = load ptr, ptr %message
  %t134 = call ptr @wolf_string_concat(ptr %t132, ptr %t133)
  %t135 = getelementptr [20 x i8], ptr @.str.26, i64 0, i64 0
  %t136 = call ptr @wolf_string_concat(ptr %t134, ptr %t135)
  %t137 = load ptr, ptr %path
  %t138 = call ptr @wolf_string_concat(ptr %t136, ptr %t137)
  %t139 = call ptr @wolf_ws_send(i64 %t131, ptr %t138)
  %t140 = call i1 @wolf_has_error()
  br i1 %t140, label %err.true.56, label %err.false.57

err.true.56:
    ret void

err.false.57:
  ret void
}

define i1 @wolf___compiler_dispatch_controller(ptr %c.arg, ptr %m.arg, ptr %args.arg, ptr %req.arg, ptr %res.arg) {
entry:
  %c = alloca ptr
  %m = alloca ptr
  %args = alloca ptr
  %req = alloca ptr
  %res = alloca ptr
  store ptr %c.arg, ptr %c
  store ptr %m.arg, ptr %m
  store ptr %args.arg, ptr %args
  store ptr %req.arg, ptr %req
  store ptr %res.arg, ptr %res
  ret i1 0
}

define ptr @wolf___compiler_create_model(ptr %name.arg) {
entry:
  %name = alloca ptr
  store ptr %name.arg, ptr %name
  ret ptr null
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  call void @wolf_init_args(i32 %argc, ptr %argv)
  %passed = alloca i64
  %failed = alloca i64
  %e = alloca ptr
  store i64 0, ptr %passed
  store i64 0, ptr %failed
  %t141 = getelementptr [43 x i8], ptr @.str.27, i64 0, i64 0
  call void @wolf_print_str(ptr %t141)
  call void @wolf_println()
  %t142 = call ptr @wolf_closure_create(ptr @__wrapper_wolf_handler, i64 0)
  %t143 = call ptr @wolf_http_serve(i64 8080, ptr %t142)
  %t144 = call i1 @wolf_has_error()
  br i1 %t144, label %err.true.58, label %err.false.59

err.true.58:
    ret i32 1

err.false.59:
  %t145 = call ptr @wolf_closure_create(ptr @__wrapper_wolf_ws_handler, i64 0)
  %t146 = call ptr @wolf_ws_on_message(ptr %t145)
  %t147 = call i1 @wolf_has_error()
  br i1 %t147, label %err.true.60, label %err.false.61

err.true.60:
    ret i32 1

err.false.61:
  %t148 = getelementptr [47 x i8], ptr @.str.28, i64 0, i64 0
  call void @wolf_print_str(ptr %t148)
  call void @wolf_println()
  %t149 = call ptr @wolf_closure_create(ptr @__wrapper_wolf_handler, i64 0)
  %t150 = call ptr @wolf_http_serve(i64 8080, ptr %t149)
  %t151 = call i1 @wolf_has_error()
  br i1 %t151, label %err.true.62, label %err.false.63

err.true.62:
    ret i32 1

err.false.63:
  call void @wolf_clear_error()
  call void @wolf_test_debug()
  %t153 = call i1 @wolf_has_error()
  br i1 %t153, label %err.true.66, label %err.false.67

err.true.66:
    br label %catch.64

err.false.67:
  %t154 = getelementptr [15 x i8], ptr @.str.29, i64 0, i64 0
  call void @wolf_print_str(ptr %t154)
  call void @wolf_println()
  %t155 = load i64, ptr %passed
  %t156 = add i64 %t155, 1
  store i64 %t156, ptr %passed
  br label %try.done.65

catch.64:
    %t157 = call ptr @wolf_get_error()
    store ptr %t157, ptr %e
    %t158 = getelementptr [26 x i8], ptr @.str.30, i64 0, i64 0
    %t159 = load ptr, ptr %e
    %t160 = call ptr @wolf_string_concat(ptr %t158, ptr %t159)
    call void @wolf_print_str(ptr %t160)
    call void @wolf_println()
    %t161 = load i64, ptr %failed
    %t162 = add i64 %t161, 1
    store i64 %t162, ptr %failed
    br label %try.done.65

try.done.65:
  %t163 = getelementptr [9 x i8], ptr @.str.31, i64 0, i64 0
  %t164 = load i64, ptr %passed
  %t165 = call ptr @wolf_int_to_string(i64 %t164)
  %t166 = call ptr @wolf_string_concat(ptr %t163, ptr %t165)
  %t167 = getelementptr [10 x i8], ptr @.str.32, i64 0, i64 0
  %t168 = call ptr @wolf_string_concat(ptr %t166, ptr %t167)
  %t169 = load i64, ptr %failed
  %t170 = call ptr @wolf_int_to_string(i64 %t169)
  %t171 = call ptr @wolf_string_concat(ptr %t168, ptr %t170)
  %t172 = getelementptr [8 x i8], ptr @.str.33, i64 0, i64 0
  %t173 = call ptr @wolf_string_concat(ptr %t171, ptr %t172)
  call void @wolf_print_str(ptr %t173)
  call void @wolf_println()
  %t174 = load i64, ptr %failed
  %t175 = icmp sgt i64 %t174, 0
  br i1 %t175, label %if.then.68, label %if.end.69
if.then.68:
  call void @wolf_system_exit(i64 1)
  %t177 = call i1 @wolf_has_error()
  br i1 %t177, label %err.true.70, label %err.false.71

err.true.70:
    ret i32 1

err.false.71:
  br label %if.end.69
if.end.69:
  ret i32 0
}
